### ISSUE TITLE
Permission Denied Error When Changing Between Node Version

### ISSUE THREAD

**Issue by grayghostvisuals** [tj/n#115]
running `n` and selecting the version I would like of node (in this case 10.5) I get the following error which I can override by running `sudo n` Seems like this is normal? Still a newb to node and `n`.
`/usr/local/bin/n: line 244: /usr/local/n/versions/.prev: Permission denied`

**Comment by shanimal** [comment]
fwiw chown on /usr/local left my terminal inoperable. I had to CMD+R during reboot and use the disk utility to get the correct permissions reset.

**Comment by tjwebb** [comment]
> fwiw chown on /usr/local left my terminal inoperable

What is the actual command you ran?

**Comment by shanimal** [comment]
Not sure, maybe `sudo rm -rf /usr/local` **;)**
