### ISSUE TITLE
Got Error message "Error: invalid version 0.10.8" while using n in FreeBSD

### ISSUE THREAD

**Issue by benpptung** [tj/n#116]
Today, I try to install Node.js on FreeBSD by using the port tree /www/node, /www/npm,
Then, I install npm n by:

```
# npm install -g n
```

The current version of /www/node at FreeBSD is 0.10.5, so I issue the following command, and hope to upgrade to node.js 0.10.8:

```
# n stable
```

However, I got the following error

```
install : 0.10.8

Error: invalid version 0.10.8
```

Don't know why I cannot use n to upgrade node.js, 
Is this a problem because I use port tree to install node.js?

Thank you in advance, and please advise.

**Comment by gshireesh** [comment]
installing curl fixes problem for me.

**Comment by chengjaun** [comment]
I have the same problem, follow the answer of installing the curl, but I still get the same error.what can I do
