### ISSUE TITLE
add support for "x", "d", or delete to remove a selected version

### ISSUE THREAD

**Issue by tj** [tj/n#139]
in the `n` interactive listing

**Comment by tedgaydos** [comment]
I am going to look into adding some more features to the interactive menu.

**Comment by maxrimue** [comment]
@tedgaydos Would we want to add this to 1.x.x too? Or is the branch just for bug fixes?

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
