### ISSUE TITLE
Doesn't work on ARM platform

### ISSUE THREAD

**Issue by legege** [tj/n#147]
Using a BeagleBone Black, it doesn't work on this platform. Should compile from source.
Linux ubuntu-armhf 3.8.13-bone20 #1 SMP Wed May 29 10:49:26 UTC 2013 armv7l armv7l armv7l GNU/Linux

**Comment by ralphtheninja** [comment]
@legege Can you check again? This issue might fix your problem https://github.com/maxrimue/n/commit/f0f2bccd2874231fa423557496597e5e05554e93 

If it works. Please close this issue. Thanks!

**Comment by maxrimue** [comment]
@ralphtheninja @legege You have to use io.js though, since Node.js never provided any ARMv7 binaries in its dist.

**Comment by ralphtheninja** [comment]
@maxrimue Aaah ok. Thanks for info!

**Comment by maxrimue** [comment]
Closed as of the merged PR #234
