### ISSUE TITLE
Errors on Raspberry Pi

### ISSUE THREAD

**Issue by nayrangnu** [tj/n#149]
I was getting ```Error: invalid version [version]``` for every version I tried on my RPi. By checking the tarball urls, then checking the nodejs repo (http://nodejs.org/dist/) I realized that not every version of node has a corresponding ```-linux-arm-pi``` version. Instead of ```0.10.20```, ```0.10.17``` worked (this appears to be the latest version with a ```-linux-arm-pi``` version). Should there be a more robust error message for pi users?
It is also an issue that the script uses ```#!/usr/bin/env sh``` instead of ```#!/bin/bash```, as the ```read``` command (used for the version selection interface) throws fatal errors.

**Comment by maxrimue** [comment]
All Raspberry Pis are supported now
