### ISSUE TITLE
Symlink location and permissions in Ubuntu

### ISSUE THREAD

**Issue by akamensky** [tj/n#167]
I remember some time ago `n` had issue in Ubuntu where it would not symlink binary file to correct directory. Seems that this issue has made its way back to life:

node binary from official repository is located in `/usr/local/sbin/` and `n` creates binary (instead of symlink) in `/usr/local/bin/`. Usually PATH looks like `/usr/local/sbin:/usr/local/bin:/usr/sbin:.......` which makes anything done by `n` useless. And also this binary has permissions set to 0700  which makes it non executable by any user other than root.

**Comment by qw3rtman** [comment]
Are you still having this issue @akamensky?

**Comment by troy0820** [comment]
I'm closing this issue because it's been over a year.  If this issue needs to remain open, please comment in the comments @akamensky
