### ISSUE TITLE
How to uninstall n?

### ISSUE THREAD

**Issue by kamikat** [tj/n#169]
I'm wondering how to clean up my `/usr/local` directory after use `n` to switch between versions?

**Comment by bennybennet** [comment]
Error: cannot remove currently active version (node/6.2.2)

**Comment by qw3rtman** [comment]
@bennybennet, are you trying to remove `n` or just a specific Node version installed by `n`?

**Comment by bennybennet** [comment]
tried to remove n but wanted to remove all node versions before.

**Comment by qw3rtman** [comment]
@bennybennet, you should just be able to `npm rm -g n` and then `rm -rf /usr/local/bin`. The version you were last using will remain (at `/usr/local/bin/node`) along with `npm` (at `/usr/local/lib/node_modules/npm/bin/npm`).

**Comment by vergenzt** [comment]
I know this is an older issue, but I thought it worth commenting: If you installed via the method mentioned in the docs,

> Additionally, consider third-party installer [n-install](https://github.com/mklement0/n-install), which allows installation directly from GitHub; for instance,
> 
>     curl -L https://git.io/n-install | bash
> 
> sets both `PREFIX` and `N_PREFIX` to `$HOME/n`, installs `n` to `$HOME/n/bin`, modifies the initialization files of supported shells to export `N_PREFIX` and add `$HOME/n/bin` to the `PATH`, and installs the latest stable `node` version.
> 
> As a result, both `n` itself and all `node` versions it manages are hosted inside a single, optionally configurable directory, which you can later remove with the included `n-uninstall` script. `n-update` updates `n` itself to the latest version. See the [n-install repo](https://github.com/mklement0/n-install) for more details.

then all you have to do is invoke `~/n/n-uninstall`. :) 

I had forgotten I used this method to install `n` and happened to find that script as I was manually cleaning things up. Thought I'd pass along the reminder.

**Comment by earthbound19** [comment]
At this writing I find the uninstall script at `~/n/bin/n-uninstall`.

**Comment by trusktr** [comment]
> ~/n/n-uninstall

That's not official. `n` should include something like this, to make it clear _exactly_ how to remove n and **all** versions installed by n, leaving only (for example) the `node` installed by Ubuntu's `apt-get`. 

Basically, if I run

```sh
sudo apt-get install nodejs
sudo npm i -g n
sudo n 8
```

then, I simply want to go back to the state I had before as if I had ran only

```sh
sudo apt-get install nodejs
```

. So, if I intuitively try to do that like this:

```sh
sudo apt-get install nodejs
sudo npm i -g n
sudo n 8 # it installed 8.9.4
sudo n rm 8.9.4
 Error: cannot remove currently active version (node/8.9.4)
```

So (officially) we're stuck. Then, eventually, we might find something (unofficial) like `~/n/n-uninstall` by stumbling here, which just doesn't seem right. The point of `n` is to manage versions, so being able to uninstall all versions should obviously be part of.... managing versions.

Furthermore, I didn't install `n` with `n-install`, so, now I have to go read a long bash script to make sure I can clean up?

This should just be built into `n`.

**Comment by trusktr** [comment]
Seriously, this sort of thing is annoying.

**Comment by ryanmtaylor** [comment]
why not have "system" as a choice for nodes within n?

**Comment by earthbound19** [comment]
Why on earth is this issue closed? It is clearly not resolved satisfactorily.

**Comment by mesqueeb** [comment]
I came to a thread hoping to find the solution:
**How to how to remove n and all versions installed by n?**

Does anyone know the correct way?

**Comment by JohnRGee** [comment]
To be sure how to remove n we would need to know: How did you install `n`? Have you set the `N_PREFIX` environment variable to change the default install location `n` uses for installing `node`? 

And some answers for the most common situations:

1) If you installed `n` using
```bash
sudo npm install --global n
```

then you uninstall it using 

```bash
sudo npm uninstall --global n
```

2) If N_PREFIX is not set then `n` installs to `usr/local` by default and stores the downloaded versions in `/usr/local/n/versions`. To remove all the downloaded versions and the directory you can use:

```bash
sudo rm -rf /usr/local/n
```

3) If N_PREFIX is set, then delete the `"${N_PREFIX}/n"` directory. And if you are not storing anything else in the N_PREFIX directory, you can delete the whole directory to delete both the downloaded versions and the installed current version.

To see if N_PREFIX is set you can run:

echo "N_PREFIX is: ${N_PREFIX}"

**Comment by shadowspawn** [comment]
I have opened a new issue with some research and ideas about what we might do in future. Subscribe to that issue for updates and/or give it a 👍 
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
`n uninstall` has been added in v4.1.0. It deletes node and npm from the install destination (`N_PREFIX` or `/usr/local`). It does not affect the cached downloaded versions.

**Comment by NikitaKA** [comment]
I'm trying to uninstall `n`, but:

If I try `n uninstall` I get:
```
Error: invalid version uninstall
```

If I try `npm r -g n`:
```
up to date in 0.089s
```

If I try `npm i -g n`:
```
npm ERR! Cannot read property 'resolve' of undefined
```

If I try `npm list`:
```
/mnt/c/Users/nikit
└── (empty)
```

What am I doing wrong? :)

**Comment by shadowspawn** [comment]
@NikitaKA 

Do you remember how you installed n? (Using npm? Using n-install? Using brew?)

What does this show?
```
command -v n
```

**Comment by NikitaKA** [comment]
I'm using Windows 10 Linux Subsystem (if that matters), `n` is installed via `npm` (95% sure). 

`command -v n`:
```
/usr/bin/n
```

**Comment by shadowspawn** [comment]
Interesting, that is not the default install location for npm global packages, so may be something custom about your setup.

The three things to delete are the n package, the n command (usually a link to the package), and the cache folder. Given you don't have a default setup and npm is not listing n, some more questions so I can hopefully give you some accurate bespoke instructions.

What do these show:
```
ls -l /usr/bin/n
ls -d /usr/n
ls -d /usr/local/n
echo $N_PREFIX
```

**Comment by NikitaKA** [comment]
**ls -l /usr/bin/n**
`ls: cannot access '/usr/bin/n': No such file or directory`

**ls -d /usr/local/n**
`/usr/local/n`

**echo $N_PREFIX**
(empty)

Thank you for help!

**Comment by shadowspawn** [comment]
Ok, manual cleanup for your setup, all that is left is the cache:
```
sudo rm -rf /usr/local/n
```

**Comment by NikitaKA** [comment]
I did that, but `n` was still in the system: `/usr/local/bin/n`
So I `rm -rf` it too. Now everything is fine. Thank you very much.
