### ISSUE TITLE
Cannot switch version of node

### ISSUE THREAD

**Issue by samholmes** [tj/n#170]
```
npm install -g n
n install 0.8.26
n
node -v
```

I ran these commands. On the third command I chose 0.8.26 from the prompt, then hit enter. I on the final command I still get the output:

```
v0.10.26
```

So, apparently, n isn't working. Why?

**Comment by shadowspawn** [comment]
`n` v6.1.2 has additional output for the situation when node command location changes, and the old location may be remembered by the current shell.

e.g.
```
Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"
```
 (Longer transcript: https://github.com/tj/n/issues/588#issuecomment-554601529)
