### ISSUE TITLE
reloading the same version

### ISSUE THREAD

**Issue by alexahn** [tj/n#171]
When installing global packages via the npm installed for the particular version of node, the binaries are not made available immediately. It seems the binaries/lib directories are copied to /usr/local/lib/node_modules and /usr/local/bin (on my particular OS) when n switches between versions. In the case that there is only one version of node installed, this seems to be somewhat problematic. I'd like to use the node-versioned npm to manage node-versioned global packages, and have packages installed in this manner be available immediately.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
