### ISSUE TITLE
completion for n

### ISSUE THREAD

**Issue by hotoo** [tj/n#181]
https://github.com/hotoo/.n-completion

```
$ n li<Tab>
```

**Comment by qw3rtman** [comment]
Just tested on OS X El Capitan and the completion didn't work. If this is still a feature you'd like to see added to `n`, send in a PR with a working version.

Personally, one benefit of `n` is that the commands are short enough that typing takes very little time, making autocompletion unnecessary.

Tested on:
```
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin14.5.0)
zsh 5.0.8 (x86_64-apple-darwin15.0)
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
```
