### ISSUE TITLE
remove "prev" command in 1.3

### ISSUE THREAD

**Issue by tjwebb** [tj/n#184]
what are everyone's thoughts on this? I personally find it more confusing than helpful, and prone to off-by-one situations

**Comment by tedgaydos** [comment]
:+1: 

I never use prev. I would just switch to the version number. It's not like we are typing that much more to achieve the same outcome.

**Comment by maxrimue** [comment]
:+1: Same over here

**Comment by tedgaydos** [comment]
I am going to submit a PR to remove this.

I ran into an interesting case that breaks the state of n when using prev.

n 0.12.0
> installs 0.12.0
n 0.12.1
> installs 0.12.1 and prev store 0.12.0
n rm 0.12.0
> removes 0.12.0
n prev
> script runs and nothing is copied. Active is not set to a value.
n
> select comes up and nothing works. Only another call to n prev will fix it.

**Comment by tjwebb** [comment]
I think prev is weird also

**Comment by tjwebb** [comment]
This would have to constitute a new major version, though. Because semver

**Comment by knownasilya** [comment]
I use 'prev', mainly for cleanup in https://github.com/Strider-CD/strider-node

**Comment by tedgaydos** [comment]
I just took a look at your project. I have to say it is very impressive. Good work.

As for the way you are using `n prev`, if you want leave the original environment intact, you can use `n (io) use` to execute under a specific node/io.js version. That way you do not have to worry about cleanup at all.

**Comment by tedgaydos** [comment]
prev was pulled in 2.0.0.
