### ISSUE TITLE
"n use" style command for invoking npm

### ISSUE THREAD

**Issue by tjwebb** [tj/n#185]
`n use <version>` runs node as a particular version. I think it'd be useful to also be able to run npm in this manner as well. The CLI could then look something like:
1. install: `$ n <version>`
2. run node: `$ n <version> node` (or currently, `$ n use <version>`)
3. run npm: `$ n <version> npm`

**Comment by wprater** [comment]
this is a great idea for running scripts as a certain version.  progress

**Comment by bitdivine** [comment]
There is a sketch implementation of how this might work in https://github.com/tj/n/issues/192

Usage:

    n with <version> npm install

Code:

    https://github.com/bitdivine/n

This is not ready for merging into master but I find it useful to have a working implementation to play with to make sure that the feature implements all the goodies it promises.

**Comment by JohnRGee** [comment]
I suggest following same syntax as `nvs` and `nvm` which both have an `exec` command:

```
n exec <version> [command ...]
```

So running npm could look like:

```
n exec lts npm --version
```

**Comment by shadowspawn** [comment]
This is not likely to make it to `n` anytime soon. I have implemented this in [nvh](https://github.com/shadowspawn/nvh) if any readers would like to give it a try.

**Comment by shadowspawn** [comment]
Prerelease available via npm i n@next for v6. Release notes: https://github.com/tj/n/releases/tag/6.0.0-0

**Comment by shadowspawn** [comment]
Added `n exec` in v6: https://github.com/tj/n/releases/tag/v6.0.0
