### ISSUE TITLE
Escape variables to support spaces in paths

### ISSUE THREAD

**Issue by jbnicolai** [tj/n#187]
I think we all agree that spaces in paths are a _bad idea_ :smile:. I suggest we still make the script a bit more robust by handling them correctly though, and properly quote all dereferenced variables.

Would a PR for this be welcome?

**Comment by bitdivine** [comment]
With my security hat on I would say that shell variables should always, always, ALWAYS be quoted unless you are going out of your way to be pwned.  With my realistic one I reduce that to "almost always".  Would a pull request be welcome?

**Comment by JohnRGee** [comment]
On a related note, following the advice from`ShellCheck` (see #465) would likely address spaces in paths and more.

**Comment by shadowspawn** [comment]
Fixed in v4.0.0
