### ISSUE TITLE
Up / down arrow keys not working as expected

### ISSUE THREAD

**Issue by carloscarcamo** [tj/n#190]
Hello, I have installed n and I have installed 3 differents node.js versions:
0.10.29
0.11.12
0.11.13

The problem is when I try to switch between versions, 
$ n
   0.10.29
   0.11.12
o 0.11.13

according to documentation:  "Type n to prompt selection of an installed node. Use the up / down arrow to navigate, and press enter or the right arrow to select, or ^C to cancel:"

But up / down arrow keys not working for me, when I use the arrow keys the prompt returns to $ and I can't switch between versions.

What could be the problem? 

note: i'm using debian 7 amd64

**Comment by montogeek** [comment]
I have this problem using a Colemak keyboard, might it be the problem?
