### ISSUE TITLE
Optional Progress Bar

### ISSUE THREAD

**Issue by anoxic** [tj/n#205]
I am using Vagrant (vagrantup.com), using n to install a specific version of node inside a bootstrap script. But because of the way vagrant handles output of these scripts, the progress bar is caught and makes a very unsightly log display (see the screenshot below).

![image](https://cloud.githubusercontent.com/assets/1300459/5146858/a9434e62-7165-11e4-9978-66fdd885f055.png)

A flag to make the progress bar optional would be very helpful, however some other way of mitigating this would be fine as well. I tried to find a way to get around this, but in my search through the source I haven't been able to find where the progress bar is coming from.

**Comment by maxrimue** [comment]
^1.4.0 now has support for a quiet mode (`-q`/`--quiet`)
