### ISSUE TITLE
npm error after node-upgrade with n

### ISSUE THREAD

**Issue by fredrikw** [tj/n#206]
I just used n to install node v0.10.33 and npm stopped working. Every command but npm -v ends up in _Error: ENOENT, open '<currentDir>/null'_
As suggested in https://github.com/npm/npm/issues/5897 it was solved by running _curl https://www.npmjs.org/install.sh | sudo sh_
Also in this bug report it is suggested that it could be a problem with how n is upgrading npm, see https://github.com/npm/npm/issues/5897#issuecomment-57717022

**Comment by yyzych** [comment]
maybe you can try this:
1.  n 0.12.2  (install and switch old node. before solved this problem, my computer node version is 0.12.2, npm version is 2.7.4)
2.  npm update -g npm  (update npm)
3.  n 0.12.7

sorry, my english is poor...

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
