### ISSUE TITLE
Change n version

### ISSUE THREAD

**Issue by superboum** [tj/n#207]
If I type 

```
$ n
```

And choose a different version of nodejs I have a permission error.

Now, if I go root or sudo, there is no dot to choose the nodejs version and there is a grep error when I hit arrow keys of my keyboard. I didn't find any command line to change default n version without use this menu.

```
$ sudo n
# n
```

![capture d ecran de 2014-12-16 10 19 14](https://cloud.githubusercontent.com/assets/1770289/5451092/2449f0ec-850d-11e4-899c-dc99c54c0fec.png)

For information, I use Fedora 21 :

```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 21 (Twenty One)
Release:    21
Codename:   TwentyOne
```

Is there a solution to change default nodejs version, without this interactive menu or a solution to make it works ?

**Comment by dg192** [comment]
I was having this same problem, and it looks like it had to do with my path settings.  I had moved the global npm directory (https://docs.npmjs.com/getting-started/fixing-npm-permissions) and was setting my PATH like this...

    PATH =$PATH:~/npm-global/bin

But this is not correct.  It's actually the other way around.  Seems npm bin needs to take priority.

    PATH =~/npm-global/bin:$PATH

After doing that, I was able to select the node version with my keyboard.
