### ISSUE TITLE
should we include io.js support?

### ISSUE THREAD

**Issue by tjwebb** [tj/n#212]

**Comment by medimatrix** [comment]
If it is not too much work to add support for `io.js`, then yes, definitely.

**Comment by snostorm** [comment]
:+1: I think nvm and n supporting [io.js](https://github.com/iojs/io.js) could be very useful in helping the project (and users) bounce between the projects. Especially with talk of having an install option/default to stomp over the existing `node` command https://github.com/iojs/io.js/issues/43

**Comment by tjwebb** [comment]
Yea that's what I was thinking. Breaking down barriers between the two
projects in this way could benefit everyone.

**Comment by Fishrock123** [comment]
Please do.

For now, you can find io.js nightlies here: https://iojs.org/download/nightly/

**Comment by joeybloggs** [comment]
I would love a tool like n to provide support for io.js, it may be prudent however to fork or create another project, maybe called i ;) based off of n

That way if io.js ever diverges enough it will be easier to maintain separate codebases... And if they stay close then merges should be pretty painless.

**Comment by tjwebb** [comment]
That sort of diminishes the power of the feature though. It'd be
advantageous to support switching between the nodejs and iojs using a
single tool, right?

**Comment by joeybloggs** [comment]
I agree one tool will help with a transition from one to the other, however after io.is becomes stable switching from one to the other will probably be minimal.

My only concern was if io.js becomes different enough that switching from one to the other may not be possible..but perhaps this is a "cross that bridge when we come to it" sort of thing.

P.S. love your program, keep up the great work! Use it every day

**Comment by Fishrock123** [comment]
I have it on good word that `io.js` should not be radically different for the foreseeable future, except for the v8 version.

**Comment by mattpker** [comment]
+1

**Comment by yoshokatana** [comment]
I took a gander at the source, and I guess there are two options:

1. Update `n` to have a new feature "switch between node and iojs (and etc)" which would require a bunch of changes and new functionality.
2. Fork `n` and rejigger it for io.js, which would keep both tools as lean as they currently are.

Thoughts?

**Comment by greim** [comment]
There are a lot of node devs looking at io.js right now. The sooner someone gives them the ability to swtich between all the nodes and io.js's painlessly, the better a place the world will be. IMHO. I vote for io.js versions appearing in the list of things that `node` can become when you type `n`.

**Comment by getify** [comment]
especially since [`nvm` has said](https://github.com/creationix/nvm/issues/590) they will support io.js, it'd be really great if `n` could land support in roughly the same timeframe (aka "soon").

**Comment by ericelliott** [comment]
@getify :+1:

**Comment by ericelliott** [comment]
> I have it on good word that io.js should not be radically different for the foreseeable future, except for the v8 version.

Supporting ES6 natively is radically different, IMO.

**Comment by Ognian** [comment]
Yes, io.js support would be great, and today is the best time to do it, they just released v.1.0.1 ...

**Comment by mmarcon** [comment]
+1

**Comment by getify** [comment]
btw, can someone please edit the description to say "io.js" instead of "js.io"? :)

**Comment by tjwebb** [comment]
whoops, my bad. fixed

**Comment by tjwebb** [comment]
also, I'm pretty swamped atm; PR would be appreciated from anyone who is able to help out.

**Comment by joaquimserafim** [comment]
Hey guys,

How you are think about to do this? passing a new parameter? where the user chooses between io.js and node.js!

cheers

**Comment by boopathi** [comment]
Sent a pull request. Changed as minimal code as possible. This should work temporarily.

https://github.com/tj/n/pull/214

**Comment by jessy1092** [comment]
:+1:

**Comment by joaquimserafim** [comment]
:+1:

**Comment by appsforartists** [comment]
In the meantime, you can just decompress the `io` archive into `/usr/local/n/versions/1.0.1/` and use `n` to switch as you normally would.

**Comment by ericelliott** [comment]
> In the meantime, you can just decompress the io archive into /usr/local/n/versions/1.0.1/ and use n to switch as you normally would.

Nice.

**Comment by EvanCarroll** [comment]
It would seem to me that specifying `--io` is rather arbitrary. Why not `--distro io` as a mandated argument (opens the possibility to work with later forks, or even other binary distributions), and then issue warnings when the flag is lacking for the next release?

    n --distro node
    n --distro io

etc?

**Comment by snostorm** [comment]
In #215 would `--stable` point at anything right now? The stable/unstable convention for io.js doesn't match that of Node.js. Maybe those flags aren't applicable in this project.

Regarding a flag like `--distro` it would be nice to perhaps turn on a default distro. So `n 1.0.2` would go with my distro preference (re: future proofing future distro version conflicts.)

**Comment by EvanCarroll** [comment]
How does `--stable` and `--distro` not apply to io.js? [Version 0.10.35 was Stable.](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#summary-of-changes-from-nodejs-v01035-to-iojs-v100).

**Comment by yoshokatana** [comment]
I like the syntax of `--distro`, including the default behavior. :+1:

**Comment by snostorm** [comment]
@EvanCarroll io.js is moving to [Semver](http://semver.org/) instead of odd/even versions to indicate "stability" like in Node.js.

I'm not sure how `n` would differentiate if an io.js version is `--stable` vs `--current`.

The `--distro` would apply to io.js. My comment re: `--distro` was unrelated. Basically I was just stating that it would be nice to specify one default distro over another. (As, eventually, node.js and io.js versions may overlap.)

**Comment by rcsole** [comment]
@snostorm I agree it looks like `--stable` doesn't really make sense in that case.
It does, however, make sense for `node`. Maybe `--stable` in the case of `--io`
should just point to latest?

I do agree `--distro` looks like a good idea, but maybe we could have a config file
much like rbenv does. This config file would obviously be optional. Maybe this adds
more complexity which is not philosophy that `n` was looking for? Thoughts?

**Comment by EvanCarroll** [comment]
I still think you're making the wrong decision to drop `--stable` and `--current`. `stable` is the very word [`io.us` uses](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md). It would make more sense to parse the CHANGELOG.md at the root of the master branch if the distro is `io`. It also adds consistency with the node.js api.

**Comment by rcsole** [comment]
@EvanCarroll I don't see `io.js` using `stable`/`unstable`:

> The changelog below was inherited from joyent/node prior to the io.js fork.

The changelog post-fork is not using `stable` or `unstable`, just semver.

**Comment by slajax** [comment]
:+1: for distro flag.

**Comment by aheckmann** [comment]
+1 to a distro setting

**Comment by kentcdodds** [comment]
Would definitely love this to be supported. I really like the simplicity of `n`

**Comment by boopathi** [comment]
Have updated the code to support 

    n [command] #defaults to node
    n node [command]
    n io [command]

here - https://github.com/tj/n/pull/214

**Comment by glenjamin** [comment]
It looks like nvm is treating iojs as a prefix to its version argument.

This seems sensible to me, and is similar to I've seen it handled in Ruby version switching tools.

```
n use iojs-1.0
```

**Comment by jwarkentin** [comment]
However it's handled it would be nice if it also respected an environment variable if not specified in the command.

**Comment by aronwoost** [comment]
+1

**Comment by darrrk** [comment]
:+1:

**Comment by appsforartists** [comment]
If you aren't a contributor to **n** and you don't have anything to say beyond `+1` or :+1:, please don't both replying here.  You're spamming a whole lot of people with noise.

**Comment by tjwebb** [comment]
@appsforartist Please stay on topic. No one is interested in advice from the internets.

**Comment by AntouanK** [comment]
+1

**Comment by bitinn** [comment]
while I support this move, I am not sure what would happen to `npm`, see #210.

I upgraded to node 0.12 and npm is at 2.5.1, while for iojs, npm is at 2.4.1.

**Comment by glenjamin** [comment]
Now that npm is moving quite quickly, I wonder if tools like nvm and n should stop bundling it

**Comment by tjwebb** [comment]
npm is bundled with node itself. n/nvm don't really have a choice.

1.2.14 published with io.js support: https://www.npmjs.com/package/n

**Comment by qw3rtman** [comment]
Now that `io.js` has merged with Node, is it time to remove `io.js` as an option?

Made an issue for discussion: #331.
