### ISSUE TITLE
n is not modifying version of node

### ISSUE THREAD

**Issue by ezmiller** [tj/n#213]
I have node installed but when I run n in order to change my version on Node, it fails to do so. There's no error message or anything. It seems to run smoothly but when I check the node version, it remains the same. Thoughts?

**Comment by tjwebb** [comment]
Need actual details to help you: OS, node versions, n version, was it working before or did it just start recently, etc.

**Comment by ezmiller** [comment]
I think this was a problem with my installation. I started from scratch using brew to install node and things seem to be okay now.
