### ISSUE TITLE
Would it be possible to isolate global packages?

### ISSUE THREAD

**Issue by fl0w** [tj/n#217]
Not sure if this is of concern really. I've dealt with [virtualenv](https://virtualenv.pypa.io) previously and I loved setting up a specific environment with isolated global packages. Would this be of interest to n or is this out of scope? I'd imagine a feature like this would involve a number of breaking changes - a separate fork or even an entirely separate package.

My reasoning behind this feature/change is that with the introduction of io.js, it's of interest to me to have separate global versions installed of the same package depending on what environment I'm currently in.

I guess this ties in a bit into #212

**Comment by drschwabe** [comment]
Maybe whenever you ```npm install -g mymodule``` it can be installed to:  

```
n/versions/node/0.xx.x/node_modules/mymodule
```
(and similar pattern for iojs)

**Comment by adamreisnz** [comment]
This appears to be already the case

**Comment by JohnRGee** [comment]
No, global installs have not been separated by node version.

**Comment by adamreisnz** [comment]
Interestingly enough that's where my globally installed modules ended up in, see also https://github.com/tj/n/issues/546. I realise now this was not the intended behaviour.

**Comment by shadowspawn** [comment]
A reasonable question @fl0w . Isolating global packages would be a big change and unlikely to happen in `n`. If that is an important feature for you, I suggest you look at one of the other node version managers which support isolated global packages, such as `nvm`.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
