### ISSUE TITLE
Why does n install old version of npm

### ISSUE THREAD

**Issue by codepreneur** [tj/n#218]
For example `n stable` installs node 0.10.35 and npm 1.4.28 where as `n latest` installs node 0.11.14 and npm 2.0.0, both of them are old versions of npm and the latest one is 2.2.0.

Why cant n install node with compatible versions of npm ?

**Comment by gingermusketeer** [comment]
Npm is bundled with node. It depends which version of npm the node team decide to ship with each version of node. This is not something that n can determine.  You can update to the latest by running `npm install -g npm`

**Comment by nuisanceofcats** [comment]
The bundled versions of npm are basically useless for most node projects given the peer dependency changes.
