### ISSUE TITLE
n ls does not list iojs

### ISSUE THREAD

**Issue by Globegitter** [tj/n#222]
I am running on the latest master and general iojs support works beautifully. Minor glitch I found, `n ls` does not list iojs though.

**Comment by hanjianwei** [comment]
Use `n io ls`.

**Comment by jeffbski** [comment]
Ideally we should have a way to see both lists in one glance and know which one we are pointing to. `n ls` used to be that command. Now you have to go multiple places and `n io ls` doesn't indicate which versions are installed and which we are pointing to either.

**Comment by jeffbski** [comment]
`n ls` also used to list which version was active, but that doesn't seem to be the case anymore.

**Comment by ralphtheninja** [comment]
@Globegitter What @hanjianwei said. Use `n ls` for node versions and `n io ls` for iojs versions. The readme has been updated with more information.

@jeffbski `n ls` worked for node versions but not for `n io ls` as you reported yourself. It's fixed now though as I mentioned in your bug report :)

@Globegitter Close this issue?

**Comment by jeffbski** [comment]
@ralphtheninja your fix works. It is not deployed to npm yet, but if I install from github directly then I see the fix. Thanks.

**Comment by ralphtheninja** [comment]
@jeffbski Cool. I just have the code and do `npm link` in that.

**Comment by ralphtheninja** [comment]
Close?

**Comment by jeffbski** [comment]
Yes, everything is working as expected, Thanks!
