### ISSUE TITLE
n 1.2.13 has 1.2.9 bin

### ISSUE THREAD

**Issue by d5** [tj/n#224]
Just installed `1.2.13` but it contains `1.2.9` bin (`/bin/n`).

**Comment by winkerVSbecks** [comment]
same here. `1.2.14` is not available on npm yet

**Comment by elaijuh** [comment]
+1 tagging `1.2.14`

**Comment by justinjmoses** [comment]
+1.

**Comment by dominicbarnes** [comment]
+1 please fix this

**Comment by tjwebb** [comment]
I'll fix this tomorrow

**Comment by dominicbarnes** [comment]
@tjwebb how is the fix coming along for this? Would it be useful to have some extra collaborators around this project?

**Comment by tjwebb** [comment]
Should be updated: https://www.npmjs.com/package/n
