### ISSUE TITLE
`n io stable` will install `io-v1.2.0` instead of v1.3.0

### ISSUE THREAD

**Issue by fhemberger** [tj/n#230]
`n io stable` will install `io-v1.2.0` instead of v1.3.0, because io.js doesn't use Node's convention for stable/dev releases. `display_latest_stable_version` should behave differently for io.js (see https://github.com/tj/n/blob/master/bin/n#L471).

**Comment by tjwebb** [comment]
Ah I see that. We'll need to skip that odd/even check for io. On that note, io probably should just have a "latest" and not have a "stable" tag at all. Or something like that. Feedback is welcome.

**Comment by tedgaydos** [comment]
I think that would be a good idea. I might try this out. If someone where to try something like:

> n io stable

It would give an error message saying it is not supported for io. Or, should stable just go and pull latest instead to keep a similar workflow as it is today?

**Comment by ralphtheninja** [comment]
@tjwebb +1 for removing stable and just keeping latest
