### ISSUE TITLE
Error: no installed version

### ISSUE THREAD

**Issue by zwhitchcox** [tj/n#231]
I get the above error, but I am 100% sure I have node installed. I use it all the time.

**Comment by tjwebb** [comment]
Are you going to post the command you typed in? This error by itself is useless.

**Comment by dstroot** [comment]
I am seeing the same thing.  The command is "n"  ;)

```
❯ node -v
v0.12.0

~/.dotfiles master*
❯ n

  Error: no installed version
```

**Comment by dstroot** [comment]
I just `n 0.10.36` or `n latest` and that got me rolling again

**Comment by tjwebb** [comment]
So it is just with 0.12 series, maybe?

**Comment by zwhitchcox** [comment]
ah, that worked for me too

**Comment by dstroot** [comment]
>> So it is just with 0.12 series, maybe?

Could be - that is what I installed that killed n.
