### ISSUE TITLE
Installation of io.js failing on Raspberry Pi

### ISSUE THREAD

**Issue by maxrimue** [tj/n#232]
I installed the latest version of n via npm, but when I type `sudo n io stable` it just tries to install `io-v1.4.1` (current one) but fails right after beginning, resulting in this error:

     install : io-v1.4.1

     Error: invalid version 1.4.1

I know this issue from node, where it exits the same way with the same error when you try to install a node version that doesn't support ARMv6 in its dist, however, the dist of io.js v1.4.1 has a compatible package for ARMv6.

**Comment by tjwebb** [comment]
Hmm, `n` probably isn't aware that you're trying to install on a pi, and so is just giving you the regular x86 binaries. Some other issues have been filed about this, but I'm not the right person to implement this (I don't have a PI to test on, for starters).

Would anyone else be interested in taking on this project?

**Comment by maxrimue** [comment]
Maybe it has just problems with finding the right binary and just exits, if it used the x86 package I think it would have downloaded it first and would fail while installing, I'm not sure though.

**Comment by maxrimue** [comment]
Okay, I found and fixed the bug in my recent pull request #233.
