### ISSUE TITLE
Custom dist address

### ISSUE THREAD

**Issue by monkadd** [tj/n#237]
n downloads data from its official address.

```
MIRROR=(${NODE_MIRROR-https://nodejs.org/dist/}
        ${IO_MIRROR-https://iojs.org/dist/})
```

Is there a plan to support setting dist address to an mirror manually?

**Comment by maxrimue** [comment]
Could you explain what for? As the dists always have the most recent releases, I don't understand what the purpose of that would be.

**Comment by AdoHe** [comment]
@maxrimue I think maybe @monkadd is worried about the `https://nodejs.org/dist/` and `https://iojs.org/dist/` may get blocked, so sometimes a mirror maybe ok.

**Comment by tedgaydos** [comment]
I believe you can set the mirrors using the NODE_MIRROR and IO_MIRROR when running n to set a custom path.

**Comment by AdoHe** [comment]
@tedgaydos yeah, exactly.
