### ISSUE TITLE
Problem when change user

### ISSUE THREAD

**Issue by fernandoneto** [tj/n#243]
First of all thank you for this great job.

Im facing a problem configuring `n` with 2 users and hope you can help me.
Im running n in ubuntu 14.04 with 2 user's. i install n with command `npm install -g n` and everything work fine in this user. im able to install node versions and switch between them with no problem. 
The problem start when i change to second user. This user have no sudo rights so i change the prefix to 
`N_PREFIX=$HOME/n` to install new versions without using sudo. 

Then imagine i want to install and use node v0.11.15 i use the command `n 0.11.15` the download start but the version won't change.

![node](https://cloud.githubusercontent.com/assets/6515784/6668638/236de996-cbec-11e4-8c1d-b1be28855c0b.png)

But if i launch the process with `n use 0.11.15 test.js`, the porcess will run with the exact version i defined. 
![node 2](https://cloud.githubusercontent.com/assets/6515784/6668735/ade4b8a2-cbec-11e4-8c0e-cc41b11056d7.png)

There's some way to define node version for user's without using `n use` ?

**Comment by AdoHe** [comment]
@fernandoneto I think first you should use `n` to list the installed node versions, also this will indicate which version is active, if you want to change the node version, just use the up&down arrow key to choose the version ,and the use the `<Enter>` key to make sure.

**Comment by AdoHe** [comment]
@fernandoneto also I think the first picture you post here is not correct.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
