### ISSUE TITLE
`n io ls` doesn't indicate which versions are installed and active

### ISSUE THREAD

**Issue by jeffbski** [tj/n#245]
`n io ls` doesn't indicate which versions are installed, they are all grayed out even if they are installed.

Also it doesn't indicate which version is active like `n ls` used to (it appears that it no longer works either).

The reason it is important to indicate which versions are installed with `n io ls` is so one can cleanup old versions and not waste space forever. Also is handy if you want to switch to an already built version and don't know which ones you have previously installed.

**Comment by AdoHe** [comment]
@jeffbski please use `n` to indicate which version was active, and `n ls` will indicate which versions are installed

**Comment by jeffbski** [comment]
@AdoHe `n ls` doesn't display the iojs versions that are installed. So neither `n ls` nor `n io ls` displays the iojs versions that are installed.

**Comment by ralphtheninja** [comment]
Yes they are! ;) https://github.com/tj/n/pull/242

**Comment by jeffbski** [comment]
@ralphtheninja yes, you are correct, your change does fix this. Thanks. **Could we get this deployed to npm** since the only way to get the fix is to install from github currently (which I did and it works).

**Comment by tjwebb** [comment]
I just published 1.3.0

**Comment by jeffbski** [comment]
Thanks @tjwebb works great!

**Comment by ralphtheninja** [comment]
`n` is an unpolished diamond :)
