### ISSUE TITLE
Typo in bash code

### ISSUE THREAD

**Issue by thedark1337** [tj/n#246]
I was viewing the commits and noticed this line: https://github.com/tj/n/blob/master/bin/n#L344 says iclude and not include, is that intentional or a typo?

**Comment by maxrimue** [comment]
Yep, seems like a typo from my recent PR. That's a bit embarrassing.

**Comment by tedgaydos** [comment]
Shouldn't the cp copy go to $N_PREFIX also? I just put in a pull request #248 so the files get copied. Maybe there was no error because cp has no destination?

**Comment by maxrimue** [comment]
@tedgaydos I'm not sure, I looked into the folders where the versions get installed, and the `include` folders always were there, so I assume cp takes the last destination again. This snippet of code wasn't mine anyway, @ralphtheninja was this intended or is it a typo?

**Comment by ralphtheninja** [comment]
@maxrimue I don't know :) The fix is in this commit https://github.com/tj/n/commit/d5eb3695feaf3869e8834d7438b76eb3686f2391 as part of this PR https://github.com/tj/n/pull/235

**Comment by ralphtheninja** [comment]
@tedgaydos Oh right. Of course the copy operation should go to `$N_PREFIX` as well.

We should get some tests up and running for `n`

**Comment by maxrimue** [comment]
@ralphtheninja Well it was your suggestion to use this code, so I thought you'd know :D 
Doesn't matter anyway now, #248 will fix it so or so.

**Comment by tedgaydos** [comment]
@maxrimue What you see is probably because you had a version over 0.10.24 installed previously. I removed everything from my $N_PREFIX path and activated 0.10.23. There was no include folder copied. Then when I switched to 0.12.0, the include folder was not copied.

@ralphtheninja I can help in getting some tests going for this.

**Comment by ralphtheninja** [comment]
@maxrimue Aye, you're right. I messed up on that one :)

**Comment by maxrimue** [comment]
@ralphtheninja It's alright, I didn't see it either

**Comment by maxrimue** [comment]
@thedark1337 Since the PR #248 solving this issue has just been merged, please close this issue if everything is solved to you now, thanks
