### ISSUE TITLE
io.js not installing

### ISSUE THREAD

**Issue by chrisabrams** [tj/n#250]
When I run:

    n io stable

I get:

    cp: /usr/local/n/versions/io/bin: No such file or directory
    cp: /usr/local/n/versions/io/lib: No such file or directory
    cp: /usr/local/n/versions/io/include: No such file or directory
    cp: /usr/local/n/versions/io/share: No such file or directory

What do I need to do?

**Comment by maxrimue** [comment]
It seems like n is trying to install io.js in the wrong path, normally it would be `/usr/local/n/versions/io/<version>/`. I can't reproduce that error, I uninstalled everything completely and it works. Are you maybe running an old version of n?

**Comment by chrisabrams** [comment]
I'm on `1.3.0`

**Comment by chrisabrams** [comment]
Hmm uninstalling `n` and reinstalling seems to have worked.

**Comment by DJXia** [comment]
Hello,
I think you need to add "sudo" to launch the command:
`sudo n io stable`
