### ISSUE TITLE
package.json Version Configuration

### ISSUE THREAD

**Issue by joezimjs** [tj/n#251]
It would be amazing if we could extend `package.json` with some configuration of which version of Node and which version of NPM is used for that project and n would use that configuration to determine which versions it uses. Also add a `--save` flag when loading a version so that n can handle adding the configuration.

I'm not sure how this would be handled, whether the Node and NPM files would be stored in the project locally or installed globally, but I'm sure you can figure it out. If you install locally, the feature from #185 would work well for invoking Node and NPM, similar to the way you can [use `npm run` to invoke locally installed modules that have binaries](http://www.joezimjs.com/javascript/no-more-global-npm-packages/).

**Comment by maxrimue** [comment]
So you mean that, if you for example have a Node.js project saying in its package.json that it requires for example version 0.12.0, that you can then run something like `n run` and n will read the package.json, see which version to use, and then run the project with that specific version?

**Comment by joezimjs** [comment]
I was thinking that the `package.json` would specify version of Node (0.12.0 for example) and NPM (0.2.6 for example) and instead of using `n <version> node`, you could use `n node` and it would use Node v0.12.0 and you could use `n npm` and it would run NPM v0.2.6. I was comparing it to `npm run` simply as an example for how it can use local packages as though it was installed globally, so you can store the Node and NPM versions locally instead of in the machine's PATH.

**Comment by maxrimue** [comment]
@joezimjs What would be the benefits by running different npm versions? Since Node/io.js comes bundled with npm and certain versions aren't compatible with each other, would it be acceptable to only include `n node`? Also, since n already offers the possibility to "store" multiple node and io.js versions, why store the binaries in the project folder?

**Comment by joezimjs** [comment]
NPM versions aren't important since they are generally connected to different versions of Node, so you can skip that I guess. 

Also, I'm not saying you have to store Node in the project folder, but I'm just stating it as an option, since the idea seems similar to the way you can do that with NPM and cli packages.

Another idea would be that you can use the [`engines.node`](https://docs.npmjs.com/files/package.json#engines) property in `package.json` as the specifier for the version of Node to use.

**Comment by maxrimue** [comment]
@joezimjs Yes, I thought of that property already. #253 would require a JSON parser module too, so we can use that module for both ideas.

**Comment by tedgaydos** [comment]
I think this might be similar to #192 ?

Also, would this not be fulfilled with the [n-api](https://github.com/tjwebb/n-api) ?

**Comment by joezimjs** [comment]
Definitely similar to #192. I missed that one. Feel free to close this one down.

**Comment by tedgaydos** [comment]
@joezimjs You can close the issue if you feel it is answered. Thanks.
