### ISSUE TITLE
External repository support for precompiled Node.js binaries

### ISSUE THREAD

**Issue by X4** [tj/n#253]
I think adding support for external sources would be an awesome addition. 
Maybe starting with a `repository.json` file containing links to external repositories would help the community to start self-organizing build-servers, binaries and links to external repositories. Having an SHA1 hash to the json file would ensure that nobody compromises the binaries after a successful build.

**Comment by maxrimue** [comment]
@X4 Would this list be in an external repo or inside this one? I think it would be best if we seperated the repos and just added the possibility to download binaries from any external link, so we can contribute seperately and so on. Also, I don't think it's possible for bash to parse JSON data without any other dependency, so this would probably require too much code. Thoughts?

**Comment by X4** [comment]
Jup seperating the repository from n would keep 'n clean.

Here are links to Bash JSON Parsers: 
- https://github.com/dominictarr/JSON.sh
- https://github.com/ingydotnet/json-bash

**Comment by tedgaydos** [comment]
You can set the repo paths when running n setting NODE_MIRROR and IO_MIRROR. Here is the check  in the [n script](http://www.github.com/tj/n/blob/67173e8cc6d202fdd6b33e558691e3cc5d2aa9b9/bin/n#L19-20).
