### ISSUE TITLE
I can't install n because I have win32

### ISSUE THREAD

**Issue by Tim15** [tj/n#254]
Why isn't win32 supported?
Is there a way that I can install n?

**Comment by tedgaydos** [comment]
n is a 'nix shell script. It is a known limitation #151 at this time.

**Comment by tjwebb** [comment]
Some other folks have mentioned this but no one's submitted a PR for a `.bat` script yet. I'd be happy to except I haven't used Windows since 2007

**Comment by Tim15** [comment]
Thanks! I was just curious to know.
