### ISSUE TITLE
iojs alias does nothing

### ISSUE THREAD

**Issue by tedgaydos** [tj/n#255]
I have noticed that the iojs alias is broke. It does not correctly refer to io references in the script. If I try to run, for example, n iojs latest. It will go and install the latest version of node. The reason is the test in set_default() can never match iojs because the only values stored in BINS is node and io.

I could fix it or remove the alias. I know @tjwebb was looking to keep the script simple and limit aliases. I vote to remove the alias.

**Comment by maxrimue** [comment]
Yep, I think removing both `latest` and `stable` would make sense for io.js, does io.js even have any unstable builds (except nightly builds) like Node.js did with for example v0.11.0?

**Comment by tedgaydos** [comment]
I made a comment about latest and stable in #230 and think leaving latest would still work. What is your opinion?

**Comment by maxrimue** [comment]
@tedgaydos either so or just make `n io` install the latest io.js version, that'd be even simpler and would also make sense, since usually when you install something, you expect to get the latest version.
