### ISSUE TITLE
Honor npm in the path

### ISSUE THREAD

**Issue by knownasilya** [tj/n#258]
This doesn't work `n use 0.12.0 npm start`, because it returns an error: 

``` no-highlight
Error: Cannot find module '/Users/me/path/to/project/npm'
```

A workaround is this: `n use 0.12.0 `which npm` start`.

**Comment by bitdivine** [comment]
This seems to be still an issue.  My solution to https://github.com/tj/n/issues/192 solves this but still needs to be sanity checked and probably needs refinement.  Comments and constructive criticism are welcome.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
