### ISSUE TITLE
n <ver> returns exit 1 

### ISSUE THREAD

**Issue by edanderews** [tj/n#259]
Hi,

I have chef recipes that run "n [version]" example: "n 0.10.38", ever since upgrade to 1.3.0 these are failing with no output:
## Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '1'
---- Begin output of n 0.10.38 ----
STDOUT: 
STDERR: 
---- End output of n 0.10.38 ----
Ran n 0.10.38 returned 1

Please advise

**Comment by tjwebb** [comment]
What is your operating system

**Comment by edanderews** [comment]
ubuntu 14.04

**Comment by stefankutko** [comment]
Same thing... Mac OS X Yosemite 10.10.3

**Comment by maxrimue** [comment]
Is this problem still occurring?

**Comment by edanderews** [comment]
Yes as far as I'm aware

**Comment by maxrimue** [comment]
Weird... I can't reproduce the problem. Maybe you need to reinstall n, try to clone this repository and do  `sudo make install` and then `sudo n 0.10.38` again

**Comment by hgenru** [comment]
+1 same problem on ubuntu 14.04

**Comment by reyhansofian** [comment]
+1 and still happening on my Ubuntu 14.04

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
