### ISSUE TITLE
n doesn't work on intel edison (3.10.17-poky-edison)

### ISSUE THREAD

**Issue by xa4** [tj/n#260]
it can't find bash. After installing bash it fails because of a tar arg that is not recognised (--strip)..

**Comment by tjwebb** [comment]
Yea, this is a shell script so you need bash for it to run. 

> fails because of a tar arg that is not recognised

I don't know what this means. Can you post the error message?

**Comment by xa4** [comment]
This is what I get now:
```
# n stable
cp: can't stat '/usr/local/n/versions/node/0.12.2/bin': No such file or directory
cp: can't stat '/usr/local/n/versions/node/0.12.2/lib': No such file or directory
cp: can't stat '/usr/local/n/versions/node/0.12.2/share': No such file or directory
```

But I remember the first that I ran the command, it would extract the content of the downloaded tar file because of an error in the tar argument (--strip was not recognized)

**Comment by tedgaydos** [comment]
Looks like --strip is not a GNU tar flag. The GNU flag is --strip-components. I will submit a PR with the change.

**Comment by maxrimue** [comment]
@xa4 Try out 1.4.0 or 2.0.0, does it work now?

**Comment by VeepC** [comment]
# n stable
cp: can't stat '/usr/local/n/versions/node/0.12.2/bin': No such file or directory
cp: can't stat '/usr/local/n/versions/node/0.12.2/lib': No such file or directory
cp: can't stat '/usr/local/n/versions/node/0.12.2/share': No such file or directory

=============================================================

I hava the same problem~

**Comment by maxrimue** [comment]
@VeepC Are you also using an Intel Edison, or is the error just similar?

**Comment by VeepC** [comment]
@maxrimue Yeah, it is similar! I'm sorry that.  my error is: 
cp: /usr/local/n/versions/node//bin: No such file or directory
cp: /usr/local/n/versions/node//lib: No such file or directory
cp: /usr/local/n/versions/node//share: No such file or directory

**Comment by maxrimue** [comment]
@VeepC Sorry, I was asking if you use the same device.

**Comment by VeepC** [comment]
@maxrimue sorry, I go to the apple site, but couldn't know which device it is. I know my mac is  MacBook Pro (Retina, 13-inch, Mid 2014) - Technical Specifications  .You can see this: https://support.apple.com/kb/SP703?locale=zh_CN&viewlocale=en_US

**Comment by maxrimue** [comment]
@VeepC Your problem isn't related to this one then. This issue was caused by the device with its platform, namely the Intel Edison, your problem is different though. Could you open up another issue?

**Comment by xa4** [comment]
Hello @tedgaydos @maxrimue, thanks for checking this out. I don't have access to the edison now as I'm on holidays but I will try it next week and let you know.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
