### ISSUE TITLE
change the version by n, but do not effect. i use "which node", the result is "/usr/bin/node"

### ISSUE THREAD

**Issue by chelsh** [tj/n#261]
![image](https://cloud.githubusercontent.com/assets/10752360/7384699/c8546854-ee6a-11e4-9725-2890100c7a08.png)

![image](https://cloud.githubusercontent.com/assets/10752360/7384685/8fd3be1c-ee6a-11e4-8c9a-149133107454.png)

**Comment by tjwebb** [comment]
> i use "which node", the result is "/usr/bin/node"

Did you previously install node through `apt-get`?

**Comment by melxx001** [comment]
I have the same issue and I did install node using apt-get

**Comment by melxx001** [comment]
nvm... I opened another terminal and the node version updated :)

**Comment by tjwebb** [comment]
>  I did install previously node using apt-get

You need to `apt-get remove` all node versions installed through apt-get before using `n` or things will be very confusing.

**Comment by maxrimue** [comment]
@chelsh Has your problem been solved by removing any Node.js versions installed outside n?

**Comment by bigdx** [comment]
@ tywebb
How can is that possible if npm/node is required for n? Or how do you mean that?

Btw. I'm using CentOS, so maybe its different here ...

**Comment by maxrimue** [comment]
@bigdx Node.js/NPM is **not** required for using n, you can also just clone this repo and install n this way:
```
git clone https://github.com/tj/n
cd n
sudo make install
```
Have you installed Node.js outside n somehow?

**Comment by bigdx** [comment]
@maxrimue 
Yes, npm and node.js are installed from the epel-repo ... to be able to install n ("npm install -g n") to be able to install node.js (in the latest stable version) ^^

**Comment by maxrimue** [comment]
@bigdx Well okay, I'd recommend to just remove all Node.js installations you have on your system, install n the git-way, and then install Node.js via n

**Comment by franciscop** [comment]
@melxx001 same thing happened to me, opened another terminal and "problem" solved

**Comment by franciscop** [comment]
Please note that I had to do this after updating to the latest version:
- http://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register

**Comment by maxrimue** [comment]
I'll close this now, as the problem seems to be solved
