### ISSUE TITLE
Add ability to install a version without activating it

### ISSUE THREAD

**Issue by glenjamin** [tj/n#262]
This would be quite useful in automated scenarios where I'd want to install many versions and not have any default.

Applications would then be able to opt-in using `n use <app>`.

**Comment by maxrimue** [comment]
So you mean just a "download only" option? In this case, I think just another if in the code would do it

**Comment by glenjamin** [comment]
Yep, exactly that.

**Comment by maxrimue** [comment]
I made a PR for that #265

**Comment by maxrimue** [comment]
We'll get the PR merged as soon as we're ready for a new release
