### ISSUE TITLE
option to set NODE_HOME

### ISSUE THREAD

**Issue by amir-arad** [tj/n#275]
it would be nice top be able to set a system variable that points at the current version of node

i.e NODE_HOME

**Comment by tedgaydos** [comment]
What is the use case you are trying to achieve? With `n`, I call `which node` and it points to the version activated by `n`.

**Comment by amir-arad** [comment]
some frameworks may demand an environment variable to point to the node
folder.

**Comment by maxrimue** [comment]
@amir-arad I think you could solve that problem with `path_to_node=$(which node)` just fine
