### ISSUE TITLE
Version 1.4, 2.0 and PRs pre-2015

### ISSUE THREAD

**Issue by tedgaydos** [tj/n#276]
I wanted to ask everyone what we should do with the pending PRs and how to handle version 2.0.

I figure we can roll up issues #273 #272 #269 #268 #267 #265 and publish as a version 1.4 because it adds two new features (quite mode and download only) and has some bug fixes.

For version 2.0, maybe we should initially branch it and roll in issues #271. Then merge it back into master when it's time to publish? Or branch off the 1.x version for bug fixes and master moves to 2.0?

Finally, what should we do with older PRs? Some look good but were never reviewed or merge. Their merge status is now incompatible.

**Comment by maxrimue** [comment]
This seems like a good idea, +1 for branching off the 1.x.x version for further fixes.
To the older PRs: We should look at them and then discuss them and just ask for fixing them.

**Comment by maxrimue** [comment]
I just noticed all those old, still opened issues as well. What about them? I just closed one because it was solved, but there are still 40, some of them from 2013, should we just close them or resume taking care of each? I think that some problems they address have already been solved.

**Comment by maxrimue** [comment]
I think we should merge all PRs leading to 1.4.0 soon as going to 1.4 is, as I think, nothing we have to discuss, and it seems like there are some people really waiting for these changes.
Once we went to 1.4.0, we can wait until we really discussed and decided how we want to get 2.x.x done.

**Comment by tedgaydos** [comment]
I'd like to get one more person to okay this like @tjwebb before pushing it out to npm.

**Comment by maxrimue** [comment]
@tedgaydos We should add #279 to 1.4 too

**Comment by maxrimue** [comment]
I suggest we get 1.4.0 and 2.0.0 ready this week, as I won't be available the weeks after this one. I've seen that you're not registered at npm, if you do so, I will add you to n there.

**Comment by tedgaydos** [comment]
I will get setup on npm and we will get it out. :+1:

**Comment by maxrimue** [comment]
Okay, so as a summary, for 1.4.0:
- #282 
- #281 
- #279 
- #273 
- #272 
- #268 
- #267 
- #265 

Is that all?
