### ISSUE TITLE
n fails to install anything

### ISSUE THREAD

**Issue by Ognian** [tj/n#284]
OS X 10.9
installed latest n 1.3.0 -> ```sudo npm install -g n```

```
sudo n node latest
cp: /usr/local/n/versions/node//bin: No such file or directory
cp: /usr/local/n/versions/node//lib: No such file or directory
cp: /usr/local/n/versions/node//share: No such file or directory
````
````
sudo n io latest
cp: /usr/local/n/versions/io//bin: No such file or directory
cp: /usr/local/n/versions/io//lib: No such file or directory
cp: /usr/local/n/versions/io//share: No such file or directory
```

notice the ```//``` before bin, lib, share
was using n 1.2.1 before without any problems
please help

**Comment by Ognian** [comment]
see #250 
but uninstall install doesn't work for me...
``` n ls ``` doesn't show up anything ...
maybe this is a hint?

**Comment by maxrimue** [comment]
Does `n io ls` show anything?

**Comment by Ognian** [comment]
no

**Comment by Ognian** [comment]
OK, did some debugging:

the curl command issued by n and the reason for the empty list is: 

```
curl -# -L https://iojs.org/dist/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

```

**Comment by maxrimue** [comment]
That's weird, curl has no problem with iojs.org's certificate on my machine, the npm version of n also works just fine

**Comment by Ognian** [comment]
indeed, in safari the certificate of node and iojs are shown as trusted but curl don't think so...

**Comment by Ognian** [comment]
OK, found it:
path contains another curl, not the OS X default one ...
let's see if everything works now...

**Comment by haozxuan** [comment]
I have this problem too,can resolve?

**Comment by Ognian** [comment]
Yes. everything works now...
So the only problem I see is that n doesn't show me the error from curl which would help in finding out the correct cause.

@haozxuan:
look with ```which curl``` at what curl is used and change your path to the correct one...

**Comment by tedgaydos** [comment]
We can look into adding the flag to not check certificates. `n` uses `wget` by default if `curl` is not installed and uses a flag to ignore certificate warnings. That should help with this issue in the future.

**Comment by Ognian** [comment]
disagree, not checking certificates in these days is not an option for me ;-)
In my opinion a clear error message would be enough to find the cause (in my case it was anaconda the python versioning tool which brings his own curl version ....)

**Comment by maxrimue** [comment]
We could do both, implement a flag and make n show curl and wget errors, that way, you can still solve curl and wget certificate problems without having to use the flag, but you still could use the flag if you really need to, making it really an optional thing. However, I'll close this now, as the original problem is solved.

**Comment by hkkhchan** [comment]
My solution is to remove the folder.
/usr/local/n/versions/node/<your version>/
and then install again.
