### ISSUE TITLE
Suggestion: support installing n directly from GitHub, without needing to install Node.js / npm first

### ISSUE THREAD

**Issue by mklement0** [tj/n#286]
I've created a separate project, [/mklement0/n-install](/mklement0/n-install), to support this, but it would make sense to have n support this directly.
Shorter-term, if you think it makes sense and deem it robust enough, it could be linked to from n's read-me.

The only additional prerequisite, beyond what n itself needs, is `git`.

Aside from installing n directly from GitHub, it also installs helper scripts for updating n (`n-update`) and uninstalling (`n-uninstall`).

For `bash`, `ksh`, `zsh`, it modifies the relevant shell-initialization file to define env. variable `N_PREFIX` and appends `$N_PREFIX/bin` to the `$PATH` variable; for other shells, this must be done manually.
(Note that the need to modify shell-initialization files could be obviated if `n` supported reading the `N_PREFIX` value from, say, `~/.nrc`, and the n installation procedure created that file and placed a _symlink_ to `n` into a _preexisting_ `$PATH` directory, such as `~/bin`.)

Here are working examples; see [/mklement0/n-install](/mklement0/n-install) for details:

* Installation with confirmation prompt to confirm installing to default location `$HOME/n` and installing the latest stable Node.js version:

```shell
curl -L http://git.io/n-install | bash
```

* Automated installation to the default location, with subsequent installation of the latest stable Node.js and io.js versions, as well as the latest 0.10.x Node.js version:

```shell
curl -L http://git.io/n-install | bash -s -- -y stable io:stable 0.10
```

* Automated installation of just n itself to the default location, _without_ subsequent installation of the latest stable Node.js version:

```shell
curl -L http://git.io/n-install | bash -s -- -y -
```

* Automated installation to custom location `~/util/n`, with subsequent installation of the latest stable Node.js version:

```shell
curl -L http://git.io/n-install | N_PREFIX=~/util/n bash -s -- -y
```

**Comment by maxrimue** [comment]
To tell you my personal opinion, I find the idea great, when you for example want to deploy a Node.js app and want to "hide" the Node.js installation for simplifying the installation process and so on.
However, I think this is going beyond what n was originally thought for. We want to keep n as minimalistic as possible, and the necessary code to establish the named features seems like a not-so-tiny amount. We could definitely discuss adding a link to the readme to your project, but I think other collaborators will have about the same opinion. So to make it clear: I like the idea, but I think it wouldn't fit into this repo.

**Comment by mklement0** [comment]
@maxrimue Thanks for the thoughtful feedback. 

I do understand the desire to remain minimalistic (and kudos for having succeeded impressively).
(My project is already larger than n itself)

A link in the read-me would be great, however; please let me know if you need anything from me to make this happen. I'm happy to propose something in a PR.

**Comment by maxrimue** [comment]
I was thinking about something like:
>If you need features like automatic installation of n without requiring npm and followed by making n install a specific Node.js/io.js version, plus upgrading or removing n again, you might want to check out [n-install](https://github.com/mklement0/n-install).

@mklement0 opinion?

I would also like to get some opinions from other collaborators on this subject.

**Comment by mklement0** [comment]
@maxrimue 

Sounds great, thanks (except that I'd replace the 'and' before 'followed' with a comma). 

P.S.: I also suggest revising the current instructions for _manual_ installation, which are virtually incomprehensible at the moment.

**Comment by tedgaydos** [comment]
It is a neat project and good luck with it. But, it is out of scope for what `n` does. I am on the fence about adding this to the readme file. If we add this project, which others should we add? I can think of `n-api` off the top of my head.

Putting more detail for `N_PREFIX` and a manual install section in the readme would make sense. To do a manual install is only a few lines for most Linux distros. 

```shell
(On Ubuntu/Linux Mint)

~ $ git clone git@github.com:tj/n.git
(enter password)
~ $ cd n && make install
~ $ echo "N_PREFIX=$HOME" >> ~/.bashrc && . ~/.bashrc
~ $ n stable && . ~/.profile
```

There are added calls to refresh the shell to make sure `N_PREFIX` and `~/bin` are loaded. But, that's common when adding to the environment.
 
And to update `n` is just a `git pull` with another call to `make install`.

**Comment by mklement0** [comment]
@tedgaydos Thanks.

Adding details re `N_PREFIX` and your manual-installation steps to the read-me  is a great idea - sorely missing at the moment.
(As an aside: it would make sense to switch `Makefile` from `PREFIX` to `N_PREFIX` for consistency.)

In essence, your steps are what `n-install` does, PLUS:

* it does it all with a **single command** (compare your steps to `curl -L http://git.io/n-install | bash` and think about performing your steps over and over).
* for **multiple shells**: Bash, Ksh, and Zsh - with instructions given for other shells
* for **multiple platforms**: Linux and OSX (where `~/.bash_profile` rather than `~/.bashrc` must be modified)

In addition:
* You get an **easy-to-remember script in the path (`n-update`) for updating**, rather than having to remember the internals of `n`.
* You get **simple UNinstallation with `n-uninstall`**, based on sequestering `n` and all the Node.js versions it manages in a dedicated directory; manual uninstallation, especially if installed to `$HOME`, would be quite cumbersome and potentially dangerous (accidental removal of unrelated files).

I'll address the question whether to put a link in the read-me in a separate comment.

**Comment by mklement0** [comment]
@tedgaydos 

>  If we add this project, which others should we add?

If that is a concern, you could - as other projects have done - create a dedicated Wiki page listing all (noteworthy) related projects, and mention it (with a link) in the read-me.

**Comment by maxrimue** [comment]
+1 for using the wiki, it's enabled here and just left empty, we could put some more documentation in there

**Comment by maxrimue** [comment]
@tedgaydos What's your opinion on using the wiki? If we decide to not use the wiki, I'd like to ask you @mklement0 to create a pull request for the readme including a short description of your project and a link

**Comment by mklement0** [comment]
I appreciate the follow-up, @maxrimue. 

Whatever form you decide on, let me make the case for it once more: I (not so humbly) think `curl -L http://git.io/n-install | bash` is by far the simplest way to get set up with _both_ `n` and Node.js, and I think many people would benefit from that.

**Comment by maxrimue** [comment]
@mklement0 Could you create a pull request? I'll merge it into both branches once it's finished.

**Comment by mklement0** [comment]
Thanks, @maxrimue - see the PR. 

I've also streamlined the existing installation instructions a little.

Let me know if this works for you.

**Comment by maxrimue** [comment]
I'll close this now as the PR got merged
