### ISSUE TITLE
Wont install any versions

### ISSUE THREAD

**Issue by codan84** [tj/n#288]
Just installed n 1.3.0 from npm package on CentOS, no matter which version of node I am trying to install, I get `Error: invalid version x.x.x` (tried 0.12.2, 0.8.14 and few more)

**Comment by maxrimue** [comment]
What output do you get when running `n ls`?

**Comment by codan84** [comment]
empty, just few empty lines.
When running `n stable` I get:

    cp: cannot stat `/usr/local/n/versions/node//bin': No such file or directory
    cp: cannot stat `/usr/local/n/versions/node//lib': No such file or directory
    cp: cannot stat `/usr/local/n/versions/node//share': No such file or directory

And indeed `/usr/local/n/versions/node/` is empty...

**Comment by maxrimue** [comment]
`/usr/local/n/versions/node/` is where the Node.js versions will get installed, so if you haven't installed any through n yet, it's absolutely fine that this directory is empty. The problem rather is that cp tries to copy the folders to incorrect paths, there is only one slash after `node` supposed to be there. I think this already once occurred in another issue, but I'm not yet sure why it fails

**Comment by codan84** [comment]
Ok I have tried usinf nvm and had similar issue, every version of node would be "incorrect". Went there to browse for issues and found that: https://github.com/creationix/nvm/issues/769
As suggested I did run:

    nvm_download -L -s $NVM_NODEJS_ORG_MIRROR/ --verbose -o -

And indeed turns out my certs were bad:

    SSLv3, TLS handshake, Server hello (2):
    SSLv3, TLS handshake, CERT (11):
    SSLv3, TLS alert, Server hello (2):
    SSL certificate problem, verify that the CA cert is OK. Details:
    error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Running `yum update openssl -y` did fix the problem and now I can use n or nvm :)

**Comment by maxrimue** [comment]
@codan84 That's good to hear, I was just about to search the whole script :D

**Comment by sbryfcz** [comment]
For anyone else looking into this on Mac, I installed/updated openssl using brew and this worked. http://apple.stackexchange.com/questions/126830/how-to-upgrade-openssl-in-os-x
