### ISSUE TITLE
"n stable" fails with invalid version

### ISSUE THREAD

**Issue by coladict** [tj/n#289]
I tried it several times, but kept getting the following error:

         install : node-v261:0.6.9

      Error: invalid version 261:0.6.9

Eventually I figured-out the problem is that I have an environment variable GREP_OPTIONS that adds "--line-number" to the grep command line. You should put an `unset GREP_OPTIONS` somewhere in the script, so that it will just use the defaults.

**Comment by maxrimue** [comment]
You shouldn't use `GREP_OPTIONS` as pointed out in [the manual of grep](http://www.gnu.org/software/grep/manual/grep.html#Environment-Variables):
>GREP_OPTIONS
This variable specifies default options to be placed in front of any explicit options. As this causes problems when writing portable scripts, this feature will be removed in a future release of grep, and grep warns if it is used. Please use an alias or script instead.
