### ISSUE TITLE
Unable to switch versions of Node.

### ISSUE THREAD

**Issue by hzhu** [tj/n#290]
I'm trying to switch Node versions on my system like the gify demo: [https://github.com/tj/n#user-content-n](https://github.com/tj/n#user-content-n)
But when I hit `enter` on a selected version, and type `node --version` the version didn't change. Can anyone help?...

![node3](https://cloud.githubusercontent.com/assets/1811365/8514936/0da2deaa-234e-11e5-99fd-e8a13ab2f467.gif)

**Comment by maxrimue** [comment]
My guess is that the account you use doesn't have write permissions for `/usr/local/n`, what happens if you instead use `sudo n` and then change the version?

**Comment by Hesesses** [comment]
+1

**Comment by hzhu** [comment]
hi @maxrimue , I still get the same problem. The version doesn't change. 
![node44](https://cloud.githubusercontent.com/assets/1811365/8662660/f142e2bc-2976-11e5-853f-088b51824db8.gif)

**Comment by maxrimue** [comment]
Have you changed the N_PREFIX so n downloads Node.js somewhere else than
/usr/bin/? Or have you installed Node.js with another package manager like
homebrew?
Henry Zhu <notifications@github.com> schrieb am Di., 14. Juli 2015 um 00:51:

**Comment by troy0820** [comment]
If you used nvm, they go into ~/.nvm folder and this may be the reason your switch isn't working as well.

**Comment by hzhu** [comment]
I apparently used Boxen a long time ago, so `which node` tells me `/opt/boxen/nodenv/shims/node`.

I tired export `N_PREFIX=/opt/boxen/nodenv/` but that still didn't work. Any ideas how to make fix this issue?

**Comment by maxrimue** [comment]
You'll have to remove Boxen, or at least the Node.js it installed. I'm not sure how you would remove just Node.js from Boxen, but I found that this is how you remove Boxen itself:
> Run script/nuke from inside the /opt/boxen/repo directory.
(boxen/boxen#86)

**Comment by hzhu** [comment]
Thank you @maxrimue! Removing Boxen did the trick.
