### ISSUE TITLE
Ubuntu 14.04 install problem

### ISSUE THREAD

**Issue by luckylooke** [tj/n#291]
I have read all other install issues no one solved my problem.

```
$ sudo n stable
sudo: n: command not found
$ sudo -E env "PATH=$PATH" n stable

     install : node-v0.12.6
       mkdir : /usr/local/n/versions/node/0.12.6
       fetch : https://nodejs.org/dist/v0.12.6/node-v0.12.6-linux-x64.tar.gz
   installed : v0.12.6

$ node -v
v0.10.39
$ sudo -E env "PATH=$PATH" n rm v0.10.39
$ node -v
v0.10.39
```

PATH hack used from here: http://stackoverflow.com/a/29400598/861615

```
$ n stable
mkdir: cannot create directory ‘/usr/local/n’: Permission denied
mkdir: cannot create directory ‘/usr/local/n’: Permission denied
mkdir: cannot create directory ‘/usr/local/n’: Permission denied
mkdir: cannot create directory ‘/usr/local/n’: Permission denied

     install : node-v0.12.6
       mkdir : /usr/local/n/versions/node/0.12.6
mkdir: cannot create directory ‘/usr/local/n’: Permission denied

  Error: sudo required
```

I dont understand what happening... thanks for any help

**Comment by maxrimue** [comment]
How did you install n? In the second snippet, it says `cannot create directory '/usr/local/n'`, that directory should already exist

**Comment by luckylooke** [comment]
```
npm install n
```

**Comment by maxrimue** [comment]
How did you install Node.js before? What output do you get for `which node`?

**Comment by luckylooke** [comment]
```
$ which node
/usr/local/bin/node
```
Before I have had installed it via apt-get.

**Comment by maxrimue** [comment]
Hm, I think you should install n via this repo (so clone it and then do a `sudo make install`), then remove the Node.js you installed via any package manager and then try to install Node.js via n

**Comment by tedgaydos** [comment]
You need to export N_PREFIX to a folder your login can access if you do not want to use `sudo`. By default, `n` will try to use /usr/local. You will then also need to add $N_PREFIX/bin to the front of your PATH to make sire `n` managed node will take precedence ove rthe apt-get installed copy.

**Comment by luckylooke** [comment]
I was just checking node version again just to be sure before uninstall and it shows 0.12.6 corectly... I dont know what refreshed the version. Between issue post and now I have just installed some projects via yeoman. So I dont see any relevant information about solving the problem. Thank you for assistance and solution remains somewhere between Earth and sky.
