### ISSUE TITLE
uninstall a selected version causes error

### ISSUE THREAD

**Issue by gksu** [tj/n#292]
For example, I have node 0.12.5, 0.12.6 installed with n, and the current version of node I'm using is v0.12.5
```
$ n
    o node/0.12.5
      node/0.12.6
```
now I'm removing 0.12.5
```
$ n rm 0.12.5
```
and then I try to select another version
```
$ n
    node/0.12.6
```
**I can't select v0.12.6, the only thing I can do is hit enter and return to the command line with nothing changed**, then I discovered the node version I've just removed is still exist
```
$ node -v
v0.12.5
```
Still, I can change version with
```
$ n 0.12.6
```

**Comment by tedgaydos** [comment]
I've seen this issue before myself. I am looking into a fix.

**Comment by maxrimue** [comment]
I think n should just warn and abort if you try to remove the currently active version

**Comment by tedgaydos** [comment]
That's what I was planning on adding. A check against the active to make sure it's not removed before changing to a different version.

**Comment by maxrimue** [comment]
@tedgaydos I'll register both 1.4.1 and 2.0.1 as releases quickly in the repo, then you can push the necessary changes and we could get out 1.4.2 and 2.0.2 if you want.
