### ISSUE TITLE
Switching from io to node

### ISSUE THREAD

**Issue by artem-malko** [tj/n#299]
I use 2.0.1 version of n. I installed latest nodeJs and iojs 3.0.0 When i switched to io. Everything were fine. After that, I've decided to switch to node, but it still uses io.

**Comment by maxrimue** [comment]
Are there any errors you get?

**Comment by artem-malko** [comment]
@maxrimue No, there are no any errors. I just see iojs on Iterm tab, when js-code is running.

**Comment by maxrimue** [comment]
@artem-malko Have you ever installed Node.js/io.js with another way than to use n?

**Comment by artem-malko** [comment]
Yes, I've installed 0.10 version of NodeJs. But i switched to 0.12, which has been installed by n.

**Comment by maxrimue** [comment]
Try to remove every Node.js/io.js that was not installed with n

**Comment by artem-malko** [comment]
I removed io and nodeJs, but it still works with iojs.

**Comment by artem-malko** [comment]
Hm, I have to use sudo every time, when I change node version.

**Comment by maxrimue** [comment]
Yeah, that's normal that you have to use sudo since your user account
doesn't have write permissions for /usr/local/...
Artem Malko <notifications@github.com> schrieb am Mi., 12. Aug. 2015 um
18:40:

**Comment by artem-malko** [comment]
Ok, thank you a lot.
