### ISSUE TITLE
Can't select versions in Yosemite bash

### ISSUE THREAD

**Issue by bullitbd** [tj/n#300]
When trying to select a node version (n + enter), no bullit appears, and cursor is disabled:
Some troubleshooting:

$ which n
/Users/*username*/local/node/bin/n

$ which node
/Users/*username*/local/node/bin/node

$ node -v
v0.10.36

*also, if I use...*
$ n --stable
0.12.7
*then...*
$ node -v
v0.10.36 *...no change*

![screen shot 2015-08-18 at 4 37 17 pm](https://cloud.githubusercontent.com/assets/9753407/9345620/bc8b6fd6-45c7-11e5-9419-904a739b09a9.png)

**Comment by tedgaydos** [comment]
I have a couple questions.

Did you install from npm?
If so, what version of node did you install before and where?
Did you override N_PREFIX?

**Comment by bullitbd** [comment]
yes, installed from npm;
prior to n install, have 0.10.36 installed as above at: /Users/username/local/node/bin/node
did not override N_PREFIX

thanks.

**Comment by tedgaydos** [comment]
I am going to assume that /Users/username/local/node/bin/ is in the PATH and higher up than /usr/local/bin.

By default, n will manage everything from /usr/local. It looks like you want n to work from /Users/username/local/node/. Add `export N_PREFIX=/Users/username/local/node` to your .bash_profile file and load a new terminal. That should handle your issue.

**Comment by bullitbd** [comment]
Thank you.  Yes, that is correct (your PATH question).

Couldn't get things working, so I finally deleted everything and started over!  All works now - thanks for your response.  By the way, does this look like the normal basic 'n' directory structure?

$ tree -L 3
.
└── n
    ├── bin
    │   ├── n
    │   ├── n-uninstall
    │   ├── n-update
    │   ├── node
    ├── etc
    ├── include
    │   └── node
    ├── lib
    │   ├── dtrace
    │   └── node_modules
    ├── n
    │   └── versions
    └── share
        ├── man
        └── systemtap

**Comment by tedgaydos** [comment]
That looks like a normal `n` setup with everything under one root. Glad to assist and everything is working.

**Comment by bullitbd** [comment]
Good - I was curious about the /n/n nesting.  Thanks again.

**Comment by maxrimue** [comment]
@bullitbd Can this be closed now?

**Comment by bullitbd** [comment]
yep sorry.

**Comment by maxrimue** [comment]
No problem
Bob Day <notifications@github.com> schrieb am Sa., 22. Aug. 2015 um 18:15:
