### ISSUE TITLE
npm ERR! not a package

### ISSUE THREAD

**Issue by sbmthakur** [tj/n#302]
I got the following error when I ran $sudo npm install -g n :

npm ERR! not a package /tmp/npm-9404-9fUtIxWy/1440877967135-0.09174488740973175/tmp.tgz

I could only get past it after running $sudo npm install -g tj/n. I am not able to figure out why it didn't work for the former command.

**Comment by maxrimue** [comment]
That's strange. The usual reason for this error is that the `package.json` is invalid, but I just checked it again and it is valid JSON. Otherwise, the second command would have failed, too. Could you provide the full error output, or was it just that one line?

**Comment by comradealain** [comment]
Yes, it was only one line.

**Comment by maxrimue** [comment]
Did you try it just once or several times? Since I can't reproduce the problem, it seems like this was just a little bug with npm

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
