### ISSUE TITLE
Handling SIGINT on OS X doesn't show expected behaviour

### ISSUE THREAD

**Issue by maxrimue** [tj/n#304]
When exiting `n` while it's in fullscreen (with ctrl+c), `leave_fullscreen()` isn't executed and the shell remains weird until `tput rmcup` and `stty echo` are executed manually.

**Comment by courajs** [comment]
I came here to report this issue exactly

**Comment by mashiox** [comment]
This occurs on Ubuntu 16, too.

**Comment by troy0820** [comment]
I can't reproduce the problem to help with this issue.  I have a docker image `troy0820/node-n:16.04` that is an Ubuntu 16 and I can't reproduce it.  What version of `n` are you running?

**Comment by mashiox** [comment]
@troy0820 Whatever's on npm. I'm making a PR with my fix right this moment
