### ISSUE TITLE
n doesn't overwrite existing node version if trying to switch to the same version but just different architecture

### ISSUE THREAD

**Issue by cgadam** [tj/n#306]
Hi,

I'm running _n_ version _2.0.2_ and I'm getting this weird behavior: when trying to change node version to a version I already had installed but with different architecture _n_ does nothing. It just assumes that the version is already installed but, in fact, it's not because I need the same version but with a different architecture.

Seems like the architecture itself is not considered when checking if the version exists or not.

Example:

```
cgadam-mac01:public cgadam$ n --version
2.0.2
cgadam-mac01:public cgadam$ n 0.12.7

     install : node-v0.12.7
       mkdir : /Users/cgadam/n/n/versions/node/0.12.7
       fetch : https://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x64.tar.gz
   installed : v0.12.7

cgadam-mac01:public cgadam$ node --version && node -p -e process.arch
v0.12.7
x64
cgadam-mac01:public cgadam$ n 0.12.4
cgadam-mac01:public cgadam$ node --version && node -p -e process.arch
v0.12.4
ia32
cgadam-mac01:public cgadam$ n -a x86 0.12.7
cgadam-mac01:public cgadam$ node --version && node -p -e process.arch
v0.12.7
x64 //Here I would expect ia32 instead!
```

There's a workaround to this which consists on deleting the previous version and installing from scratch:

```
cgadam-mac01:public cgadam$ node --version && node -p -e process.arch
v0.12.7
x64
cgadam-mac01:public cgadam$ n 0.12.4
cgadam-mac01:public cgadam$ node --version && node -p -e process.arch
v0.12.4
ia32
cgadam-mac01:public cgadam$ n rm 0.12.7
cgadam-mac01:public cgadam$ n -a x86 0.12.7

     install : node-v0.12.7
       mkdir : /Users/cgadam/n/n/versions/node/0.12.7
       fetch : https://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x86.tar.gz
   installed : v0.12.7

cgadam-mac01:public cgadam$ node --version && node -p -e process.arch
v0.12.7
ia32
```

But it would be nice to consider the architecture part of the version! :+1:

**Comment by maxrimue** [comment]
Yeah, I have to admit this case wasn't considered. The architecture-overriding feature was added recently, but the feature for checking whether or not a certain version is installed is way older and wasn't touched by that patch. Currently, if you tell n to install a certain version, it'll check if inside its folder there's a folder with the version as a name, and if it's not it will create one and save the version in there. The architecture is just not checked. I could look what to change for n take a look at the specified architecture, too.

My idea would be:
In each version folder, there are architecture folders, so n would not only check if the version, but also if the architecture is installed. It would create this kind of structure:
```
n
>0.12.7
>>ia32
>>>`content`
>>x64
>>>`content`
```

I'll take a look on how to make this possible. Thanks for pointing out.

**Comment by EBZ-Krisemendt** [comment]
apperently this still is an issue. will it be fixed anytime?

stumbled on it while preparing an image for multiple raspberry versions. i need node in armv61 as well as in armv71 architecture. but due to this issue i can't use same version on both systems.

_i get an "invalid version" error as well, as i try to install the variant architecture but this could be handled by inserting the SD into a different raspi_

**Comment by JohnRGee** [comment]
@EBZ-Krisemendt : are you preparing a single shared image for multiple raspberry versions, or a separate image for each raspberry version?

It does not sound like you are trying to install different architectures on the same machine like the original poster, and I am wondering if you could use N_PREFIX to download the same version for multiple architectures to different locations.

**Comment by EBZ-Krisemendt** [comment]
sorry for being unclear. it's one image for different raspberry versions (namely B and B+).

will try using N_PREFIX, but since i already get an error (invalid version) if i want to download armv61 while on armv71 i'm not very hopefull

**Comment by JohnRGee** [comment]
Just in case you have a typo. You said twice looking to download `armv61` ending in one. But the architecture in the filename is`armv6l` with an L on the end.

e.g. `n --download --arch armv6l 8.11.2`

**Comment by EBZ-Krisemendt** [comment]
shame on me... you got me there. had a typo.

but still:
```bash
pi@lab1:~ $ sudo n install -a armv7l latest

  Error: invalid version install

```

**Comment by JohnRGee** [comment]
Another typo, have not got to the architecture problem yet. Take out the `install` which `n` does not use.

**Comment by EBZ-Krisemendt** [comment]
ok, it's working now. dont remember which tutorial told me to use that `install`

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
