### ISSUE TITLE
Unable to upgrade node.js from 4.0.0 to 4.1.0 using npm

### ISSUE THREAD

**Issue by jkwuc89** [tj/n#307]
I use the following helper bash script on my MacBook Pro to upgrade node.js when new releases come out.

``` bash
#!/bin/bash
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

Up through version 4.0.0, this script has been successful in upgrading my locally installed copy of node. Today, this script does not upgrade 4.0.0 to 4.1.0.

Is upgrading node via npm still supported?

**Comment by tedgaydos** [comment]
The stable keyword works under the assumption that even number minor versions are stable branches following the pre-4.0 versions. We are working on an update. To use `n` to install v4.1 use the command `sudo n latest`

**Comment by jkwuc89** [comment]
Using sudo n latest worked. Thanks for the tip.

**Comment by TheLudd** [comment]
FYI this was solved int the fork "ny" https://github.com/perint/ny/issues/8

Here is the commit: https://github.com/perint/ny/commit/cc52fc088e75b44343b6d4c02860b0859199d0df

Don't know if it will help =)

**Comment by troy0820** [comment]
I'm assuming this issue is resolved because @jkwuc89 said it worked.  If this issue needs to be open, I'll reopen it.  Just comment.
