### ISSUE TITLE
NODE_PATH is skipped

### ISSUE THREAD

**Issue by carlitux** [tj/n#312]
I I have this command to test

NODE_PATH=app:lib:frontend/javascript mocha

but not working on strider.

**Comment by qw3rtman** [comment]
AFAIK, `NODE_PATH` is used to specify where Node will look for a module if it can't find it in any of the other locations it checks first, not for running a test or any other command. [See this for more info.](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders)

**Comment by carlitux** [comment]
@qw3rtman yeah I found that... I tried to used shell script plugin but didn't work now creating a new container with that... thank you very much!
