### ISSUE TITLE
`n 0.8.5` and below fail on Mac OS

### ISSUE THREAD

**Issue by jamesshore** [tj/n#315]
v0.8.5 and below fail on Mac OS X 10.10.5 (Yosemite):

```sh
$ n 0.8.4

     install : node-v0.8.4

  Error: invalid version 0.8.4
```

v0.8.6 is the earliest version that works:

```sh
$ n 0.8.6

     install : node-v0.8.6
       mkdir : /usr/local/n/versions/node/0.8.6
       fetch : https://nodejs.org/dist/v0.8.6/node-v0.8.6-darwin-x64.tar.gz
   installed : v0.8.6
```

This is likely due to the `darwin-x64` distributable not existing in 0.8.5 and below.

**Comment by tedgaydos** [comment]
n supports version 0.8.6 and up. You can see all available version using the command `n ls` or `n io ls`
