### ISSUE TITLE
n doesn't work on os x

### ISSUE THREAD

**Issue by leaves4j** [tj/n#317]
the version of ox is 10.11,I installed the node v4.x and then installed v0.12.x by n,when switch on v0.12.x. the node dosen't work

**Comment by qw3rtman** [comment]
Could you provide the exact error that occurs?

**Comment by leaves4j** [comment]
if installed the node v4.x by the dmg file  and then installed v0.12.x by n，I can't switch the version,else I installed v 0.12.x first and then installed the v4.x， I can switch the version ,but when I choose v4.x,the node and npm doesn't work

**Comment by axvpast** [comment]
Looks like wrong dirs, expected that node (& n) installed in directory /usr/local/bin, but now it is installed into /opt/local/bin.

Pre conditions:
1. Upgrade MACOS to Capitan
2. Reinstall MacPorts
3. Install npm
4. Install n (sudo npm install n -g )
5. nodejs installed with version v0.12.7
6. n 0.10.20
7. n
Output does not contains any selected nodejs version. So I push Up/Down and got error message about wrong usage of grep command.

How to fix. Edit /opt/local/bin/n
N_PREFIX=${N_PREFIX-/opt/local}
BASE_VERSIONS_DIR=$N_PREFIX/n/versions

replace original /opt/local/bin/node by /opt/local/n/versions/node/0.10.20/bin/node

Switcher works.

**Comment by leaves4j** [comment]
I have solved the problem ,use 'sudo n version ' to install the node ,then switcher works

**Comment by TuningGuide** [comment]
What about using (so it does not matter which directory n is installed in):
```
DIR="$( cd "$(dirname `dirname "${BASH_SOURCE[0]}"` )" && pwd )"`
N_PREFIX=${N_PREFIX-DIR}
```

**Comment by troy0820** [comment]
Closing this issue
