### ISSUE TITLE
No input echo'ed after listing installed versions

### ISSUE THREAD

**Issue by MarcDiethelm** [tj/n#320]
- OSX 10.10.5
- Bash 4.3.42

Occurs in iTerm2 and OSX Terminal.

Steps to reproduce:

- `n`
- `CTRL-C`
- Entered keys and pasting from clipboard is not shown anymore

**Comment by qw3rtman** [comment]
I'm having trouble understanding the issue. Could you elaborate?

**Comment by MarcDiethelm** [comment]
I can't see what I type after listing the installed Node versions.

**Comment by Raederle** [comment]
I am having this issue as well.  I am running Yosemite 10.10.5.  n seems to do everything it should.  However, when I run n and get the list of available versions, there's no cursor.  

Additionally, when I try to use the arrow keys strange things happen.  Up arrow or down arrow brings spits out the command-line summary for grep at the top of the screen.  Left arrow, right arrow, and enter exit n without doing anything (as far as I can tell).

**Comment by edi9999** [comment]
This should be reopened, the error still appears

**Comment by upupzealot** [comment]
Same problem, any solution?
