### ISSUE TITLE
Node v5.0.0 :  Error: no installed version

### ISSUE THREAD

**Issue by mcpDESIGNS** [tj/n#325]
When trying to run `n` from the shell, it simply states:

    MyMac-iMac-2:sportstwits Philly$ node --version
    v5.0.0
    MyMac-iMac-2:sportstwits Philly$ n

    Error: no installed version

Any idea what's going on here?

**Comment by tedgaydos** [comment]
If installed from NPM, `n` will not have any managed versions of node yet. You have v5.0.0 as a stand alone version. `n` does not manage that, you would need to run `n latest` or `n 5.0.0'.

**Comment by mcpDESIGNS** [comment]
Thank you I think that did it! Now I installed 4.1.1 & 5.0.0 as I needed.
Much appreciated :+1: 

I got a bunch of Permission denied's when installing, but it seems to of all worked properly I can switch between the 2 of them, strange.

**Comment by tedgaydos** [comment]
If you use the default install location, you will need to run `n` with the `sudo` command to aviod the permission issues.
