### ISSUE TITLE
Windows 7 - 64bit : Unable to install : EBADPLATFORM Not compatible with your operating system 

### ISSUE THREAD

**Issue by mcpDESIGNS** [tj/n#326]
Getting a strange issue on Windows 7 64-bit when doing an install of `n`. It says `valid arch: Any`, I'm running cmd in administrator mode etc just in case as well.

`npm install -g n` 

![image](https://cloud.githubusercontent.com/assets/2574412/11243955/1780420a-8dd9-11e5-86b0-2bbb1ad3a5ee.png)

**Comment by DiscoNova** [comment]
And Valid OS says "anything but Win32", so there is nothing strange there; your OS simply is not supported ;)

**Comment by mcpDESIGNS** [comment]
Ouch, completely didn't notice that one :(
Is it possible to have muliple versions of Node on windows another way then?

**Comment by mcpDESIGNS** [comment]
For those running into this as well:
You can use `nvm` to install Node versions on Windows

https://github.com/coreybutler/nvm-windows

**Comment by czl1378** [comment]
@DiscoNova "Anything but Win32"... But his OS is 'Win7 - 64bit'! Did i have a misunderstanding of this?

**Comment by MarkPieszak** [comment]
It's only for Mac/Linux OS, use nvm-windows which is the same thing but works on windows 32 or 64 bit, and you'll be all set. @czl1378

**Comment by czl1378** [comment]
@MarkPieszak Thank you, i will do this.
