### ISSUE TITLE
seems n changes prefix for npm

### ISSUE THREAD

**Issue by amishurov** [tj/n#328]
How to reproduce on Ubuntu 12.04
sudo npm -g install n

```
/usr/bin/n -> /usr/lib/node_modules/n/bin/n
n@2.0.2 /usr/lib/node_modules/n
```

sudo npm prefix -g

```
/usr
```

sudo n 4.1.0

```
install : node-v4.1.0
mkdir : /usr/local/n/versions/node/4.1.0
fetch : https://nodejs.org/dist/v4.1.0/node-v4.1.0-linux-x64.tar.gz
installed : v4.1.0
```

sudo npm prefix -g

```
/usr/local
```

**Comment by JohnRGee** [comment]
I was reading up on this recently, so adding an answer to this old old question.

The `npm` docs say that by default:

> The prefix config defaults to the location where node is installed.

So in your case when you use `n` to install a copy of `node` to the default prefix of `/usr/local/` it also implicitly changes the prefix for `npm` to `/usr/local/` when that copy of `node` is running. (i.e. the new `node` executable is at `/usr/local/bin/node`)

<https://docs.npmjs.com/files/folders.html#prefix-configuration>

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
