### ISSUE TITLE
ability to install node/io master or tags

### ISSUE THREAD

**Issue by bo01ean** [tj/n#330]
I think it would be a nice feature to install the master (or any branch/tag) of node using n

There is a segfault issue on OS X here that requires a master build to work around:
https://github.com/nodejs/node/issues/4091

I apologize in advance if this functionality already exists :+1:

**Comment by qw3rtman** [comment]
Using the master build would require building the source. While this is possible, it would make the entire installation process very slow. Also, if a machine does not have all the prerequisites needed to build the source, the functionality will be useless.

An alternative would be to add an option to install from the nightly releases, which are built every 24 hours from the master branch. Would that solve your problem?

Example usage may be:
`n nightly` grabs the latest nightly release
`n nightly <today|latest>` also grabs the latest nightly release
`n nightly <back>` grabs the nightly release <back> days from today (if back is 1, it will grab the nightly release from right before the latest one)

**Comment by bo01ean** [comment]
That would be amazing. I forgot n installs a compiled binary

**Comment by williamkapke** [comment]
I just (finally) figured out now to install a nightly:
```bash
PROJECT_NAME="node" PROJECT_URL="https://nodejs.org/download/nightly/" n project 6.0.0-nightly201602102848f84332
```

Maybe put this in the README?

However: There are talks of changing (eliminating?) the nightly build. https://github.com/nodejs/node/issues/4856

**Comment by amio** [comment]
@qw3rtman Is this `n nightly` on planing?
Can't wait to try the new debugging interface ([The functionality has already reached Node.js nightly builds](https://developers.google.com/web/updates/2016/06/devtools-digest))

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
