### ISSUE TITLE
Removing io.js Support

### ISSUE THREAD

**Issue by qw3rtman** [tj/n#331]
Now that `io.js` has merged with Node, it may be time to remove `io.js` as an option. Thoughts?

**Comment by jwarkentin** [comment]
Not that I think it shouldn't necessarily be removed but for the sake of discussion I still have projects that depend on io.js and don't yet work with newer versions of node. I use n to manage my versions and it makes it easy to install exactly what I need. If support for io.js is removed then I will need to just remember to use an older version of n until I get everything updated.

**Comment by tedgaydos** [comment]
I would leave the io.js support in because people may still need to access versions before the merge.

**Comment by ralphtheninja** [comment]
Hi! Have you heard of semver? ;)

+1 for removing support for io.js and bumping major.

**Comment by jamen** [comment]
+1

**Comment by troy0820** [comment]
Does this issue still need to be open?

**Comment by shadowspawn** [comment]
io support removed in #516
