### ISSUE TITLE
n lts - attemt to install node long term support yields  Error: invalid version lts

### ISSUE THREAD

**Issue by callahanp** [tj/n#334]
# n --version
2.0.2
# npm --version
3.3.12
# node --version
v5.3.0
# ls /usr/local/bin
n  node  npm

# ls -lah /usr/local/bin
n
drwxr-xr-x  2 root root 4.0K Dec 29 12:35 .
drwxr-xr-x 12 root root 4.0K Dec 29 12:32 ..
lrwxrwxrwx  1 root root   27 Dec 29 12:32 n -> ../lib/node_modules/n/bin/n
-rwxr-xr-x  1 root root  25M Dec 29 12:35 node
lrwxrwxrwx  1 root root   38 Dec 29 12:35 npm -> ../lib/node_modules/npm/bin/npm-cli.js

# n lts

     install : node-vlts

  Error: invalid version lts

**Comment by qw3rtman** [comment]
Update `n` to `2.1.0` with `npm install -g n`.

**Comment by callahanp** [comment]
I agree this is closed in n@2.1.0-beta.1.

 The problem is npm install -g n gets you maxrimue's n, not tj's beta.   lts is not listed as an option in documentation on on maximrue/n but is shown on tj/n
It works on tj's latest beta.

use npm install -g tj/n instead of npm install -g n to get n verson 2.1.0-beta-1 as of 29-Dec-2015

**Comment by qw3rtman** [comment]
Just updated `npm`. `npm install -g n` should install `v2.1.0` now!
