### ISSUE TITLE
n stable installs the version before stable.

### ISSUE THREAD

**Issue by callahanp** [tj/n#335]
https://nodejs.org/en/ shows v5.3.0 as stable  n stable downloads v5.2.0
# n stable

   install : node-v5.2.0
       mkdir : /usr/local/n/versions/node/5.2.0
       fetch : https://nodejs.org/dist/v5.2.0/node-v5.2.0-linux-x64.tar.gz
   installed : v5.2.0

![screenshot from 2015-12-29 13-00-28](https://cloud.githubusercontent.com/assets/6132176/12039197/5e7dac56-ae2c-11e5-8008-fab671d855c6.png)

**Comment by qw3rtman** [comment]
Hmm, I'm not having this issue. Which OS and `n` version are you running?
<img width="697" alt="screen shot 2015-12-29 at 12 12 30 pm" src="https://cloud.githubusercontent.com/assets/1139621/12039375/9054e0de-ae25-11e5-9a4c-78e20307fde5.png">

**Comment by tedgaydos** [comment]
The stable keyword will only grab even number minor versions. It is still using the old way of finding node versions. To get the current version, use the latest keyword.

The stable keyword needs to be refactored to be an alias of lts.

**Comment by JohnRGee** [comment]
I got confused by this too when node was at 8.7. I have submitted a pull request which minimises code changes, and downgrades stable to an alias for lts in the documentation.

**Comment by troy0820** [comment]
![screen shot 2018-11-05 at 3 41 25 pm](https://user-images.githubusercontent.com/5985850/48025406-4ef25c80-e111-11e8-995e-aaaad7652ffe.png)
Now that LTS is considered stable this issue is closed with PR #467
