### ISSUE TITLE
"n use" doesn't support global node modules (easily)

### ISSUE THREAD

**Issue by tandrewnichols** [tj/n#338]
By default `n use <version>` looks for a node script in pwd, so things like `n use <version> grunt build` doesn't work because `grunt` is installed globally and not in your pwd (probably). You can get around this with a subshell, something like `n use <version> $(which grunt) build` or `n use <version> $(npm prefix -g)/grunt build`, but it's a bit awkward. It would be nice to see support for a `global` flag on the `use` command to make this simpler.

Maybe I'll even poke at this over the weekend, but I'm telling you now, any shell I write will need serious review (unless it's as simple as using `which`).

**Comment by bitdivine** [comment]
I don't use grunt myself but I have ported packages from people that do.  This is what I have done in similar situations:

* Add grunt as a dependency for that project.  That way you get a grunt for the right version of node.
* Instead of calling the global grunt, call the local one, in: ./node_modues/.bin/grunt

Hope that helps.

**Comment by tandrewnichols** [comment]
Yeah, there are ways around it, for sure. And for that matter, this is a generic node issue, not really n itself. If you do something like `$(which node) grunt foo`, it does the same thing. I'm just postulating that it could be a nice feature addition.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
