### ISSUE TITLE
[OS X] Support Homebrew 

### ISSUE THREAD

**Issue by icetee** [tj/n#339]
I installed nodejs with [Homebrew](http://brew.sh/) and it doesn't list `n list` command.
How to fix it?

![screenshot 2016-02-13 04 42 27](https://cloud.githubusercontent.com/assets/1855340/13025627/88aa756e-d20c-11e5-8045-c2b83cf922b7.png)

**Comment by sotojuan** [comment]
You're not supposed to install node with Homebrew. You're supposed to install n and install node with n.

**Comment by qw3rtman** [comment]
`n list` only displays Node versions installed with `n`.
