### ISSUE TITLE
Project name error when developing under React Native

### ISSUE THREAD

**Issue by andresn** [tj/n#342]
Not sure if this is the right home for this, but it looks like somewhere React Native uses the same global (likely for a different reason), but does not define a url value, causing the following error:

$: n

  Error: Must specify PROJECT_URL when supplying PROJECT_NAME

$: echo $PROJECT_NAME
React

Setting PROJECT_NAME='' fixes the issue; however, one would need to remember to set this back to 'React'  when switching back to an RN project -- probably a good idea to avoid issues under that framework. Therefore, perhaps namespace globals with N_?

**Comment by akeating** [comment]
I'm added a workaround to ~/.bash_profile:
alias n="PROJECT_NAME='' /usr/local/bin/n"

**Comment by facupedrazzini** [comment]
+1

**Comment by Chaunjie** [comment]
solved?@andresn

**Comment by sscaff1** [comment]
Ending your React Native packager also solves the issue (even though again this isn't a permanent fix).

**Comment by gaearon** [comment]
Find your `n`:

```
which n
```

Then edit this file:

```
nano /usr/local/bin/n
```

Remove these lines:

```
if [ -n "$PROJECT_NAME" ]; then
  BINS+=($PROJECT_NAME)
  BIN_NAME+=($PROJECT_NAME)
  if [ -z "$PROJECT_URL" ]; then
    abort "Must specify PROJECT_URL when supplying PROJECT_NAME"
  fi
  MIRROR+=(${PROJECT_URL})
  VERSIONS_DIR+=($BASE_VERSIONS_DIR/$PROJECT_NAME)
fi
```

This fixes the issue. Of course it's not a permanent fix but at least it makes n usable for me again.
:-)

**Comment by JohnRGee** [comment]
I wonder how many people are actually using `PROJECT_NAME` with `n`. I suspect most uses are to use major mirrors like taobao, and I think the undocumented `NODE_MIRROR` is a more elegant way of changing the canonical download source.

**Comment by shadowspawn** [comment]
I have been wondering how to fix this with minimum disruption to people actually using the `PROJECT_NAME` support. I would prefer to remove it, but who knows how many people are using it! I came up today with a possible approach:
- add `N_PROJECT_NAME`, which overrides `PROJECT_NAME`
- include support for `N_PROJECT_NAME` being blank to suppress old behaviour (specifically as a work-around for clash with React Native)
- later... show warning if `PROJECT_NAME` defined without `N_PROJECT_NAME` also defined
- much later... remove code for `PROJECT_NAME`

(If a fork of n is an option to readers with this problem, I removed `PROJECT_NAME` from https://github.com/shadowspawn/nvh )

**Comment by shadowspawn** [comment]
Prerelease available via `npm i n@next` for v6. Release notes: https://github.com/tj/n/releases/tag/6.0.0-0

**Comment by shadowspawn** [comment]
Removed `PROJECT_NAME` in v6: https://github.com/tj/n/releases/tag/v6.0.0
