### ISSUE TITLE
chose node version but nothing changed

### ISSUE THREAD

**Issue by benag** [tj/n#343]
did: sudo n
from the list chose 4.0.0
when doing node -v
still gets 0.10

**Comment by devflow** [comment]
In my case, problem is [nvm](https://www.npmjs.com/package/nvm). i just remove it.

**Comment by Jonnymcc** [comment]
See my comment here https://github.com/tj/n/issues/340, might explain why this is happening to you.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
