### ISSUE TITLE
Use `sh` instead of `bash`

### ISSUE THREAD

**Issue by theRemix** [tj/n#344]
For use in minimal environments, such as [alpine](http://www.alpinelinux.org/) which does not have bash installed by default.

**Comment by pavel-paulau** [comment]
This patch is not sufficient. If one just changes bash to sh, the the script will fail:
`/usr/bin/n: line 33: syntax error: unexpected "("`

`apk add bash` should help you.

**Comment by pavel-paulau** [comment]
In fact, there are many other places where `n` won't work.

For instance, wget doesn't support `--no-check-certificate` option.

**Comment by pavel-paulau** [comment]
`apk --update add bash curl nodejs tar` helped me.

**Comment by pavel-paulau** [comment]
Please notice that node binaries installed with n won't work out-of-the-box because of glibc:

```
# ldd /usr/local/bin/node
	/lib64/ld-linux-x86-64.so.2 (0x556108305000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x556108305000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x556108305000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f3913a24000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x556108305000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f3913811000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x556108305000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x556108305000)
Error relocating /usr/local/bin/node: __isinf: symbol not found
Error relocating /usr/local/bin/node: __rawmemchr: symbol not found
Error relocating /usr/local/bin/node: __isnan: symbol not found
Error relocating /usr/local/bin/node: __strtod_internal: symbol not found
Error relocating /usr/local/bin/node: backtrace: symbol not found
```

**Comment by tedgaydos** [comment]
Is this all while using Alpine?

**Comment by pavel-paulau** [comment]
Yup.

**Comment by qw3rtman** [comment]
@pavel-paulau, were you able to get it working?

Since this is a fairly niche issue, we could add steps specifically for Alpine users to follow in the `README`. What do you think, @tedgaydos?

**Comment by pavel-paulau** [comment]
Nah, I gave up eventually.

**Comment by qw3rtman** [comment]
@theRemix, sorry it didn't work for you. Unfortunately, I have no experience with Alpine.

I'll close this issue for now. If anyone manages to get `n` working on Alpine, we can add those instructions to the `README`.
