### ISSUE TITLE
Error on node installation for all 0.x versions

### ISSUE THREAD

**Issue by SFIDevelopment** [tj/n#346]
Hello,

I'm receiving a "Error: invalid version 0.x.x" exception whenever I try to install any version of Node prior to ver 4.0.  I can perform a "n ls" and clearly see the version(s) I'm trying to pull down are present, but the command (i.e. n 0.12.12) will not execute.

Working in Ubuntu for Raspbian Jessie, 2016-02-16 release.

Thoughts?

Thanks.

-C

**Comment by parties** [comment]
Bump; experiencing the same when trying to install 0.6.6.

I've tried `n v0.6.6` as well as `n 0.6.6`, both throwing the same exception.

**Comment by qw3rtman** [comment]
@SFIDevelopment: just to confirm, are you using Ubuntu or Raspbian Jessie?

**Comment by qw3rtman** [comment]
@parties, could you provide some details about your current OS?

**Comment by parties** [comment]
@qw3rtman I'm on Mac, El Capitan, v10.11.3.

**Comment by qw3rtman** [comment]
@parties, I believe the cause of your issue is different than that of @SFIDevelopment's issue. Could you open a new issue for your error?

**Comment by parties** [comment]
Sure thing, thank you.

**Comment by SFIDevelopment** [comment]
Any thoughts on the original post/issue?

**Comment by qw3rtman** [comment]
I have a feeling it has to due with either the lack of a pre-compiled binary for your OS or an issue in how `n` figures out your OS (so it can get the right pre-compiled binary).

Could you tell me what `uname -a` outputs for you?

**Comment by parties** [comment]
Apologies for the delay, here is the output of `uname -a`.

`Darwin ANA001-S-310.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64`

**Comment by seattleacademy** [comment]
Having a similar problem on a Raspberry Pi 3.  Need to check a module with 0.10.28 or similar.  uname-a outputs:
Linux rpi3 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

**Comment by tedgaydos** [comment]
Everyone here is trying to use versions of node that are not supported by `n` or supported for your OS/CPU combo.

@SFIDevelopment 0.12.12 is not supported for ARM processors.
@parties `n` does not support any version prior to 0.8.6 because there are no available compiled binaries. It is an issue that versions prior to 0.8.6 are visible.
@seattleacademy 0.10.28 is not supported for armv7l processors. It is only available for armv6l.
