### ISSUE TITLE
Error: invalid version 5.9.0 - can't install stable releases

### ISSUE THREAD

**Issue by MarkPieszak** [tj/n#347]
When running

```
sudo n 5.9 
or
sudo n latest (which tries to install 5.9)
```

It returns **Error: invalid version 5.9.0**

Running a MAC with OS X El Capitan (v 10.11.12)

**Comment by qw3rtman** [comment]
Are you still having this issue? The only reason I could think of is due to no internet connection.

**Comment by MarkPieszak** [comment]
It's fine on one Mac that is 10.10.3, but not on the other. Very strange... I'll try again later and get back to you!

**Comment by MarkPieszak** [comment]
That was it actually, there's something with that version of OS X.
I upgraded to 10.11.14 and now everything installed fine! Bizarre. Thanks @qw3rtman
