### ISSUE TITLE
Error on node installation for version ≤ 0.7 - Mac OS X

### ISSUE THREAD

**Issue by parties** [tj/n#350]
On El Capitan 10.11.3; trying to install version 0.6.6 and getting the error: `Error: invalid version 0.6.6`.

I've tried to find the boundary of what is installable and found that I can install `0.8.x` and higher, but nothing from `0.7.x` and lower.

I found [this check] in the source (https://github.com/tj/n/blob/e6b057918524e28155e954c94b24a574795dbf3c/bin/n#L485), but I'm not seeing why those particular versions would be invalid.

**Comment by qw3rtman** [comment]
After some investigation, it seems pre-compiled binaries aren't available for any versions prior to [`0.8.6`](https://nodejs.org/dist/v0.8.6) (take a look at [`0.8.5`](https://nodejs.org/dist/v0.8.5), for example).

I'm not sure if there has been any attempt at adding a fallback for this, such as having `n` simply download the source and compile it for you, but I think that would be the only option here.

cc @tedgaydos

**Comment by tedgaydos** [comment]
Yea. The script was set up to not allow installing anything before 0.8.5. But, somewhere along the way, the fix was lost when another merge stomped over a bunch of changes. I am looking for an "old" copy of the script that still has the lost features.

**Comment by parties** [comment]
Closing as per @tedgaydos's comment here: https://github.com/tj/n/issues/346#issuecomment-214086497
