### ISSUE TITLE
does n switch node_modules directory?

### ISSUE THREAD

**Issue by ghost** [tj/n#353]
node modules which is installed through npm , depends on node.js version.
does n switch node_modules directory when i change node version?

When I switched node.js version using n, node_modules directory seems not switched

```
$ node -v
v0.10.41
$ ls -l /usr/local/lib/node_modules
total 0
(installed node modules)
$ n use 5.2.0
$ node -v
v5.2.0
$ ls -l /usr/local/lib/node_modules
total 0
(installed node modules are not switched
 it's as same as when node.js v0.10.41)

```

how can I change directory based on enabled node.js version?

**Comment by tedgaydos** [comment]
`n` does not switch directories. It overwrites the binaries and node_modules folder from the base install the script downloads. It is an issue and have also experienced the problem. I will mark this as a feature request to look into how to maybe use symlinks or back copy node_modules when switching versions.

**Comment by Jonnymcc** [comment]
I made a PR that will persist node_modules when changing node versions https://github.com/tj/n/pull/364.
It does copy node_modules back to the installed version dir. I tried symlinks, but it seems as though `npm install -g npm` will follow the symlink and delete the contents of node_modules in the installed version dir. Essentially wiping out npm and requiring that the node version be removed and re-installed with `n` or npm re-installed manually.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
