### ISSUE TITLE
line 43: syntax error near unexpected token '$PROJECT_NAME'

### ISSUE THREAD

**Issue by aCodeBaby** [tj/n#357]
ATT, My linux version is 2.6.32_1-14-0-0, how to fix it?

**Comment by qw3rtman** [comment]
What version of `bash` are you running (check with `bash --version`)?

**Comment by aCodeBaby** [comment]
GNU bash(bdsh), version 3.00.22(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2004 Free Software Foundation, Inc.

**Comment by qw3rtman** [comment]
After some research, it looks like the syntax we use to add an element to an array is only supported in Bash `3.1-alpha1` and above.

I would recommend updating Bash as the latest version is `4.3`.
