### ISSUE TITLE
Error installing 'n'

### ISSUE THREAD

**Issue by cjkumaresh** [tj/n#358]
Getting the below error when try to install n

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: n@2.1.1
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kujayaraman\npm-debug.log

**Comment by qw3rtman** [comment]
Unfortunately, `n` is not supported on Windows (as indicated by your error) yet.

I'll make this more clear in the README!
