### ISSUE TITLE
Error: invalid version

### ISSUE THREAD

**Issue by StewartNoyce** [tj/n#365]
Attempted to upgrade node with n from v0.10.32 to v4.4.7 on a Mac (OSX 10.6.8).
```
bash-3.2$ sudo n 4.4.7
Password:

     install : node-v4.4.7

  Error: invalid version 4.4.7
```
Saw this error.  Reviewed similar issues, both closed and open.  Thinking that perhaps node 4.4.7 didn't work on the older Mac, I downloaded and installed the latest package from nodejs.org.  It works fine, but I have to remove it to run all existing projects with dependencies set for the older node version.  

What can be done to get n to load the newer version?

**Comment by qw3rtman** [comment]
`n 4.4.7` seems to be working for me on macOS Sierra. If it's not working for you, maybe try `n lts`, which will install the latest LTS version (currently 4.4.7).

What version of OS X are you running?

**Comment by StewartNoyce** [comment]
Thanks for the quick response.  Unfortunately, 'n lts' produced the exact same error message. 
 
I am running Snow Leopard (Mac OS X version 10.6.8) on a Mac Mini from mid 2009.  The LTS version, node v4.4.7, runs fine on this system (downloaded as a pkg and installed separately).  It just won't play nice with n.

**Comment by devleaks** [comment]
You're not alone. Same here. OSX 10.6.8, impossible to use n.

**Comment by StewartNoyce** [comment]
Further investigation exposes the deeper, unfortunate truth. 

One cannot go fully to node 4.4.7 (LTS) on OSX 10.6.8 because the newer node brings along grunt 1.x with a node-gyp dependency on a c++11-capable compiler that requires a version of xcode that does not support older OSX versions.  See [node-gyp do not pass -std=gnu++0x #922](https://github.com/nodejs/node-gyp/issues/922).

The Snow Leopard nears extinction and Apple hastens its demise.  Sadly, we must move on.

**Comment by qw3rtman** [comment]
Thanks for your research, @StewartNoyce! I think the README would benefit from this information. Send in a PR if you like! Perhaps the `Additional Details` section or near the top where the Windows incompatibility disclaimer would be a good place. 😄 

I'm going to close this issue now that the source of the problem has been found to be out of `n`'s control.

**Comment by StewartNoyce** [comment]
I'll give it a go with a PR.
