### ISSUE TITLE
Question: update npm version

### ISSUE THREAD

**Issue by Olgagr** [tj/n#374]
Is there any way to update npm version for particular node version ? Let's say I switch to node version 6.6.0. The npm version is 3.10.3 and I need to have version 3.10.6.

**Comment by jewelsjacobs** [comment]
I suppose you can refer to this closed issue: https://github.com/tj/n/issues/218

As recommended I did `npm install -g npm`.

**Comment by Olgagr** [comment]
@jewelsjacobs Thanks for answer. This is what I did, but still when I switch the node version with n, I get bundled npm version. For example, I switched to node 6.6.0, I did `npm install -g npm`, `npm -v` gave me as expected 3.10.6 but after switching to node 6.6.0 after a while, again I have bundled npm version -> 3.10.3.

**Comment by Mesieu** [comment]
@Olgagr  did you figure it out?
I have the same issue.

**Comment by Olgagr** [comment]
@Mesieu Unfortunately I didn't.

**Comment by soknifedev** [comment]
For those looking for a solution nowadays, what I did is to specify the npm version manually "npm install -g npm@7..0.0", since npm install -g npm@latest didn't work after switching the node version with n.

**Comment by shadowspawn** [comment]
See #484 for details about npm when switching node.js versions..
