### ISSUE TITLE
Installing nightly?

### ISSUE THREAD

**Issue by EvanCarroll** [tj/n#376]
It would be great if we could install nightlies, you can find the repos here. https://nodejs.org/download/nightly/

Especially to get async await, and more people testing these. Developers are also asking for feedback.

https://www.reddit.com/r/node/comments/53vhyk/please_try_a_new_inspect_commandline_switch/

**Comment by jwhitmarsh** [comment]
Came to check if this was possible for exactly the same reason!

**Comment by qw3rtman** [comment]
This is a great idea! If you're able to send in a PR for this, I'll merge it. 😄

**Comment by jbielick** [comment]
This'll work, although `n` has a hard time displaying it in `ls` 

`NODE_MIRROR=https://nodejs.org/download/nightly/ n 7.0.0-nightly20160930f5d997c476`

**Comment by qw3rtman** [comment]
Thanks, @jbielick! I've added a link to your solution at the top of the README while we work on building this feature into `n`. 😄

**Comment by doug-wade** [comment]
You can use @jbielick solution for the beta builds as well `NODE_MIRROR=https://nodejs.org/download/test/   n v7.0.0-test2016100609987d242b` (which would also be nice to add)

**Comment by EvanCarroll** [comment]
I think it should be easier than that... `n lts` installs the nightly copy, we need `n nightly`

**Comment by pkoretic** [comment]
@qw3rtman any news on this one?

**Comment by JohnRGee** [comment]
I am having a go at this in a fork and using `nightly/latest` syntax, influenced by `nvs`. If it works out sanely I'll look at a PR.

**Comment by JohnRGee** [comment]
I have a heavily modified [fork](https://github.com/JohnRGee/nvh) with [versions](
https://github.com/JohnRGee/nvh#specifying-node-versions) support for the binary [download folders](https://nodejs.org/download/) such as nightly, test, chakracore-release, et al. I am pleased with the syntax. e.g.

    nvh install lts
    nvh install nightly/8
    nvh install chakracore-release/latest
    nvh install test

```bash
$ nvh
    chakracore-release/v10.6.0
    nightly/v8.9.1-nightly20171104a815e1b6a2
    node/v8.11.4
  ο test/v11.0.0-test8ac916309b
```

Willing to start afresh and put together a pull request within existing commands if still interest from an `n` maintainer. Fairly extensive changes to support the new version patterns, and sorting reworked to cope with more filename patterns. Otherwise, fitted in reasonably well.

(NB: recent nightly/11 builds do not current include darwin binaries so not working on Mac!)

**Comment by frank-dspeed** [comment]
@JohnRGee are you still working on that ? because i wanted to implament it but your looks working already?

**Comment by JohnRGee** [comment]
I released support for nightly and the other binary download folders in [nvh](https://github.com/JohnRGee/nvh/) v3.0.0. I don't have any further work planned in that area. (Feedback welcome on using it for installing `nightly` for real work, I only used it for toy testing.)

**Comment by shadowspawn** [comment]
Update: it will be a while before `nightly` gets considered for `n`. If you give it a try in [nvh](
https://github.com/shadowspawn/nvh) then I am interested in feedback about how useful it is in practice.

**Comment by shadowspawn** [comment]
Prerelease available via npm i n@next for v6. Release notes: https://github.com/tj/n/releases/tag/6.0.0-0

**Comment by shadowspawn** [comment]
Added in v6: https://github.com/tj/n/releases/tag/v6.0.0
