### ISSUE TITLE
Rewrite of this?

### ISSUE THREAD

**Issue by EvanCarroll** [tj/n#379]
Would you consider a rewrite of this as a perl script? Perl is also in the LSB and distributed with every Linux distribution. Perl comes with LWP. I can vastly simplify this and make it much easier to maintain.

**Comment by EvanCarroll** [comment]
@tj  any interest in delegating? I want to close out some of the issues. I'd personally rather restart in Perl, but if not I'm going to close them out in bash. At least some kind of east of functionality to get on nightly/testing and the bug to delete old versions.

**Comment by fa7ad** [comment]
@EvanCarroll I'm not a perl programmer but can you explain why it would be better in perl than in other languages such as *C* or *Python*. Anyway, why don't you start a fork and see where that takes you.

**Comment by EvanCarroll** [comment]
Because Perl is far easier to write and maintain than shell. It's in the LSB. It ships with LWP which will be installed where `curl` and `wget` are not installed. It will be easier to test. Python, and even js would be better, imho, but they both have their own challenges. Python is not in the LSP and has a far smaller install base. Javascript is executed by node which is what this is trying to install.

I have *0* interest in a forking this project for shits and giggles.

**Comment by tj** [comment]
I don't see a point in rewriting, might as well be a new project then IMO.
