### ISSUE TITLE
Don't assume having Node installed

### ISSUE THREAD

**Issue by iMagdy** [tj/n#380]
From readme:

> Since you probably already have node, the easiest way to install n is through npm

This isn't the case in many scenarios, it's often needed to install this on fresh machines, without node, `nvm` does this. I think it'd be really nice to have this available here too.

**Comment by qw3rtman** [comment]
Consider using [`n-install`](https://github.com/mklement0/n-install)! If you scroll down a bit, the README mentions this alternative method.
