### ISSUE TITLE
Cannot switch node versions?

### ISSUE THREAD

**Issue by khelle** [tj/n#381]
``` shell
$> node -v
v5.7.1
$> sudo n latest
     install : node-v6.8.0
       mkdir : /usr/local/n/versions/node/6.8.0
       fetch : https://nodejs.org/dist/v6.8.0/node-v6.8.0-linux-x64.tar.gz
######################################################################## 100,0%
   installed : v6.8.0
$> node -v
v5.7.1
$> n
ο node/6.8.0
$> node -v
v5.7.1
```

What do I do wrong? How can I switch to node v6 ?

**Comment by pborenstein** [comment]
What does `which -a node` give you?

**Comment by khelle** [comment]
I fixed the problem by manually removing the symlink and creating a new pointing to the n node's location.

**Comment by hotrush** [comment]
same error
```
$ which -a node
/usr/local/bin/node
/usr/bin/node
```

**Comment by dcsan** [comment]
@khelle can you explain in more detail?

i have such a symlink:

```
ls -la /usr/local/bin

 n -> ../lib/node_modules/n/bin/n
```

so you removed that and replaced it with something pointed to the node binary, not the `n` script?

**Comment by roccomuso** [comment]
I'm having the same issue.

**Comment by EasonWang01** [comment]
I'm using arm system after ssh reconnect solved.

**Comment by RoanDev** [comment]
@roccomuso thanks that helps

**Comment by luisdelarosa** [comment]
Same - opening a new shell fixed this issue. Running Ubuntu Mate 16.04 on Raspberry Pi 3.

**Comment by guido4000** [comment]
It might help to remove the pre-installed version of node:
`sudo apt remove nodejs`

**Comment by shaharyar123** [comment]
Adding `sudo` works for me.

`sudo n 10.4.0` etc.

**Comment by shadowspawn** [comment]
I have added additional logging in v5.0.0 which should make PATH issues easier to identify.

Leaving this issue open for now since it includes the suggestion to reopen shell which has helped a lot of people: https://github.com/tj/n/issues/381#issuecomment-271722736

**Comment by shadowspawn** [comment]
Much improved error messages in v6: https://github.com/tj/n/releases/tag/v6.0.0

**Comment by shadowspawn** [comment]
`n` v6.1.2 has additional output for the situation when node command location changes, and the old location may be remembered by the current shell.

e.g.
```
Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"
```
 (Longer transcript: https://github.com/tj/n/issues/588#issuecomment-554601529)

**Comment by 1c7** [comment]
In my case, I forgot I also installed `nvm`.
I use `which -a node` found out
and then I just `nvm use 12.11.0`

**Comment by SupunKavinda** [comment]
My issue was I already had node installed via brew. Removing that helped

`brew remove node`

**Comment by JohannesFerner** [comment]
In my case ... somehow there was nvm installed as well. 
removing nvm (`rm -rf ~/.nvm`) fixed it

**Comment by menocomp** [comment]
None of these solutions fixed the issue for me.
Here is my docker file:
```
FROM alpine:3.15.0
RUN apk add --update --no-cache git less openssh bash npm gettext py-pip jq curl
RUN npm i -g n
RUN n 14
```
I git this error: `/usr/local/bin/n: line 744: /usr/local/bin/node: No such file or directory`

**Comment by shadowspawn** [comment]
@menocomp 
Alpine is not supported by the pre-built images on the standard mirror. `n` downloads a "normal" Linux build which does not run.

We have had some success with downloading from an unofficial mirror, if that is acceptable: https://github.com/tj/n/issues/648#issuecomment-763176280

**Comment by 5r33n** [comment]
could also be something as simple as switching version as root user but checking it as normal user.

**Comment by StarTaleLife** [comment]
> `rm -rf ~/.nvm`)

useful!thanks to resolve my prolem!
