### ISSUE TITLE
Version number of 2.1.4 not updated

### ISSUE THREAD

**Issue by pborenstein** [tj/n#382]
Looks like the version number in `bin/n` and `package.json` are out of sync:

**bin/n**

```
#!/usr/bin/env bash

#
# Setup.
#

VERSION="2.1.3"
```

**package.json**

```
{
  "name": "n",
  "description": "Interactively Manage All Your Node Versions",
  "version": "2.1.4",
```

**Comment by EvanCarroll** [comment]
The joys of not using a build system.

**Comment by EvanCarroll** [comment]
Also, it should be worth mentioning in the future @pborenstein you can actually edit the file in the github browser, make the change and it'll automatically fork and submit a pull request. I only say this because it's both easier, and far more useful. But thanks for catching this.
