### ISSUE TITLE
n work error in mac 10.11.13

### ISSUE THREAD

**Issue by zhugexiansheng** [tj/n#385]
I just install n, when i use n install lts and then n install 4.6.0,when it finish install, my node, npm can't work anyway; The error msg is 
"dyld: bad external relocation length
[1]    6986 trace trap  node"
I need to reload node.....

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
