### ISSUE TITLE
version error ?

### ISSUE THREAD

**Issue by vqoph** [tj/n#386]
I look like n package doesn't get the right version : 
```
$ n --lts
6.8.1

$ n --stable
6.8.1

$ n --latest
6.8.1
```

**Comment by icunioli** [comment]
Although I'm not sure if this could be the cause, according to the LTS schedule today should start LTS for v6 (https://github.com/nodejs/LTS#lts-schedule)

Best.

**Comment by vqoph** [comment]
ok thanks for your answer, I'll use the v4 manually.
