### ISSUE TITLE
Installing a -test version bugs out grep.

### ISSUE THREAD

**Issue by EvanCarroll** [tj/n#391]
Grep is reading the search string when you [install nightly](https://github.com/tj/n/issues/376) as an argument. Using the workaround in #376 https://github.com/tj/n/issues/376#issuecomment-252156076,

```
$ node --version
v7.0.0-test2016100609987d242b

```

gives you grep errors.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
