### ISSUE TITLE
n bin version not showing path when using lts as version

### ISSUE THREAD

**Issue by nbari** [tj/n#392]
When installing the latest versions using:

    n lts

at the moment of writing this 6.9.1 get installed

    n ls 

prints 

     ο 6.9.1

So far all good 

But if wan to get the path:

    n bin lts

An error is printed:

    Error: lts is not installed

The problem I am facing if that I would like to automate this process and keep a system always with the ``lts``version  but after installing using ``n lts`` I  need to create a symlink to that version, currently I am using a fixed version for example ``6.9.1``  ``/usr/local/n/versions/node/6.9.1/bin/node`` the one I link to ``/usr/bin/nodejs`` but would be nice to just use ``lts`` and no need to worry about what version to specify.

I am using the output of ``n bin`` to create the simlink

    path = /usr/local/bin/n bin {{ nodejs_version }}

But as described before when using ``lts`` as the version it doesn't work.

**Comment by jhermsmeier** [comment]
You could use `n bin $(n --lts)` as a workaround for now,
same should work with `--stable` and `--latest`.

**Comment by nbari** [comment]
@jhermsmeier many thanks is working, but If I have a custom version ``6.9.1`` and use:

    n bin $(n --6.9.1)

I get an  ``Error:  is not installed`` (n ls prints I do have it installed and as default)

Any idea of what flags or escape sequences could I use to just use a value `lts` or `6.9.1`

I would like to find a patter in order to simplify my automation tool.

Thanks in advance.

**Comment by jhermsmeier** [comment]
You could use a condition to check whether it starts with a digit, and if not – reassign it:
```bash
if [[ $node_version =~ ^[^0-9] ]] then
  node_version = $(n --$node_version)
fi
```

**Comment by nbari** [comment]
That's exactly what I want to avoid, would be nice to if ``n`` could handle it.

If currently is already  using a condition to install the latest, maybe same logic could be applied to just print the path. 

At the end I could implement many workarounds, but ideally would be nice to have ``n`` behave consistent with the options, maybe this could be an marked as an improvement.
