### ISSUE TITLE
Interested in helping build an official Node Version Manager?

### ISSUE THREAD

**Issue by williamkapke** [tj/n#393]
The Node.js Technical Steering Committee was asked to consider bringing `nvm` in to the Node.js Foundation to guide/govern it's future. This has been a long running discussion and I want to invite the contributors here to participate in the conversation.

As you know, there are a few version managers in the ecosystem and they offer different things to different use cases. Ultimately, we want to provide Node.js users with the best solution for most scenarios. So we've been asking "Is that 'nvm'? What about the other managers? What about Windows support?"... etc

We are considering creating a new Working Group that is made up of experts in this area to drive the solution. We know the folks contributing to this project have amazing perspective to offer and I hope you will join the conversation.

See:
https://github.com/nodejs/TSC/issues/96

**Comment by tjwebb** [comment]
@williamkapke thanks for reaching out. I'll follow the thread you linked to.
