### ISSUE TITLE
Error running on OpenWRT

### ISSUE THREAD

**Issue by sdaitzman** [tj/n#395]
N requires bash to run. I linked the ash shell, used by OpenWRT, to /bin/bash. When I run `# n latest`, the output is `bash: applet not found`. Is there a way to run n without calling bash? Or work around this somehow?

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
