### ISSUE TITLE
Doesn't update npm version when in Node >=7

### ISSUE THREAD

**Issue by hbarcelos-revmob** [tj/n#397]
This works fine:
```
➜ ~ % sudo n 4.3.0
➜ ~ % npm --version
2.14.12
```

This too:
```
➜ ~ % sudo n lts
➜ ~ % npm --version
3.10.8
```

But here it's broken:
```
➜ ~ % sudo n latest
➜ ~ % npm --version
3.10.9 # Should be npm@4.x.x
```
If I run any script, I get:

> \> npm build
> 
> npm ERR! Linux 4.4.0-47-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "build"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.9
> npm ERR! code MODULE_NOT_FOUND
> 
> npm ERR! Cannot find module 'internal/fs'
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/henrique/test/es6/npm-debug.log
> 
> npm ERR! Linux 4.4.0-47-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.9
> npm ERR! code ELIFECYCLE
> npm ERR! es6@1.0.0 prestart: `npm build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the es6@1.0.0 prestart script 'npm build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the es6 package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs es6
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls es6
> npm ERR! There is likely additional logging output above.
>

**Comment by xixixao** [comment]
Confirmed, npm installation is broken.

**Comment by troy0820** [comment]
@xixixao @hbarcelos-revmob 
From the README:
```
Working with npm

After switching Node.js versions using n, npm may not work properly. This should fix it (thanks @mikemoser!):

$ curl -0 -L https://npmjs.org/install.sh | sudo sh
sudo may not be required depending on your system configuration.
```

Try that to see if that fixes your problem. I'm trying to reproduce the error and I'm not getting it.

**Comment by hbarcelos-revmob** [comment]
For the record, I'm using Ubuntu 14.04 at work. Here I have this problem.
At home, I use Arch Linux and didn't have the same problem.

**Comment by troy0820** [comment]
@hbarcelos-revmob @xixixao I'm trying to reproduce the error and I'm not getting it.  I also made a docker container that you can try it on to see if you are getting the same error.  Did you install nvm first? What version of this are you running? 

If you have docker installed, you can run this container and try to replicate the errors you are getting.  
```
docker run -it troy0820/node-n:1.0
sudo -i
```
After that run some n commands and if you can output in this issue if you are receiving them there as well.

**Comment by troy0820** [comment]
@hbarcelos-revmob @xixixao Did this work for you? Can this issue be closed?

**Comment by hbarcelos-revmob** [comment]
@troy0820 

I just ran

```
n latest
```
It installed `node@7.4.0` and `npm@4.0.5` as expected.

For the record, I'm running  `n@2.1.3`.

**Comment by tony-gutierrez** [comment]
This is def still an issue. N refuses to update npm.
