### ISSUE TITLE
Doesn't render with solarized terminal color scheme

### ISSUE THREAD

**Issue by owais** [tj/n#401]
What it looks like:

<img width="670" alt="screen shot 2016-12-29 at 1 36 31 am" src="https://cloud.githubusercontent.com/assets/46186/21530514/63c1af54-cd67-11e6-8265-f47c12cb9460.png">

-------------

What it looks like after selecting text:

<img width="659" alt="screen shot 2016-12-29 at 1 36 37 am" src="https://cloud.githubusercontent.com/assets/46186/21530523/6d36df00-cd67-11e6-87f4-3d64a07192f2.png">

-------------------

I'm using iTerm2 Build 3.0.13 on OS X with Fish Shell and Solarized color scheme.

**Comment by sercanov** [comment]
+1, dark fonts are not visible

**Comment by troy0820** [comment]
Issue resolved with PR #412
