### ISSUE TITLE
Managing global modules after moving from platform-packaged nodejs to n

### ISSUE THREAD

**Issue by rosemead** [tj/n#402]
Hi.
Been using stock node (ubuntu. Installed via apt. /usr/bin/node). Have installed several packages globally (npm i -g: grunt, mocha, jasmine et al). Then moved on to use n, which prompted the removal of the existing node package. Installed n under $HOME.

Question: what's the suggested solution for managing said global modules, now that npm doesn't see them anymore: How do I list/remove/upgrade those packages? 

Thanks!

**Comment by JohnRGee** [comment]
If you are now running npm out of your home folder, then reinstalling the global packages under your home directory might be the simplest way.

If is likely to be confusing at some point having things installed twice though, so removing the unwanted install is worth doing too. You can check for multiple copies of an executable using the `-a` option of the `which` command. e.g.
```
which -a npm
which -a grunt
```
You can check where your npm is putting global executables with `npm bin -g`

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
