### ISSUE TITLE
Using n can break npm features like scopes

### ISSUE THREAD

**Issue by gnestor** [tj/n#403]
Some of my `npm install`s were failing with `Invalid name: "@jupyterlab/services"`. After doing some research, I found https://github.com/npm/npm/issues/13986#issuecomment-264503491, ran `npm install -g npm@latest` and my issue was resolved. However, if this comment is correct, then n may be the culprit:

> The reason you need to delete and then reinstall Node.js / npm is that this happens due to the fact that the Node.js installer (and potentially n, I guess) doesn't wipe out the existing installation of npm before unpacking the new one over the top of it. This means that some of npm's dependencies end up in an inconsistent state and use older versions of dependencies when they shouldn't be. This is a bug in those installers, and not one that npm can fix itself, due to the nature of the problem.

**Comment by shadowspawn** [comment]
Hopefully fixed by #470 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
