### ISSUE TITLE
Enbale to install 

### ISSUE THREAD

**Issue by nodejquery11** [tj/n#406]
Hi Nimit,

It is not an issue but I am unable to install the `n` module. While I was trying to install the `npm n`, it gave me the version issue between npm & node. 
Please help me out or guide me that how can I update node version using `npm n`. For your reference I have attached the screen shots
![capture-pic1](https://cloud.githubusercontent.com/assets/18608441/22075400/dfbdc9ba-ddd1-11e6-997f-95b50cce78c4.JPG)
![capture-pic2](https://cloud.githubusercontent.com/assets/18608441/22075416/e9657d5a-ddd1-11e6-9a5f-b7d165306200.JPG)

Thanks
Vikas

**Comment by ewanharris** [comment]
@nodejquery11 As stated in the readme, n does not support Windows. An alternative for Windows is https://github.com/coreybutler/nvm-windows

**Comment by troy0820** [comment]
Closing this issue 👍

**Comment by nodejquery11** [comment]
Thanks all 👍
