### ISSUE TITLE
Failed to create symlink for binary

### ISSUE THREAD

**Issue by jrmhaig** [tj/n#408]
I have tried to install the [localinclude](http://bbcnewslabs.co.uk/2017/01/13/localinclude/) module with 

```bash
npm install -g localinclude
```

and it has installed the binary to `/usr/local/n/versions/node/6.0.0/bin` but has not created a symlink into a directory in `$PATH`.

I presume that the link should have been put in `/usr/local/bin`, which is where the link for node is.

**Comment by troy0820** [comment]
@jrmhaig : 

* What version of `n` do you have installed?

* Can you run `which n` and `which localinclude` and put the output in this issue. 

* What OS are you running on? 

* If you have docker installed, you can run this in a container by running 

```bash
docker run -it troy0820/node-n:latest
sudo -i
npm i -g localinclude
``` 
You will see it working on that environment.

**Comment by jrmhaig** [comment]
```bash
$ which n
/usr/local/bin/n
$ n --version
2.1.0
```

I have created the symlink but `which localinclude` was returning nothing. The OS is ubuntu 16.04.1 LTS and we are not using docker.

**Comment by troy0820** [comment]
Your issue sounds like it may be with `localinclude` but I can run it in that container which is also running ubuntu:16.04.  That container is `troy0820/node-n:16.04`

I know you don't have docker but this is how you would run the image in a container to test the issue. 

```bash
docker run -it troy0820/node-n:16.04
```
