### ISSUE TITLE
When running npm run lint it uses the right npm version, but the wrong node version

### ISSUE THREAD

**Issue by wlsf82** [tj/n#413]
OS: MacOs Sierra 10.12.3

n version: 2.1.4

I'm not installing `n` globally. May this cause the issue?
This is the way I'm installing it.

`npm install n@latest`

### Steps to reproduce issue:
1. `./node_modules/.bin/n ${NODE_VERSION_7}`
2. `./node_modules/.bin/n ${NODE_VERSION_7} # If <version> has already been installed (via n), n will activate that version.`
3. `${N_PREFIX}/n/versions/node/${NODE_VERSION_7}/bin/npm install`
4. `${N_PREFIX}/n/versions/node/${NODE_VERSION_7}/bin/npm run lint`

Result:

```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/my-user/www/my-project/n/n/versions/node/7.5.0/bin/npm" "run" "lint"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
```
Note that node version used to install is the one installed on my global environment (`6.9.5`), but the npm version being used is the one from node.js version 7.

**Comment by wlsf82** [comment]
Just to update, the same issue happens when n is installed globally. :/

**Comment by troy0820** [comment]
How did you install `n`? Do you have `nvm` installed? Please do a `which n` since you have it globally installed so I can get some more information on your issue. 

I have a docker container that you can test your issue out on.  If you have docker installed, you can test your use case in this container by running 
```bash
docker pull troy0820/node-n:latest
docker run -it troy0820/node-n:latest
sudo -i
```
You should see version `7.4.0`

**Comment by troy0820** [comment]
Try using `n use <version>` in your script.  _since it's global now_ 

You can see where the version you are trying to target is installed with `n bin <version>` and use that for your script.  i.e. 
```bash
n bin 7.4.0
/usr/local/n/versions/node/7.4.0/bin/node
```
Then in your package.json `scripts` object, target that `/usr/local/...` for whatever version you want.  
@wlsf82

**Comment by wlsf82** [comment]
The problem is that I'm trying to install node and npm in a place different than `/usr/local/.../`, then when running `./node_modules/.bin/n use 7.6.0` (for example), I got the following error: `Error: 7.6.0 is not installed`, but actually this version is installed in the following location `${N_PREFIX}/n/versions/node/${NODE_VERSION_7}/`, where `${N_PREFIX}` is equal to `export N_PREFIX=`pwd``

**Comment by wlsf82** [comment]
The main issue is that I cannot use n globally, because it will be executed by a user that doesn't have sudo permissions.

**Comment by troy0820** [comment]
> ./node_modules/.bin/n use 7.6.0

Your script in your package.json should be `./node_modules/n/bin/n 7.6.0;`  which will execute installing 7.6.0 then whatever you want to do after that.  Installing n doesn't give you npm even when you change versions, 

So for instance if you are doing this in a travis-ci env to test multiple versions it would need to be globally installed, the ./node_modules are not in your path to execute this.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
