### ISSUE TITLE
please republish after version bump

### ISSUE THREAD

**Issue by Ognian** [tj/n#417]
use `npm view n` to see which version and when it was published in the npm registry
you will notice that
``` 
'2.1.4': '2016-08-07T20:02:06.732Z'
```
2.1.4. has been published on August 8 2016
and not republished especially when the version string was changed to 2.1.4 which was on Dezember 17 2016...

**Comment by troy0820** [comment]
I can't publish over `2.1.4` so I would have to bump this to `2.1.5`  and fix that in the `bin/n`

**Comment by troy0820** [comment]
n@2.1.5
