### ISSUE TITLE
Simplify Installation section in README

### ISSUE THREAD

**Issue by stevestock** [tj/n#418]
### Issue Type: Documentation

Recommend simplifying the README to put the `n-install` option right after the `npm` option, and having a separate section for manually building via `make install` and setting up environment variables.  In my experience, long "getting started/installation" sections can turn people away.

What drew me to use n over nvm was the simplicity.  
From a brand new machine, `curl -L https://git.io/n-install | bash`, new terminal, `node latest`, done
I don't think the documentation sells that.

If you're interested, I can put together a PR.

**Comment by troy0820** [comment]
Yeah if you want to contribute to the docs, I'd definitely appreciate it.  Put a PR in and we will see what we can do.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
