### ISSUE TITLE
Problem installing node using `n 4.5.0'

### ISSUE THREAD

**Issue by gmacgr** [tj/n#433]
I am using CentOS 6.6 and trying to use 'n' to install a version of nodejs I wish to use with RocketChat. 
` node -v
v0.10.48`
` n -V
2.1.7`
`npm -v
2.15.9`

I installed `n` using `npm install -g n`

Issue:

```
[root@testVm1~]# n 4.5.0

     install : node-v4.5.0

  Error: invalid version 4.5.0


```
Any suggestions on what i might be doing wrong?  I was successful using this in CentOs 6.9 but I need to use 6.6 for it.  

I also attempted to `n stable` and got:
```
[root@testVm1~]# n stable

  Error: invalid version

```

**Comment by troy0820** [comment]
Please use the template...

What happens when you try to `n ls`?  
From the looks of it, it looks like you don't have curl installed on your machine.  `yum install curl` 

I have this in a `docker container` that you can run with `docker run -it troy0820/node-n-centos:6.6 /bin/bash`.  After you have it running, you can try to install some versions `n lts` n latest` and use `n` to switch between them.  I hope this helps.

**Comment by gmacgr** [comment]
Hi Tony,

Sorry about the template, I removed the headers but it was basically in the same layout.

`n ls` gives back nothing, which doesn't make sense according to the docker container you suggested..  

I have curl installed 
```
[root@testVm1~]# rpm -qa | grep curl
curl-7.19.7-37.el6_5.3.x86_64
python-pycurl-7.19.0-8.el6.x86_64
libcurl-7.19.7-37.el6_5.3.x86_64
```

Does N use ssl for connections?

**Comment by troy0820** [comment]
It's Troy....

You are probably having a SSL issue.  `openssl` probably needs to be updated. 

Did you try to run the docker container?  If you have docker, I would try that container and compare it to your VM. It's CentOS v6.6 and it can help you troubleshoot the problem better.

The mirror we use in `n` is `https://nodejs.org/dist/`.  If you can't wget or curl that url, then you may have a bigger issue than just `n`.  

Also these are the minimum packages I installed on the `centOS:6.6` docker container and got it working.  `yum update -y && yum install curl tar zip wget which -y`.

**Comment by gmacgr** [comment]
That looks like the problem...I cannot curl https://nodejs.org/dist/
```
[root@atfmchatdev1 ~]# curl https://nodejs.org/dist/
curl: (35) SSL connect error
```

Time to figure out why ssl isn't working....

Thanks for the help Troy, and sorry about the miss typed name, Auto correct changed it and I never noticed.

**Comment by troy0820** [comment]
@gmacgr Are you still having this problem?  Did you try the docker container?

**Comment by gmacgr** [comment]
Yes still issues but only on testVm1.  Looks like the SSL config is broken at Change Cipher Spec during the SSL connection. 
  
I  deployed another VM and installed nodejs and n.  It appears to be working as the curl commands are as well.  Not sure what went wrong with testVm1 install and the ssl configuration as i did not change the default.  

Thanks for the help, and the docker container.
