### ISSUE TITLE
Error installing on x64 Windows 10

### ISSUE THREAD

**Issue by mickyinba** [tj/n#435]
on my Windows 10 64-bit
I couldn't install n using command "npm install -g n". The error that I got was:
npm ERR! notsup Unsupported platform for n@2.1.7: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x6 4"})

**Comment by troy0820** [comment]
The README states `n does not work on Windows at the moment. Pull Requests are appreciated.`

I haven't tried to see if this works with Windows 10 inside the ubuntu bash shell yet.

**Comment by brodybits** [comment]
FYI https://github.com/jasongin/nvs supports Windows as well as macOS & other *nix.
