### ISSUE TITLE
Node binary cannot be found in macOS Sierra

### ISSUE THREAD

**Issue by isiahmeadows** [tj/n#436]
**OS:** macOS Sierra
**`n` version:** 2.1.7
**Installation method:** `curl -L https://git.io/n-install | bash`
**Installation location:** `/Users/<username>/n/bin/n`

## Symptoms

I had issues selecting the version, and saw that `grep` was printing its help message, so I began to investigate.

## Underlying cause

What I found was that no Node version is found, despite verifying one *should* be found. What happened is that it assumes the `node` binary it finds via `which node` matches one of `n`'s managed versions (i.e. no binary diff). Because it makes that invalid assumption, it breaks when they all differ.

## Proposed fix

- Create a directory that contains the active `node` and `npm`, and prepend it to the `$PATH` if it's not already there, taking precedence over the existing binaries.
- When changing versions, diff against that local folder rather than the result of `which node` and `which npm`.
- Allow reverting to the system version, in which you just clear the `node` and `npm` binaries from the exposed folder.

----

One item of note for perf/stability improvements is that you can `break` and `return` from inside loops within Bash. But that's mostly unrelated.

**Comment by troy0820** [comment]
Using the 3rd party installer puts `n` in `$HOME/n/bin`.  This in Mac OS Sierra isn't in your path originally.  This 3rd party installer isn't where the functionality of where that installer puts `n`.  If you are using mac os sierra the easiest way to install `n` is to use `npm i -g n` which will symlink your node binary to the version selected.

**Comment by isiahmeadows** [comment]
Okay. That resolved my issues. I'll complain in `n-install`.
