### ISSUE TITLE
Uninstall n from Windows

### ISSUE THREAD

**Issue by heliotpile** [tj/n#439]
I installed n on Windows without knowing it was not compatible at first. I would like to remove n from my machine, but it will not uninstall.

# Issue Template:

### Describe issue including what OS you are using
Windows 10

### Describe what version of N you have
2.1.7

### Describe how you installed N
npm install -g n

### Steps to reproduce issue _1.2.3_
1) npm uninstall -g n
2)  n --version     #Shows that n is still installed

### Describe the results you received
I cannot remove n from my machine. npm uninstall does not remove n and even uninstalling node shows that it is still installed)

### Describe the results you expected
I was supposed to get an error that n is not installed or not a valid command, but I am still able to use n.

### What version of npm you are using
5.0.0

### Additional information you deem important (e.g. issue happens only occasionally):
Even when uninstalling ndoe, n still is installed.

**Comment by Aladdin-ADD** [comment]
how did you do that? I get some errors when install n on windows 10.
![image](https://cloud.githubusercontent.com/assets/13050025/26742186/4333cca4-480f-11e7-8d96-34c965a5cb78.png)

**Comment by heliotpile** [comment]
I made an Angular2 project and ran "npm install n" in it. I didn't get any errors, it just worked and now won't uninstall.

**Comment by RifeWang** [comment]
@Aladdin-ADD I got the same error , have u solved that?

**Comment by Aladdin-ADD** [comment]
@RifeWang no, seems it is incompatible with windows. u can try some other version manager, like nodist.

**Comment by troy0820** [comment]
I have to try to reproduce this problem on a Windows machine.  Can't do it from a linux/mac right now.

**Comment by paolord** [comment]
@heliotpile did you install using "npm install -g n" or "npm install n" or did you do both, the statements in your comments says you did both.

**Comment by heliotpile** [comment]
@paolord I did both, although I did "npm install -g n" first.

**Comment by blling** [comment]
how to uninstall it from linux?:)

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
