### ISSUE TITLE
error installing node version on macOS

### ISSUE THREAD

**Issue by ahmedelgabri** [tj/n#443]
# Issue Template:

### Describe issue including what OS you are using

macOS Sierra 10.12.5

### Describe what version of N you have
2.1.7

### Describe how you installed N

`npm i -g n`

### Steps to reproduce issue _1.2.3_

`n latest` or `n <version>`

### Describe the results you received

```
~
λ n latest

     install : node-v8.1.0
       mkdir : /usr/local/n/versions/node/8.1.0
       fetch : https://nodejs.org/dist/v8.1.0/node-v8.1.0-darwin-x64.tar.gz
######################################################################## 100.0%
cp: cannot overwrite non-directory '/usr/local/include/node' with directory '/usr/local/n/versions/node/8.1.0/include/node'
cp: cannot overwrite non-directory '/usr/local/share/doc/node' with directory '/usr/local/n/versions/node/8.1.0/share/doc/node'
cp: cannot overwrite non-directory '/usr/local/share/systemtap' with directory '/usr/local/n/versions/node/8.1.0/share/systemtap'
   installed : v8.1.0
```

### Describe the results you expected

To work without errors

### What version of npm you are using

5.0.3

**Comment by troy0820** [comment]
Try sudo.  

it looks like you can't write to that directory.  You can either use sudo or you can chown that directory to not use sudo.  I would recommend chown'ing the directory.

**Comment by ThomasHuke** [comment]
讲真，层主一个说英语的人，看不懂提示， 我也是醉了，我都能看懂，我英语这么烂
