### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jordanjtidwell** [tj/n#444]
# Issue Template:

### Describe issue including what OS you are using

_i.e. I'm using MacOS Sierra_

### Describe what version of N you have
_i.e. n --version output: 2.1.4_

### Describe how you installed N

* _i.e. npm install -g n_
* _i.e. make install_

### Steps to reproduce issue _1.2.3_
_i.e._
1. n latest
2. couldn't pull latest from source

### Describe the results you received

_i.e. blank screen_
### Describe the results you expected

_i.e. I was supposed to see the lastet being pulled from source_

### What version of npm you are using

_i.e. npm --version output: 4.0.5_

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:`
* Output of `node -v:`

**Comment by troy0820** [comment]
Nothing in issue.
