### ISSUE TITLE
Tag the latest version on GitHub

### ISSUE THREAD

**Issue by danielbayerlein** [tj/n#445]
Can you tag / release the latest version on GitHub (https://github.com/tj/n/releases), please?

**Comment by troy0820** [comment]
Latest tag pushed, I'll push the other tags that are between 2.1.4 -> 2.1.6 later and add some release notes as well.

**Comment by danielbayerlein** [comment]
Thank you 👍

**Comment by Phyks** [comment]
Seems like tag 2.1.8 is not pushed to Github either :/ Thanks!
