### ISSUE TITLE
n: command not found

### ISSUE THREAD

**Issue by matt3224** [tj/n#447]
### Describe issue including what OS you are using
CentOS 7

### Describe what version of N you have
Latest Version

### Describe how you installed N

npm install -g n_

### Describe the results you received
Upon a clean install of n I received no errors but am unable to run n as it says 'command not found'

### Describe the results you expected
I expected it to work

### What version of npm you are using
npm --version output: 4.0.5

#### (paste your output here)
```
[root@sergio /]# npm install -g n
/root/.node_modules_global/bin/n -> /root/.node_modules_global/lib/node_modules/n/bin/n
/root/.node_modules_global/lib
└── n@2.1.8 

[root@sergio /]# n
-bash: n: command not found
```

**Comment by troy0820** [comment]
Try sudo n

**Comment by matt3224** [comment]
Ok I tried this but it's the same:
```
[root@sergio /]# sudo npm install -g n
/root/.node_modules_global/bin/n -> /root/.node_modules_global/lib/node_modules/n/bin/n
/root/.node_modules_global/lib
└── n@2.1.8 

[root@sergio /]# sudo n
sudo: n: command not found
[root@sergio /]# 
```

**Comment by troy0820** [comment]
Check to see if n is in your PATH. Try `which n` And you should see where n is installed. If that is in your PATH, you should be good to go.

**Comment by matt3224** [comment]
I get this: `/usr/bin/which: no n in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/usr/local/easy/bin:/usr/local/rvm/bin:/root/bin)`
how can i fix the path?

**Comment by matt3224** [comment]
Its ok i fixed it, thanks
