### ISSUE TITLE
Some versions of wget don't pass is_ok

### ISSUE THREAD

**Issue by spencer-rig** [tj/n#449]
# Issue Template:

### Describe issue including what OS you are using

I'm using a custom Linux distribution built by [Yocto](https://www.yoctoproject.org/). arm7l architecture. This includes `wget` from `BusyBox v1.24.1 (2017-06-18 18:12:16 PDT) multi-call binary.`, which does not recognize the `S` option.

```
# wget
BusyBox v1.24.1 (2017-06-18 18:12:16 PDT) multi-call binary.

Usage: wget [-c|--continue] [-s|--spider] [-q|--quiet] [-O|--output-document FILE]
	[--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
	[-U|--user-agent AGENT] [-T SEC] URL...
```

### Describe what version of N you have

```
# n --version
2.1.7
```

### Describe how you installed N

`npm install -g n`

### Steps to reproduce issue _1.2.3_

1. Install `n` on this particular OS
2. `n lts`

### Describe the results you received

```
# n lts

  Error: invalid version 6.11.1

```

I debugged it to see which "invalid version" this abort was. It's the one on https://github.com/tj/n/blob/master/bin/n#L560

### Describe the results you expected

```
# n lts

     install : node-v6.11.1
       mkdir : /usr/local/n/versions/node/6.11.1
       fetch : https://nodejs.org/dist/v6.11.1/node-v6.11.1-linux-x64.tar.gz
   installed : v6.11.1

```

### What version of npm you are using

```
# npm --version
4.2.0
```

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
