### ISSUE TITLE
Please change the name `N` to something easier to search for

### ISSUE THREAD

**Issue by piggyslasher** [tj/n#455]
# Issue Template:

### Describe issue including what OS you are using

N/A

### Describe what version of N you have
N/A

### Describe how you installed N

npm install -g n

### Steps to reproduce issue _1.2.3_
1. n latest

### Describe the results you received
Well I spent almost a minute finding you. That's too long.

_i.e. blank screen_
### Describe the results you expected
Refer to previous.

### What version of npm you are using

Doesn't matter

### Additional information you deem important (e.g. issue happens only occasionally):

n <- this needs to change, pretty please.

**Comment by OpaqueSky** [comment]
Windows 10 OS 

Sent from Evangelical Orthodox Catholic iPad

हेईसेई 8 अग॰ 29 को अ 10:09 पर Vik Ramanujam <notifications@github.com> ने लिखा :

**Comment by qw3rtman** [comment]
I agree that finding `n` is no easy task if you Google search `'n'`; however, a Google search for `'n version manager'` (or `'n version'`) or a GitHub search for `'n'` results in this project as the first result. Alternatively, it may be helpful to access [npmjs.com/n](npmjs.com/n) instead.

I'm sorry this was inconvenient for you, but it's a bit late to change the project's name. I hope the above suggestions are helpful. 😄

**Comment by mvoelk** [comment]
I didn't even know that n is a version manager for node and it's really hard to get to the point!

**Comment by shadowspawn** [comment]
This is convenient, assuming you know you are looking for a package named `n`:

```
npm home n 
```
