### ISSUE TITLE
Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by wangzongxu** [tj/n#462]
# Issue Template:

npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/fs'

### Describe issue including what OS you are using

 I'm using MacOS Sierra_

### Describe what version of N you have

When to switch the node version to 7.0.0(npm 5.3.0) and run 'npm install' or 'npm update' or 'npm cache clean' , npm do not work and throw a error Cannot find module 'internal/fs'.
When i switch the node version to 5.0.0(npm 3.3.6) , npm can work again...

**Comment by AntSworD** [comment]
Seems familiar with nodejs/node#9355

**Comment by troy0820** [comment]
Issue closed from merging PR #470.
