### ISSUE TITLE
Version published on NPM does not match latest release on GitHub

### ISSUE THREAD

**Issue by matthew-andrews** [tj/n#468]
```
$ npm cache clean
$ npm uninstall -g n
$ npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
/usr/local/lib
└── n@2.1.8
$ n --version
2.1.7
```

Also you can see here: https://registry.npmjs.org/n/-/n-2.1.8.tgz  — unzip and look in `./bin/n` to see `VERSION="2.1.7"`.  The version in the `package.json` is correct, however.

**Comment by troy0820** [comment]
The latest version is now 2.1.9 on github/npm. Closing.
