### ISSUE TITLE
Put a description that it does not work on Windows

### ISSUE THREAD

**Issue by marcelobart** [tj/n#471]
# Issue Template:

### Describe issue including what OS you are using
I'm using Windows 10

### Describe what version of N you have
Not Applicable

### Describe how you installed N
Not Applicable

### Steps to reproduce issue _1.2.3_
1. Navigate to https://www.npmjs.com/package/n2
2. Not see a description that inform: It does not work on Windows!

### Describe the results you received
"My own flavour of node binary management, no subshells, no profile setup, no convoluted api, just simple."

### Describe the results you expected
"My own flavour of node binary management, no subshells, no profile setup, no convoluted api, just simple. It does not work on Windows!"

### What version of npm you are using
3.10.10

### Additional information you deem important (e.g. issue happens only occasionally):
Not Applicable

**Comment by sikender** [comment]
The description is already there. You are visiting a different package. It is https://www.npmjs.com/package/n instead of https://www.npmjs.com/package/n2 .
