### ISSUE TITLE
Npm not working when I switch to node 0.10.27 from higher node version

### ISSUE THREAD

**Issue by asadman1523** [tj/n#472]
# Issue Template:

### Describe issue including what OS you are using

I'm using Ubuntu 14.01

### Describe what version of N you have
2.1.7

### Describe how you installed N

npm install -g n

### Steps to reproduce issue _1.2.3_

1. sudo n
2. choose  node/9.2.0
3. npm -v   //5.5.1
4. sudo n
5. choose  node/8.2.0
6. npm -v   //5.3.0
7. sudo n
8. choose  node/0.10.27
9. npm -v   //not working

### Describe the results you received

/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:6
let url
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/access.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

### Describe the results you expected

1.4.8
--

### What version of npm you are using

npm not working in 0.10.27

### Additional information you deem important (e.g. issue happens only occasionally):

I need to switch two version of node.  But if I switch to higher version and switch back to 0.10.27, npm will not working.

**Comment by SyXuan** [comment]
remove /usr/local/lib/node_modules/npm
and copy npm directory

fixed here
https://github.com/tj/n/pull/473
https://github.com/tj/n/pull/473/commits/b38739edb15994cfe41c6bd04d47b70cb59be807

**Comment by shadowspawn** [comment]
This issue was hopefully fixed by #470 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
