### ISSUE TITLE
need global and local option like rbenv?

### ISSUE THREAD

**Issue by iamkdev** [tj/n#477]
Can we have `global` and `local` like `rbenv` for ruby.

So that I can keep the latest version as global and local for old projects.

**Comment by Devric** [comment]
this is one work around im start to use, but will be cool to be implemented into N

**Comment by joshuapinter** [comment]
I, too, would love to see this. `rbenv` is such a pleasure to use and is simple enough to understand. It should be emulated as much as possible.

**Comment by shadowspawn** [comment]
`n` is doing a global install of node so there is not a concept of different versions of node for different projects, like there is with `rbenv`.

However, there is a suggestion to add an uninstall option in #540 which readers could subscribe to for updates and/or give a 👍 if it is of interest.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by kissu** [comment]
Damn, I thought that `n` could be somehow like `nvm use 16` but I guess I misunderstood it's usage.
It's only to install a node.js version, not to manage it more than that.

**Comment by shadowspawn** [comment]
Not sure what your comment refers to @kissu . Maybe open a new issue if you want some guidance.
