### ISSUE TITLE
ImportError: No module named Scripting

### ISSUE THREAD

**Issue by aliasone** [tj/n#48]
I've installed 0.6.6 with n and I'm getting this error when trying to build node-serialport. Any ideas?

Traceback (most recent call last):
  File "/opt/local/bin/node-waf", line 14, in <module>
    import Scripting
ImportError: No module named Scripting

node 0.6.6
npm 1.1.0-beta-4

Thanks!

**Comment by DodiyaParth** [comment]
I had same issue, when I tried to run 
`./waf `
When I ran same command using superuser permission
```
sudo su
./waf --run
```
It worked for me
