### ISSUE TITLE
sudo n stable just return Error: invalid version (proxy related)

### ISSUE THREAD

**Issue by howhow** [tj/n#482]
# Issue Template:

### Describe issue including what OS you are using
ubuntu 14.04LTS

### Describe what version of N you have
$n --version
2.1.7

### Describe how you installed N
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

### Steps to reproduce issue _1.2.3_
sudo n stable

### Describe the results you received
$ sudo n stable

  Error: invalid version

### Describe the results you expected
I was supposed to see the lastet being pulled from source_

### What version of npm you are using
$npm --version
1.3.10

### Additional information you deem important (e.g. issue happens only occasionally):
* Output of `which n:`
/usr/local/bin/n

* Output of `node -v:`
nothing

* When I run without sudo:
$n stable

     install : node-v9.2.1
       mkdir : /usr/local/n/versions/node/9.2.1
mkdir: cannot create directory ‘/usr/local/n/versions/node/9.2.1’: Permission denied

  Error: sudo required

**Comment by yeheshuah** [comment]
Have the same problem.

**Comment by nkarri** [comment]
Were you able to resolve it? I'm now having same error.

**Comment by hk1997** [comment]
Hi, I was facing the same issue while running under a proxy connection. Removing proxy settings and running under normal internet solved the issue.

**Comment by ehaliewicz** [comment]
This is expected.  Node isn't stable so they just removed it

**Comment by ankitpatnaik** [comment]
> I had this problem because I had no the environment variables for proxies set for my root user, which prevented the curl command that n uses to download node to work. Setting them fixed the problem.

How did you set them? I'm getting the same issue and I'm not sure how to fix it. I'm using Ubuntu 14.04 VM

**Comment by JohnRGee** [comment]
For proxy issue complications when using sudo:

A  manual work-around is `sudo` has an option to preserve (pass through) your current environment variables:

> -E, --preserve-env
>                 Indicates to the security policy that the user wishes to preserve their existing
>                 environment variables.  The security policy may return an error if the user does
>                 not have permission to preserve the environment.

Curl also reads settings files at various levels, so configuring a settings file is one approach for a permanent solution (albeit I have not tried this). 

Lastly, a different approach is to arrange the ownership or install location so that you do not need to use sudo.

**Comment by shadowspawn** [comment]
Prerelease available via `npm i n@next` for v6. Release notes: https://github.com/tj/n/releases/tag/6.0.0-0

**Comment by shadowspawn** [comment]
Much improved error messages in v6: https://github.com/tj/n/releases/tag/v6.0.0
