### ISSUE TITLE
Feature request: ayo support

### ISSUE THREAD

**Issue by dexamphetamine** [tj/n#483]
A keyword `ayo` argument that directs `n` to download versions of [ayo.js](https://github.com/ayojs/ayo) similar to iojs would be an excellent feature.

**Comment by JohnRGee** [comment]
There are not any releases listed on github for ayo, and the download section in the README says `To be written`. No versions to manage currently?

**Comment by dexamphetamine** [comment]
Ah, ok. Thanks for taking a look!
