### ISSUE TITLE
How do I switch NPM versions?

### ISSUE THREAD

**Issue by typemismatch** [tj/n#484]
### Downgrade NPM version

I need NPM < 5.x for support with React Native, I can switch node just fine but I can't seem to downgrade NPM.

**Comment by JohnRGee** [comment]
`n` installs the version of npm bundled with node as part of the node install. If you need a different version of npm, then downgrading (or upgrading) npm from the bundled npm version is a separate command. e.g.

`npm install -g npm@5.4.0`

When you switch node versions using `n`, you need to reinstall the desired npm version again.

**Comment by scottsword** [comment]
@JohnRGee To be clear, you shouldn't have to re-install a version of npm every time you switch node versions. Once you install a different version of npm than the one that shipped with that node version it should remain in place *for that version*. So if you switch from node 6 to 8 you won't get the npm version that you installed locally to 6, but when you go back to 6 it won't reset the version of npm to the version it was originally bundled with (assuming you changes the version of npm in node 6 e.g. 3 => 5).

**Comment by scottsword** [comment]
This should be closed.

**Comment by jeffora** [comment]
@scottsword I'm not seeing this behaviour. Switching between two different versions of node 6, I get npm@3.10.10 every time, even after installing npm@latest (5.7.1) in both versions of node. If the expected behaviour is that npm global installs persist, is this a bug?

**Comment by scottsword** [comment]
@jeffora when you install something globally in node its "global" to that particular installation of node. Thats all I was saying. Sounds like you have similar major versions that ship with the same base npm version.

**Comment by AndersonZacharyT** [comment]
Ok, I tried `omgaz` script with no luck. I seem to be stuck on npm@6, but I need npm@5. I got stuck on 6 after using `n` to switch from node 8 to node 10.

It looks like the only `npm` in my path is in `~/.npm-global` which seems ideal... `npm i -g npm@5.6.0` has no effect, as `npm -v` still returns `6.4.0`

Any ideas?

**Comment by shadowspawn** [comment]
@AndersonZacharyT we can hopefully work out your problem from scratch. 

If the version of npm does not change when you run

```
npm install --global npm@latest
```

then the location it is installing to is not replacing the active version of npm. Likewise if using `n` to install new node does not also change `npm`, then it is going to a different location.

What are:

```
command -v npm
npm prefix --global
echo $N_PREFIX
```

**Comment by shadowspawn** [comment]
`--preserve` added in v6.3.0 to preserve the version of npm when installing.
