### ISSUE TITLE
Desktop shortcuts or hotkey commands for global node apps installed via n (Linux)

### ISSUE THREAD

**Issue by drschwabe** [tj/n#487]
Having difficulty getting my system to run any shortcuts for global node apps installed via n

In a nutshell, you can't create a desktop shortcut to run a global node app 
(without some solution, for which maybe we can pinpoint in this thread)

For example, I have electron installed so to launch it from terminal I can type `electron`

But if I create a desktop shortcut entry or try to use Ubuntu's built in custom shortcuts feature (available in Keyboard settings) and specify 'electron' as the command to execute for SUPER+E nothing happens. 

Also tried creating a bash script which executes / opens electron fine if executed from terminal but again from desktop shortcut or custom hotkey that script won't execute - I presume the bash script / command needs some additional settings to reproduce how n integrates with terminal.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
