### ISSUE TITLE
pin npm version when switching node versions

### ISSUE THREAD

**Issue by reviewher** [tj/n#488]
`npm` 5.x have been causing issues with various modules, so locally I force `npm` 4.3.0.  Every time I switch to node 8 or 9 it installs some `npm` 5 version.  Is there a way to switch node versions with `n` without touching the current `npm` version?

**Comment by JohnRGee** [comment]
`n` installs the version of `npm` bundled with `node`. There is not current a way to disable this.

(Discussed in #210.)

**Comment by JohnRGee** [comment]
Implementation speculation: excluding npm might be reasonably straightforward if the install was done using rsync (using --exclude) rather than cp, but not sure about how compatible that would be.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
I have added support for preserving npm in [nvh](https://github.com/shadowspawn/nvh) if any readers would like to give it a try. (It was made possible by switching to rsync for the install and so can't be brought back to n.)

**Comment by shadowspawn** [comment]
`--preserve` added in `n` v6.3.0 to preserve the version of npm when installing node.
