### ISSUE TITLE
Installation of new version fails "dyld: Symbol not found"

### ISSUE THREAD

**Issue by petrgazarov** [tj/n#490]
Hi there, after I installed anaconda python using brew, `n` stopped working. Any ideas appreciated.

### Describe issue including what OS you are using

I'm using MacOS Sierra 10.12.5 

### Describe what version of N you have
2.1.7

### Describe how you installed N
Via `yarn`, previously tried with `brew` with same result

### Steps to reproduce issue
- install anaconda distribution of python
- this breaks n
- E.g. `n <version previously not installed on the machine>` doesn't work

### Describe the results you received
Running `n <version previously not installed on the machine>` produces the following output:
```

     install : node-v6.9.5
dyld: lazy symbol binding failed: Symbol not found: _SSL_CTX_set_alpn_protos
  Referenced from: /Users/petrgazarov/anaconda3/bin/../lib/libcurl.4.dylib
  Expected in: /Users/petrgazarov/anaconda3/bin/../lib/libssl.1.0.0.dylib

dyld: Symbol not found: _SSL_CTX_set_alpn_protos
  Referenced from: /Users/petrgazarov/anaconda3/bin/../lib/libcurl.4.dylib
  Expected in: /Users/petrgazarov/anaconda3/bin/../lib/libssl.1.0.0.dylib

dyld: lazy symbol binding failed: Symbol not found: _SSL_CTX_set_alpn_protos
  Referenced from: /Users/petrgazarov/anaconda3/bin/../lib/libcurl.4.dylib
  Expected in: /Users/petrgazarov/anaconda3/bin/../lib/libssl.1.0.0.dylib

dyld: Symbol not found: _SSL_CTX_set_alpn_protos
  Referenced from: /Users/petrgazarov/anaconda3/bin/../lib/libcurl.4.dylib
  Expected in: /Users/petrgazarov/anaconda3/bin/../lib/libssl.1.0.0.dylib

dyld: lazy symbol binding failed: Symbol not found: _SSL_CTX_set_alpn_protos
  Referenced from: /Users/petrgazarov/anaconda3/bin/../lib/libcurl.4.dylib
  Expected in: /Users/petrgazarov/anaconda3/bin/../lib/libssl.1.0.0.dylib

dyld: Symbol not found: _SSL_CTX_set_alpn_protos
  Referenced from: /Users/petrgazarov/anaconda3/bin/../lib/libcurl.4.dylib
  Expected in: /Users/petrgazarov/anaconda3/bin/../lib/libssl.1.0.0.dylib

  Error: invalid version 6.9.5
```

### Describe the results you expected
The version gets installed successfully

### What version of npm you are using
npm version 5.5.1
yarn version 0.27.5

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:`
`/usr/local/bin/n`

* Output of `node -v:`
`v8.9.0`

* Output of `n ls`
```
dyld: Library not loaded: /usr/local/opt/mpfr/lib/libmpfr.4.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
```

* Output of `n io ls`
```
dyld: Library not loaded: /usr/local/opt/mpfr/lib/libmpfr.4.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
```

**Comment by coolkat64** [comment]
Hey ! Having the same issue, there seem to be a major problem involving nvm, npm, anaconda and xcode. All 4 are showing countless issues and fixing one creates more. I can't even uninstall everything and start again because they just won't, but then they don't work anymore. 

This is now a rage thread.

**Comment by JohnRGee** [comment]
`anaconda` and `brew` can both install different versions of system tools. 

The first error looks like it is coming from `curl`, and the second error looks like coming from `awk`, both of which are called by `n`. You can do a simple check whether those two tools are still even working with `curl --version` and `awk --version`, and where they are installed using `which -a curl` and `which -a awk`. The original system ones are in `/usr/bin`.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
