### ISSUE TITLE
No effect switching to lower version on ubuntu 16

### ISSUE THREAD

**Issue by eldyvoon** [tj/n#495]
# Issue Template:

### Describe issue including what OS you are using
I'm using Ubuntu 16 LTS

### Describe what version of N you have
I'm using n version 2.1.7

### Describe how you installed N

npm install -g n

### Steps to reproduce issue _1.2.3_
_i.e._
1. sudo n 6.9.2

### Describe the results you received

Nothing

### Describe the results you expected

I was supposed to see the node version has been downgraded

### What version of npm you are using

npm --version output: 5.5.1

## extra notes
When I do `sudo n use 6.9.2 I got `node/6.9.2`. I try to select it but when I do `node -v` I still see higher version. I guess 6.9.2 is been install but the switching seems broken.

**Comment by JohnRGee** [comment]
Perhaps there is more than one copy of node installed, and just typing `node` is not running the one managed by `n`. Try
`which -a node`
to see the locations for `node` with your path.
