### ISSUE TITLE
feature request: `n -`

### ISSUE THREAD

**Issue by ycmjason** [tj/n#496]
I am switching between two different version of node frequently and would be nice if there is some command like `n -` which switches to the previous node version.

Prior art:
- `cd -` 
- `git checkout -`
...

**Comment by JohnRGee** [comment]
This has been discussed in past, and in fact matching functionality was removed at that time.
See  #184

**Comment by ycmjason** [comment]
I just happened to worked with something where I need to switch between two versions very often. That's why I suggested this. 

To be fair tho, I probably won't be using it that much too and doing `n 8`, `n 6` isn't a lot harder. I will close this then if this is not something that will be considered! 😄
