### ISSUE TITLE
Wrong order with node/10.0.0

### ISSUE THREAD

**Issue by cedric25** [tj/n#497]
### Describe issue including what OS you are using
I'm using macOS High Sierra

### Describe what version of N you have
n --version output: 2.1.7

### Describe how you installed N
npm install -g n

### Steps to reproduce issue
1. `n latest` which would install node/10.0.0 at the time of writing
2. Install other versions, ex: `n 8.5.0` and `n 9.9.0`
3. List installed versions: `n`

### Describe the results you received
```
node/10.0.0
node/8.5.0
node/9.9.0
```

### Describe the results you expected
node/10.0.0 to be at the end:
```
node/8.5.0
node/9.9.0
node/10.0.0
```

### What version of npm you are using
npm --version output: 8.5.0

### Additional information you deem important

Sort is happening in `versions_paths()`.
I got the expected result with
`sort -k 1,1 -k 2,2n -t /`
instead of
`sort -k 1,1 -k 2,2n -k 3,3n -t .`
(Split on `/` instead of `.`)
But I haven't tested all possible use-cases...

**Comment by troy0820** [comment]
Closing issue from merged in PR #498
