### ISSUE TITLE
can't install n

### ISSUE THREAD

**Issue by thesixonenine** [tj/n#500]
I'm using MacOS Sierra
I want install n like this: npm install -g n,  but it's not work

Simple:~ simple$ npm install -g n
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "n"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path /usr/local/bin/n
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/usr/local/bin/n'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/usr/local/bin/n']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/local/bin/n' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, unlink '/usr/local/bin/n'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, unlink '/usr/local/bin/n']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: '/usr/local/bin/n' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/simple/npm-debug.log

and I also use this: sudo npm install -g n, it's not work too:

Simple:~ simple$ sudo npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "n"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@3.10.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer webpack-dev-server@1.16.5 wants webpack@>=1.3.0 <3

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/simple/npm-debug.log

Simple:~ simple$ npm -v
2.15.8
Simple:~ simple$ node -v
v4.4.7

plz help me, thank you!

**Comment by troy0820** [comment]
The first command doesn't work because you don't have permission to install in that location _(chown directory will fix that or using sudo)_

It looks like it linked it in the `sudo npm install -g n` command. 
I'm more interested in this:
```
Simple:~ simple$ sudo npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "n"
npm ERR! node v4.4.7
npm ERR! npm v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@3.10.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer webpack-dev-server@1.16.5 wants webpack@>=1.3.0 <3

npm ERR! Please include the following file with any support request:
npm ERR! /Users/simple/npm-debug.log
``` 
It looks like webpack doesn't like something.  Did you try to `n latest` to see if the install worked? 

It also looks like you already have node installed which is a requirement of this.  

Can you do a `which node` so I can see the install location?  
_Please use the issue template provided, it helps tremendously_

**Comment by thesixonenine** [comment]
thank you!

The output of these two commands looks like this:

Simple:~ simple$ n latest
mkdir: /usr/local/n/versions/node: Permission denied
mkdir: /usr/local/n/versions/io: Permission denied

     install : node-v10.0.0
       mkdir : /usr/local/n/versions/node/10.0.0
mkdir: /usr/local/n/versions/node/10.0.0: Permission denied

  Error: sudo required

Simple:~ simple$ sudo n latest
Password:

     install : node-v10.0.0
       mkdir : /usr/local/n/versions/node/10.0.0
       fetch : https://nodejs.org/dist/v10.0.0/node-v10.0.0-darwin-x64.tar.gz
###                                                                        4.9%^C
Simple:~ simple$ which node
/usr/local/bin/node


Should I use 'sudo n latest' to update the node's version?

**Comment by troy0820** [comment]
That should get you the latest node version currently at v10.0.0.
