### ISSUE TITLE
Feature Request: Add proxy support (for many of us behind the firewall)

### ISSUE THREAD

**Issue by stsvilik** [tj/n#503]
Would it be possible to add an option to specify a proxy when running `n`. You already doing it for `$HTTP_USER` and `$HTTP_PASSWORD`, so just need to extend `curl` params to accept `HTTP(s)_PROXY` as well.

Please :)

**Comment by JohnRGee** [comment]
You may be able to use an environment variable recognised by `curl`, without changes in `n`? 

Either `https_proxy` or `HTTPS_PROXY`, depending on your implementation.

e.g. [How to use curl command with proxy username/password on Linux/ Unix](https://www.cyberciti.biz/faq/linux-unix-curl-command-with-proxy-username-password-http-options/)

**Comment by stsvilik** [comment]
@JohnRGee I have those set in my environment - still no luck. Additionally my company uses middle-man certificate which requires me to ignore security when I use `curl`. Maybe a way to go about it is to have an optional configuration file for `n` (ex. `.nrc`) where such nuances could be configured?

**Comment by JohnRGee** [comment]
I was wondering about certificates too as that seemed likely to be next problem! 
#324 #426

**Comment by JohnRGee** [comment]
You may be able to use http for the traffic to the proxy, and avoid dealing with the middle-man certificate. In the examples my proxy server is `localhost:3128`. The default for curl is to use http to the proxy server and I am explicitly specifying that to make it clear that not using https for that part of the connection.

Using `curl` so you can see error messages if it fails, success looks like:

```bash
$ https_proxy='http://username:password@localhost:3128' curl --head https://nodejs.org/dist/
HTTP/1.1 200 Connection established
...
```

If that works then hopefully `n` does too:
```bash
https_proxy='http://username:password@localhost:3128' n ls
```

Tip: if you are using `sudo` for the install then it does not get your environment variables by default, and `sudo -E` preserves (passes) the environment variables.

**Comment by stsvilik** [comment]
Unfortunately, neither `sudo -E n ls` nor explicitly setting proxy env in-line worked.
`curl` command only works like this `curl -k -x http://some.proxy.com:80 --head https://nodejs.org/dist/`

**Comment by JohnRGee** [comment]
Thanks for info and example `curl` command. I understand possibilities better now.

A last question. Does a connection to the nodejs mirror on `http` work? e.g.

```bash
curl -x http://some.proxy.com:80 --head http://nodejs.org/dist/
http_proxy=http://some.proxy.com:80 NODE_MIRROR=http://nodejs.org/dist/ n ls
```

**Comment by stsvilik** [comment]
Well, above example doesn't work for me, and I think that could be due to `.curlrc` file which sets our proxy. Unfortunately I can't just unset it since it is used in all other curl operations used by misc. scripts such as NPM itself. I also decided to dump in here a version of curl installed on my Mac just in case.

```
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
```

**Comment by JohnRGee** [comment]
You have a `.curlrc` file? Oh! Well that explains why more is going on than just the command line. 

The call that `n` makes to curl when you run `n ls` looks like this assuming you have not defined a custom mirror, and ideally we want it to run without needing to change it:

    curl -L -# http://nodejs.org/dist/

You said earlier this worked:

    curl -k -x http://some.proxy.com:80 --head https://nodejs.org/dist/

which suggest that the certificate check is a problem. Do you have a line with `-k` or `--insecure` in your `.curlrc` file to disable the certificate checks?

https://ec.haxx.se/cmdline-configfile.html

**Comment by stsvilik** [comment]
My `.curlrc` only has `proxy`, nothing else.

**Comment by JohnRGee** [comment]
Try adding a new line to your `.curlrc` with:

    --insecure

and then running:

    curl -L -# http://nodejs.org/dist/

**Comment by stsvilik** [comment]
Nope, tried with both `--insecure`/`insecure` in `.curlrc`, but above doesn't work. Explicitly setting proxy with `-x` works though.

**Comment by JohnRGee** [comment]
You can so the same things with command-line options as with `.curlrc`, so can hopefully narrow down the settings you need to work with `n`. 

If you want more advice here then I suggest looking at differences between proxy on command line vs proxy in your `.curlrc` settings, and supply an example of the failing command you are running and the verbose output. (I use Mac with same version of curl, but there are so many proxy possibilities...)

Two `curl` options which will be useful for exploring failures and differences between success and failure are as follows. The `-q` will be useful for running `curl` commands with options on the command line without `.curlrc` involved, and `-v` for seeing more of what is going on.

    -q, --disable
        If used as the first parameter on the command line, the curlrc config file will 
        not be read  and  used. ...

    -v, --verbose
        Makes  curl  verbose  during  the operation. Useful for debugging and seeing 
        what's going on "under the hood". ...

One paranoid thing to watch out for is environment variables left over from previous attempts.
Check whether you have any proxy settings in the environment variables:

    env

**Comment by stsvilik** [comment]
It turned out to be an issue with tinyproxy which stood between actual external proxy :/
