### ISSUE TITLE
latest stable? 2.1.10 or 2.1.11

### ISSUE THREAD

**Issue by ilovezfs** [tj/n#505]
I cannot tell based on
https://github.com/tj/n/releases/latest
and
https://github.com/tj/n/releases

**Comment by troy0820** [comment]
The release wasn’t published but the latest is 2.1.11 which is on npm.

**Comment by ilovezfs** [comment]
Thanks @troy0820! Volà https://github.com/Homebrew/homebrew-core/pull/28039
