### ISSUE TITLE
Incorrect sorting with Node@10.1.0

### ISSUE THREAD

**Issue by artemgurzhii** [tj/n#506]
# Issue Template:

### Describe issue including what OS you are using
I'm using MacOS Sierra

### Describe what version of N you have
`2.1.7`

### Steps to reproduce issue
1. n latest

### Describe the results you received
```bash
    node/10.1.0
  ο node/6.11.3
    node/7.7.1
    node/8.7.0
    node/9.2.1
```

### Describe the results you expected
```bash
  ο node/6.11.3
    node/7.7.1
    node/8.7.0
    node/9.2.1
    node/10.1.0
```

**Comment by troy0820** [comment]
Upgrade to the latest version of n, `2.1.11`.  The sorting was an issue.

**Comment by troy0820** [comment]
Did that solve your issue @artemgurzhii ?

**Comment by artemgurzhii** [comment]
@troy0820 Yes, everything is working great! Thank you for your help, and sorry for taking your time)

**Comment by troy0820** [comment]
Not a problem. Thanks for closing the issue.
