### ISSUE TITLE
Taking a long time to switch between node versions

### ISSUE THREAD

**Issue by kirisu** [tj/n#520]
# Issue Template:

### Describe issue including what OS you are using
macOS High Sierra

### Describe what version of N you have
2.1.11

### Describe how you installed N

Homebrew

### Steps to reproduce issue _1.2.3_
1. Switch from any version of node to another

### Describe the results you received
It can take over a minute to switch between versions.

### Describe the results you expected
It shouldn't take as long.

### What version of npm you are using
6.1.0

### Additional information you deem important (e.g. issue happens only occasionally):
I'm using zsh, I don't know if that is an issue. MacBook specs:

MacBook Pro (Retina, 15-inch, Late 2013)
2.6 GHz Intel Core i7
6 GB 1600 MHz DDR3

**Comment by JohnRGee** [comment]
Do you have anti-virus software running?

`n` is using a fairly straight forward `cp` command, but there are around 5000 files. I recently had the same problem with the first install of (switch to) a version taking over a minute and the second install running ok. I was able to narrow it down to the anti-virus software, which with the real-time monitoring active, made the install run 20 times slower. I could reproduce the issue without `n` involved by copying one of the downloaded folders to my desktop in the Finder and seeing a similar slowdown.

**Comment by kirisu** [comment]
Damn. That looks like what's causing it. It is a company laptop, and the antivirus policy is enforced by the network so I can't turn it off permanently, but doing so temporarily seems to improve the situation. I guess I'll just have to deal with it.
