### ISSUE TITLE
Suggested terminology changes

### ISSUE THREAD

**Issue by mklement0** [tj/n#522]
Now that Node.js distinguishes only between _LTS_ and _Current_:

* Consider supporting version spec. `current` as an alias of `latest` and documenting `current` as the preferred form going forward.

* Consider deprecating `stable` and treating it as an alias of `lts`.

* Consider replacing references to "current" in the CLI help with "active" or similar, to avoid confusion:

   *   ` n prune                        Remove all versions except the current version` ->
         `n prune                        Remove all Node.js versions except the active one`

  *  ` -V, --version   Output current version of n` ->  
      `-V, --version   Output n's version number`

**Comment by shadowspawn** [comment]
I have updated help output in v4.0.0 along lines suggested. Have not added current as alias for latest at this time. Stable deprecated. (But just noticed still used once in the n-install instructions! I'll fix that for next release.)

Thank you  for your contributions.
