### ISSUE TITLE
load specific node version

### ISSUE THREAD

**Issue by dtuyenle** [tj/n#523]
How do I load a specific node version ? Documentation is so poorly written.

**Comment by troy0820** [comment]
`n lts` will give you the latest `lts` version.  If you want a specific version, you would install it by entering `n <version number>` in your terminal.

**Comment by JohnRGee** [comment]
A concrete example of what Troy said: 
`n 4.9.1`

**Comment by dtuyenle** [comment]
This issue was related to https://github.com/tj/n/issues/400 Turned out I have nvm running .....  Just need to run `nvm use system` Closing now
