### ISSUE TITLE
n latest works but n io latest fail with cp: cannot stat

### ISSUE THREAD

**Issue by zfields** [tj/n#527]
Similar to previous issue #298...

`sudo n latest`

Failed on first try with `cp: cannot stat ...`, but then succeeds on second attempt.

Ubuntu 16.04
`n` version 2.1.3

**Comment by JohnRGee** [comment]
To clarify what is happening:
1)  Are you running `sudo n latest`? (Or `n io latest`? It looks like you may have copied the previous issue title and it might not match what you are doing.)
2) What is the full error message including the file path after the `stat`?
3) Can you reproduce this problem? (Or was it a once off?)

**Comment by zfields** [comment]
It happened the first time and not the second time. I was running `sudo n latest`, and I cannot reproduce, because it worked the second time.

**Comment by JohnRGee** [comment]
I have seen the `stat` errors with `n` when a download of a node version has failed after a cache folder got created for it but before the downloaded tarball was unpacked. The implementation detail is that while `/usr/local/n/versions/node/x.y.z` folder exists, the subfolders for `bin` and `include` and `lib` and `share` are not present and you get errors when `n` tries to copy the missing folders.

If you were still having problems with a specific version then I would suggest deleting that version, but you have got past that issue.

If it does not happen again when you try changing to a new version then hopefully it was a one-off problem and not a systematic problem.

**Comment by zfields** [comment]
Seems to be a transient error, but I thought I would report it. Everything is working now.

To be clear I tried the exact same steps two times and it "worked" the second time.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
