### ISSUE TITLE
I hope there would be a de-star... a shit

### ISSUE THREAD

**Issue by vishalvisd** [tj/n#530]
# Issue Template:

### Describe issue including what OS you are using

_i.e. I'm using MacOS Sierra_

### Describe what version of N you have
_i.e. n --version output: 2.1.4_

### Describe how you installed N

* _i.e. npm install -g n_
* _i.e. make install_

### Steps to reproduce issue _1.2.3_
_i.e._
1. n latest
2. couldn't pull latest from source

### Describe the results you received

_i.e. blank screen_
### Describe the results you expected

_i.e. I was supposed to see the latest being pulled from source_

### What version of npm you are using

_i.e. npm --version output: 4.0.5_

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:`
* Output of `node -v:`

**Comment by JohnRGee** [comment]
Please change the title to something appropriate to your issue.

A couple of ideas:

1) `n` does not produce any extra output if the requested version of node is already active, so one possibility is that latest was already installed. In any case though, just looking up the version is a useful test of whether that part of the code is working. e.g.

```bash
    $ n --latest 
    10.12.0
```

Does this produce any output for you?

2) There are a variety of ways things can fail if there are proxy issues. A simple manual check is to run a curl command similar to what `n` does. e.g.

```bash
$ curl --head https://nodejs.org/dist/
HTTP/2 200 
```

Do you see a 200 status code, or an error, or a hang?

**Comment by troy0820** [comment]
This doesn't seem like it's an issue.
