### ISSUE TITLE
Allow a group of users to install and switch node version

### ISSUE THREAD

**Issue by pelomedusa** [tj/n#537]
### Describe issue including what OS you are using
Debian 9 Stretch

### Describe what version of N you have
2.1.12

### Describe how you installed N
make install

I would like allow a group of users, let's say `nusers` to install and use different versions of node.The users do not need to user separate versions.. Right now i have to use sudo but i would like to get rid of this. How should i proceed?

Thanks

**Comment by JohnRGee** [comment]
You can use `N_PREFIX` to define the node install location (and add `${N_PREFIX}/bin` to `PATH`). 

You could define a user separate location in home directory, say `~/n`.

Or you could set up a shared node install location with write permissions for the group, say `/usr/local/nusers`.

**Comment by pelomedusa** [comment]
Ok il will try this thank you

**Comment by shadowspawn** [comment]
This issue has not had any activity in a few months.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
An addendum. Maintaining group-write for a shared install folder is complicated by the `npm` folder being deleted and recreated as part of the install, as mentioned in #610
