### ISSUE TITLE
Unusual installation method

### ISSUE THREAD

**Issue by cn-src** [tj/n#538]
# Issue Template:

### Describe issue including what OS you are using
I'm using MacOS Mojave 10.14.1

### Describe what version of N you have
n --version output: 2.1.12

### Describe how you installed N
npm install -g n

I config `export N_PREFIX=$HOME/.config`

And, brew install node with v11.2.0

```
➜  ~ n lts

     install : node-v10.13.0
       mkdir : /Users/blue/.config/n/versions/node/10.13.0
       fetch : https://nodejs.org/dist/v10.13.0/node-v10.13.0-darwin-x64.tar.gz
####################################################################################################################################################### 100.0%
   installed : v11.2.0
```

```
➜  ~ sudo n lts
Password:

     install : node-v10.13.0
       mkdir : /usr/local/n/versions/node/10.13.0
       fetch : https://nodejs.org/dist/v10.13.0/node-v10.13.0-darwin-x64.tar.gz
####################################################################################################################################################### 100.0%
   installed : v10.13.0
```

I must use 'sudo'  to work properly.

And, it will ignore the configuration 'N_PREFIX'.

**Comment by JohnRGee** [comment]
1) Without sudo: I expect you also need to add `$N_PREFIX/bin` to the start of your PATH to have the `n` managed version of node found before the one you installed with brew. 

In your first example I think `n lts` is copying node v10.13.0 into your home folder, but then when it runs node after the install it is finding the brew installed version in `/usr/local/bin` so reports that node v11.2.0 is installed.

You can run `which -a node` to see if you have more than version of node in your PATH and where they are installed.

2) With sudo: by default environment variables like `N_PREFIX` are not copied to the sudo environment. (See `man sudo`)

In your second example `sudo n lts` is using the default install location of `/usr/local` and overwriting the version installed by brew.

If you ran `sudo -E n lts` it would preserve the existing environment variables, but part of the point of installing to your home folder is to stay away from using `sudo`, so this is probably not what you want to do.

3) Unless you need two versions of node installed, it is simpler to have just one so you could uninstall or delete the version in `/usr/local/bin`.

**Comment by cn-src** [comment]
Thank you. 
Add $N_PREFIX/bin to PATH solved my problem.
