### ISSUE TITLE
Prune not working

### ISSUE THREAD

**Issue by atulmy** [tj/n#539]
OS: macOS Mojave

Version of N you have: 2.1.3

### Steps to reproduce issue
`n prune`

### Describe the results you received
`Error: invalid version prune`

### Describe the results you expected
Remove all versions except the current version.

### What version of npm you are using: 6.4.1

* Output of `which n:` 2.1.3
* Output of `node -v:` v10.14.0

<img width="253" alt="screenshot 2018-11-28 at 7 11 53 pm" src="https://user-images.githubusercontent.com/685786/49155827-e7ab7f00-f341-11e8-9fdd-ba44a1aed18c.png">

**Comment by JohnRGee** [comment]
The prune command got added in `n` v2.1.7 and the current version is v2.1.12, so you need to update if you want the `prune command.

**Comment by atulmy** [comment]
Unable to update `n` to the latest version:
`npm update -g n`

```
n --version         
2.1.12
```
