### ISSUE TITLE
Feature suggestion: n uninstall

### ISSUE THREAD

**Issue by shadowspawn** [tj/n#540]
# Suggestion

I propose `n uninstall` removes the active version of node and npm installed by `n`. e.g. for default install location:
- rm -f /usr/local/bin/node
- rm -f /usr/local/bin/npm
- rm -f /usr/local/bin/npx
- et al

I think this would be useful in various scenarios:
- temporarily reverting to a system install of node (assuming one exists)
- deleting node and npm because no longer using
- cleaning out `n` installed node and npm because trying another way of managing them
- cleaning out node and npm because broken, before trying a different install

# History

This has come up multiple times. See #127 #169 PR #173 #238 #327 #441 #486

Three different things often get discussed or mixed together: uninstalling `n`, uninstalling the active version of node, and deleting the downloaded cached versions of node. I am suggesting `n uninstall` only does the middle case as they are useful separate operations and there are already simple commands for doing the other two flavours:
- uninstall `n`: e.g. `npm uninstall -g n`
- remove cached downloaded versions: e.g. `n prune` (all but one) or `rm -rf /usr/local/n`(all)

On a related note, the third party installer [n-install](https://github.com/mklement0/n-install) has `n-uninstall` which does all three uninstall cases at once.

Other syntax considered, but I didn't like as much as uninstall:
- `n system` (#486 #169)
- `n none` (PR #173)

# Uninstall References and Implementation

Personally I initially didn't like the idea of implementing this because `n` installs using the nodejs distribution and does not use much specific knowledge of the layout. But it is a commonly requested feature, and it is a bit of a pain to delete manually. Two example links are:
- https://docs.npmjs.com/misc/removing-npm
- https://stackabuse.com/how-to-uninstall-node-js-from-mac-osx/

I propose the implementation should use fixed knowledge of the target locations rather than consult a particular cached version, not least because you are likely to have installed multiple versions over time, and may have deleted the cached version.

I propose the implementation only deletes the files and folders `n` may have installed, and not other related things like global npm and node modules. I think just undoing the things that `n` was used for  is simpler and safer.

**Comment by JohnRGee** [comment]
Proposed uninstall steps for default install to `/usr/local`:

```bash
rm -f "/usr/local/bin/node"
rm -f "/usr/local/bin/npm"
rm -f "/usr/local/bin/npx"
rm -rf "/usr/local/include/node"
rm -rf  "/usr/local/lib/dtrace/node.d"
rm -rf "/usr/local/lib/node_modules/npm"
rm -rf "/usr/local/share/doc/node"
rm -rf "/usr/local/share/man/man1/node.1"
rm -rf "/usr/local/share/systemtap/tapset/node.stp"
```

**Comment by FranklinYu** [comment]
How about `/usr/local/n/`?

**Comment by shadowspawn** [comment]
@FranklinYu 
Thanks. I deliberately left that out. See the History section in my first comment.

**Comment by FranklinYu** [comment]
The typo was why I asked. Nevertheless, `rm -rf /usr/local/n` isn’t a simple command. It is only as simple as any command in your proposal.

**Comment by shadowspawn** [comment]
Added in v4.1.0
