### ISSUE TITLE
sudo n not preserving installed node permissions

### ISSUE THREAD

**Issue by denisharder** [tj/n#550]
# Issue Template:

### Describe issue including what OS you are using
My environment is Redhat 7.3/7.4. The default behaviour within this OS on a 'sudo cp' cmd seems to remove the world permissions on the target. This is resulting in npm not being available to a regular user after a sudo n version switch. The specific lines of code in question are in the activate() function w/ the cp commands.

#### Example:
After running 'sudo n latest' under a normal user, n will install the npm version with world read/execute under the n versions folder. But when the npm folders are copied to /usr/local/lib directory, the world read/execute permission is removed.

Installed npm has appropriate r/x world permissions...
```
testuser@rhel73base ~ $ sudo ls -l /usr/local/n/versions/node/11.6.0/lib/node_modules/
total 4
drwxrwxr-x 10 500 security 4096 Dec 26 01:09 npm
```

Copied node has removed r/x world permissions...
```
testuser@rhel73base ~ $ sudo ls -l /usr/local/lib/node_modules/
total 4
drwxr-x--- 10 root root 4096 Jan 16 21:56 npm
```

Normal user trying to execute npm gets error (since npm is not world r/x)...
```
testuser@rhel73base ~ $ npm --version
bash: npm: command not found...
```

### Describe what version of N you have
```
testuser@rhel73base ~ $ n --version
2.1.12
```

### Describe how you installed N
```
sudo -i
git clone --branch v2.1.12 https://github.com/tj/n.git /tmp/n
PREFIX=/usr make --directory=/tmp/n install
rm -rf /tmp/n
```

### Steps to reproduce issue _1.2.3_
Under normal user, run...
sudo n latest
npm --version

### Describe the results you received
Under normal user, unable to run npm (since it is not world r/x).

### What version of npm you are using
6.5.0-next.0

### Additional information you deem important (e.g. issue happens only occasionally):

If i update the n source code to preserve the installed node permissions during the copy (i.e., --preserve=mode) this issue is resolved for me...
```
activate() {
  ...
    # Copy (lib before bin to avoid error messages on Darwin when cp over dangling link)
    for subdir in lib bin include share; do
      if test -L "$N_PREFIX/$subdir"; then
        find "$dir/$subdir" -mindepth 1 -maxdepth 1 -exec cp -fR --preserve=mode "{}" "$N_PREFIX/$subdir" \;
      else
        cp -fR --preserve=mode "$dir/$subdir" $N_PREFIX
      ...
}
```

After updating above, and executing 'sudo n latest', the npm permissions are correct...
```
testuser@rhel73base ~ $ sudo ls -l /usr/local/lib/node_modules/
total 4
drwxrwxr-x 10 root root 4096 Jan 16 22:11 npm

testuser@rhel73base ~ $ npm --version
6.5.0-next.0
```

**Comment by JohnRGee** [comment]
I don't see this problem spinning up a docker container with default settings. Do you have a restrictive umask set? I was testing with default mask:

```bash
$ docker run -it --rm centos:latest umask
0022
```


----
`cp -fR` does leave permissions open to being affected by mask. I did reproduce the problem by setting umask first to remove execute permissions.

`--preserve=[mode]` is not supported on Mac with bash v3. However, `-p` (preserve) and `-a` (archive) seem to be available on both Mac and Centos.

**Comment by denisharder** [comment]
Thank you, that was it... I did not have this issue with centos either, but after looking into my sudoers file on redhat, the umask was indeed set (probably by the system admin). I think it makes sense for n to follow the guidelines set by the system. Thanks again!
```
Defaults umask=027
```

**Comment by JohnRGee** [comment]
Good! And thanks for the details and digging in your report.
