### ISSUE TITLE
Making n work on Windows

### ISSUE THREAD

**Issue by Chrisstar56** [tj/n#552]
I'm not advanced enough to make this work, but wouldn't it be an alternative for windows users, to just download the correct binary and run it for the user?

**Comment by JohnRGee** [comment]
Do you mean running the full Windows native installer for node, rather than downloading the archive with the prebuilt binary? I think that is different enough from the normal workflow for `n` that probably not going to fit into `n`.

**Comment by shadowspawn** [comment]
This issue has not had any activity in a couple of months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
