### ISSUE TITLE
PR: Will add nightly chakra and others

### ISSUE THREAD

**Issue by frank-dspeed** [tj/n#553]
https://github.com/tj/n/issues/378
https://github.com/JohnRGee/nvh/
https://github.com/tj/n/issues/376
https://github.com/tj/n/issues/376#issuecomment-250876666

**Comment by frank-dspeed** [comment]
will base on existing closed PR https://github.com/tj/n/pull/388/commits/2f854b7680947291a69a8effc9b9b0e9bd0cc42f

**Comment by shadowspawn** [comment]
FYI: I am going to look to switch to using `index.tab` for version information, before considering adding nightly/chakara-core et al.

**Comment by shadowspawn** [comment]
Have open issues for nightly #376 and ChakraCore #480
