### ISSUE TITLE
PR: Will add tests via travis-ci 

### ISSUE THREAD

**Issue by frank-dspeed** [tj/n#554]
Closing: #545

**Comment by JohnRGee** [comment]
In case you hadn't seen it, I suggested adding tests in #545, and work  in progress available in https://github.com/JohnRGee/n-test

**Comment by frank-dspeed** [comment]
@JohnRGee i saw your effort but i think its the wrong way probally i will come up with something better your work in progress gave me indeed the idea to raise this PR here :D

**Comment by frank-dspeed** [comment]
PR: #555

**Comment by frank-dspeed** [comment]
Please look also into #556

**Comment by shadowspawn** [comment]
Going with #545 approach.
