### ISSUE TITLE
Installation of macports/yarn destroys n 

### ISSUE THREAD

**Issue by redevill** [tj/n#557]
# Issue Template:

### Describe issue including what OS you are using
I'm using MacOS 10.13.6

### Describe what version of N you have
n --version output: 2.1.3

### Describe how you installed N
npm install -g n_

### Steps to reproduce issue
Installed macports, followed by yarn (which does a node install I found out)
n no longer shows the selected n version
node -v gives a different result.
![image](https://user-images.githubusercontent.com/8999255/54048453-17ff8680-4197-11e9-8178-427dd4914cab.png)

### Describe the results you received
Trying to install a new version of n goes through the motions, but is not in the list and is not selectable.

### Describe the results you expected
Not sure - I know what I would like - a warning that my symbolic link is being destroyed.
Perhaps if I changed the permissions when installing "n" so other installs could not destroy it?

### What version of npm you are using
npm --version output: 6.4.1

**Comment by redevill** [comment]
A follow up. I did a re-install of n, and the functionality appears to be working with the exception of the
"n" ... which is supposed to show you what version is being used. workaround node -v

**Comment by redevill** [comment]
Another follow up - Mac ports is the one that takes away the cursor of which version is used. 
Got rid of all ports - sudo port -f uninstall installed and n working again.
![image](https://user-images.githubusercontent.com/8999255/54051556-539e4e80-419f-11e9-92d6-bc9288849913.png)

**Comment by shadowspawn** [comment]
`n` installs to `/usr/local` by default. macports installs to `/opt/local` by default. You can see if you have more than one version of node in your PATH, and where, with

```
which -a node
```

When `n` show you its list of available downloaded versions, and a different version of node is active from another location, nothing will have the "cursor". And installing a version from the list won't change the active version of node (node -v), because the other version will still be found first.

It is easiest to have just one version of node in your PATH, but you can also change your PATH so that the `n` installed version is found first.

**Comment by sdevilliers** [comment]
Thank you for the info shadow - makes sense. 
Cleaned up my .bash_profile path, and only have one version of n installed... now.

Couple of other points, that may help someone else stumbling through like me.
1. Yarn can be installed with NPM, thus avoiding the macports - and above confusion.
2. Webstorm can operate with either yarn or npm, however - when I installed yarn it changed the default to yarn. Caused me some additional headaches. This can be set in the preferences-Language & Frameworks - Node.js and NPM - Per the image below.

![image](https://user-images.githubusercontent.com/45904117/54136936-4e7d1180-43e2-11e9-8f08-914df515f775.png)

**Comment by redevill** [comment]
Thank you for the info shadow - makes sense.
Cleaned up my .bash_profile path, and only have one version of n installed... now.

Couple of other points, that may help someone else stumbling through like me.

1. Yarn can be installed with NPM, thus avoiding the macports - and above confusion.
2. Webstorm can operate with either yarn or npm, however - when I installed yarn it changed the default to yarn. Caused me some additional headaches. This can be set in the preferences-Language & Frameworks - Node.js and NPM - Per the image below.

![image](https://user-images.githubusercontent.com/8999255/54137331-16c29980-43e3-11e9-8cf8-bf737877fdea.png)

**Comment by Lockedev** [comment]
the proper way to handle this is to install yarn using something like --no-install-recommends so it does not attempt to install node.. I'm not sure what the mac equivalent is, but on linux, I use ```sudo apt-get install --no-install-recommends yarn```
