### ISSUE TITLE
Offering to be a maintainer (collaborator)

### ISSUE THREAD

**Issue by shadowspawn** [tj/n#558]
I am interested in helping maintain and improve `n`. I am active here in this repo as a commenter and contributor:

- https://github.com/tj/n/issues?utf8=✓&q=is%3Aissue+commenter%3Ashadowspawn+
- https://github.com/tj/n/pulls?utf8=✓&q=is%3Apr+commenter%3Ashadowspawn
- https://github.com/tj/n/commits?author=shadowspawn 

I see backwards compatibility as very important for `n`, being widely used and over a long period, and fairly static recently.

(FYI: I recently changed my username from JohnRGee to shadowspawn. The avatar updates in my activity, but mentions of my old username stay in comments.)

**Comment by troy0820** [comment]
I'm trying to see what I need to do for this to happen.  I was going to see if you wanted to but I saw you made your own fork of it.  I can reach out and see to get you added to this repo. @shadowspawn

**Comment by qw3rtman** [comment]
Sure, we really appreciate your contributions — would be happy to have you on-board as a maintainer!

**Comment by shadowspawn** [comment]
On GitHub only the repository owner can grant additional access, so need to reach out to @tj 
https://help.github.com/en/articles/permission-levels-for-a-user-account-repository

On npmjs, all owners have full control.
https://docs.npmjs.com/cli/owner

**Comment by tj** [comment]
added :D

**Comment by shadowspawn** [comment]
Accepted invite. Thanks team. :-)

**Comment by shadowspawn** [comment]
@troy0820

I am now a collaborator on GitHub, but have not been added to npmjs. This is something I believe you can do and does not need tj. See https://docs.npmjs.com/cli/owner

```
npm owner add shadowspawn n
```

(I am currently purging old issues and pull requests, as you may have noticed from deluge of emails! Hopefully this one does not get lost in the noise.)

**Comment by troy0820** [comment]
You should be an official "maintainer" in npm.

**Comment by shadowspawn** [comment]
Thanks, confirmed.
