### ISSUE TITLE
Can't change node versions

### ISSUE THREAD

**Issue by Darksoulsong** [tj/n#561]
# Issue Template:

### Describe issue including what OS you are using
I'm using Linux Mint 19.1

### Describe what version of N you have
2.1.12

### Describe how you installed N
sudo npm install -g n

### Steps to reproduce issue _1.2.3_
1. sudo n lts
2. sudo n v11.0.0

### Describe the results you received
v11.0.0 is downloaded but n fails to change versions, giving me the `cp: not writing through dangling symlink '/usr/local/bin/node'` error.

### What version of npm you are using
6.4.1

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:` /usr/local/bin/n

* Output of `node -v:` v8.10.0

**Comment by shadowspawn** [comment]
I suspect this is a dangling link left over from your previous node setup. You can probably just delete the problem file, but being cautious, where is the link pointing?

```
ls -l /usr/local/bin/node
```

**Comment by Darksoulsong** [comment]
@shadowspawn You're right, sir. Removing the node folder did the trick! Thank you.

**Comment by shadowspawn** [comment]
Good! You are welcome.
