### ISSUE TITLE
How to use n with node installed in user folder 

### ISSUE THREAD

**Issue by rainbow99984** [tj/n#563]
# Issue Template:
I do not have node installed in system by apt-get, I downloaded node zip , unzipped in folder, exported in path . (Node version :10.15)
### Describe issue including what OS you are using

 Ubuntu 12.04

### Describe what version of N you have
 n -V : 3.0.2

### Describe how you installed N

 npm install -g n

### Steps to reproduce issue _1.2.3_
 1. download zip of node from nodejs.org
2. unzip it. (its in user home dir lets say Alpha)
3. put in your path 
4 install n, 
5 install other version of node using n
6 n latest
node -v have no effect of change it shows 10.15
### Describe the results you received
node -v gives 10.15
### Describe the results you expected
should have shown node version opted with "n"

### What version of npm you are using

 npm --version output: 6.4.1

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:`
~/Alpha/node/bin//n  (Its in bin folder under node folder which i have unzipped it )
* Output of `node -v:`
 10.15

**Comment by shadowspawn** [comment]
By default `n` will install to `/usr/local`. You can get it to install to a folder in your home folder by defining `N_PREFIX`.

To use the node installed by `n` you need that location in your PATH before the other version of node you have installed.

You can see if you have more than one version of node and where they are with 

```
which -a node
```

**Comment by rainbow99984** [comment]
Hi, sorry I missed to update, I have set `N_PREFIX` before installing `n`. It is installed in given directory only ie `N_PREFIX (~/n_module)` directory.
`which -a node` shows only one entry ie `~/node/bin//node`
"**node**" is the folder which i unzipped under my user directory.

**Comment by shadowspawn** [comment]
So with your `N_PREFIX`, `n` is going install a new node binary into `~/n_module/bin` and you need that folder in your `PATH` like presumably you have done with `~/node/bin`.

Then to have `~/n_module/bin/node` be the active version of node it either needs to be earlier in your `PATH` than the unzipped version or delete the unzipped version.

**Comment by shadowspawn** [comment]
Some support was offered, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
