### ISSUE TITLE
install fails in Ubuntu 19.04

### ISSUE THREAD

**Issue by MasterJames** [tj/n#565]
With the latest Ubuntu 19.04 (2019-05-01 when you use npm to install 'n'
`npm install -g n `
it will not overwrite the appropriate files and it doesn't work.

First off npm not found so it says apt install npm to install
similar is the case for node but 
```
apt list nodejs
Listing... Done
nodejs/disco 10.15.2~dfsg-1 amd64
```
there is no node or nodejs accessible tough my guess is it's what's in a list of available apt update gets? I used to think it was listing what's installed?

wanting to use npm to install node you can try to install npm first.
It has an absurdly lengthy dependency listing that one must grudgingly allows.

One of the dependencies is node so then node and nodejs both show v10.15.2
npm -v is 5.8.0

I proceed to install 'n' rather quickly with npm install -g n

```
root@server:/tmp# npm install -g n
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
+ n@3.0.2
added 1 package from 4 contributors in 1.044s
root@server:/tmp#
```

The warning says update node but I want 11.8.0 anyway so 

```
root@mdserver:/tmp# n 11.8.0
     install : node-v11.8.0
       mkdir : /usr/local/n/versions/node/11.8.0
       fetch : https://nodejs.org/dist/v11.8.0/node-v11.8.0-linux-x64.tar.gz
   installed : v11.8.0
```
and it is there in /usr/local/n/versions/node/11.8.0
 Unfortunately typing node --version comes up
v10.15.2
as does nodejs not that they are suppose to be different, just redunant I think, so the confusion begins there with the duplicates of node and nodejs

Second bad thing is there is still 'which node' = /usr/local/bin/node
and there is a /usr/bin/node as well as nodejs
there is no link between them but they are dependent
as this command output sequence demonstrates

```
root@server:/tmp# mv /usr/bin/node /usr/bin/node2
root@server:/tmp# node
bash: /usr/bin/node: No such file or directory
root@server:/tmp# which node
/usr/local/bin/node
```
npm doesn't actually work at that point because it suffers the same glitches I guess.

```
root@server:/tmp# which npm
/usr/local/bin/npm
root@server:/tmp# npm
 1: 0x948a70 node::Abort() [node]
 2: 0x997982 node::options_parser::GetOptions(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 3: 0xba5e0a  [node]
 4: 0xba69b9 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 5: 0x24196574fc5d
Aborted (core dumped)
```

Yup all messed up.

```
root@server:/tmp# L /usr/bin/npm
0 lrwxrwxrwx 1 root root 27 Feb 13 22:01 /usr/bin/npm -> ../share/npm/bin/npm-cli.js
root@server:/tmp# which npm
/usr/local/bin/npm
root@server:/tmp# L /usr/local/bin/npm
0 lrwxrwxrwx 1 root root 38 May  3 03:09 /usr/local/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
root@server:/tmp#

```

I think there's enough in this initiall report to try for yourself what a mess it is and that it doesn't work to overwrite the dependencies usr/bin usr/local/bin etc.

Maybe I've done something wrong but it seems correct to install npm and then 'n' and try the version I need 11.8.0 but have nothing work and I've pointed to something odd going on.

Maybe the Ubuntu people have messed up the permissions or something maybe there is an install debug flag that would reveal the glitch preventing any of it from working.

Yes I restored node2 to node but npm -v still core dumps.

npm is too cool now to allow bug reports without going their special site https://npm.community/c/bugs (I'm not a member).
Maybe you want to connect with them about this, but my guess it's something inherently wrong with Ubuntu 19.04 changes somehow, so you need to talk to npm who need to talk with Ubuntu so the dependency chain is making debugging a painful three pillar exercise as well, or maybe this is not your problem and you simply want to pass the buck and close this. I guess then I could point npm to this page and so on down the line until somebody who knows what is happening and responsible can repair the problem.

For now I build a simple script that deleted all default Ubuntu 19.04 node and npm installations and files and downloads the installer directly from the source like your 'n' program does and replaces the files and links in /usr/bin and /usr/local/bin
Maybe it's been 3 decades and I've forgotten but why they need both node and nodejs and copies that are not links but depended from /usr/local/bin (PATH) to /usr/bin seems too complicated and the source of the problems. 
Anyone with insight why that is or needs to be please speak-up but I think that part needs to be rethought and abolished.

**Comment by shadowspawn** [comment]
You encountered a lot of problems there! I'll cover some general info and you can ask more questions as needed if you actually want more info.

1) `n` downloads and unpacks a binary distribution of node from nodejs.org. The default root of the install is `/usr/local` but you can change that using `N_PREFIX`. So by default the installed node binary ends up at `/usr/local/bin/node`. 

npm is also included in the tarball and gets installed at `/usr/local/bin/npm` (as a symlink). This has the advantage that you do get compatible versions of node+npm. (It can also be an npm downgrade though if you have manually updated npm separately.)

2) For installing on a system without `npm` on it already, you can download and run or install `n` directly. (Or use third party `n-install`.)

3) As you have discovered, it can be confusing having more than one version of node and npm installed! A simple setup is to delete the "other" version once you have a working setup with the `n` installed version. Since you installed with `apt` you could remove using `apt-get remove`.

4) The version of node that runs when you have more than one is determined by your `PATH` variable. Mac users have it easy as `/usr/local/bin` is in the default search path but that is not the case on some other systems.

5) The location and layout of other installs of node and npm depend on the installation method or package manager (like apt). `n` is not intended to

**Comment by MasterJames** [comment]
Okay so 'n' after installing a particular version of node updates the PATH to look for it there?
I imagined it changes the files of node in the expected location so...
/usr/local/lib/ and /usr/local/include/ as well as linking symbolically npm-cli.js and npx-cli.js in /usr/local/bin

**Comment by shadowspawn** [comment]
`n` does not alter the `PATH`, that is up to you.

(And yes files get copied into /usr/local/lib/ and /usr/local/include/ and /usr/local/share/ as well as /usr/local/bin.)

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by MasterJames** [comment]
This is working on 19.04 with latest updates as of 2019:05:27.
The version of 'n' that installed is 4.1.0 
NodeJS 'current' version it installs is 12.3.1 (but I still cant use anything after nodejs 11.8 for unrelated reasons.)

**Comment by MasterJames** [comment]
If in Ubuntu 19.04 you do an 
`apt install npm`
Many dependencies are installed and node 10.15.2 is installed.
I use npm to install 'n' globally and the install 'latest' with npm but it doesn't work.
You will not the warning that npm does not support NodeJS 10.15.2, so I guess it's an npm problem?
Anyway you can try for yourself maybe and try to understand why it does not work and that you need to report the problem to npm I guess? so many moving parts good luck.

```
root@myserver:/tmp# node -v
v10.15.2
root@myserver:/tmp# npm install -g n
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
+ n@4.1.0
added 1 package from 4 contributors in 1.117s
root@myserver:/tmp# n current

  Error: invalid version 'current'

root@myserver:/tmp# n latest

     install : node-v12.3.1
       mkdir : /usr/local/n/versions/node/12.3.1
       fetch : https://nodejs.org/dist/v12.3.1/node-v12.3.1-linux-x64.tar.gz
#################################################################################################################################################### 100.0%
   installed : v12.3.1

root@myserver:/tmp# node --version
v10.15.2

```
I will add more if anything changes after a few more tests for you.

**Comment by LinusLing** [comment]
npm -v is 5.8.0

**Comment by shadowspawn** [comment]
If you use n to install node, it also installs npm, as the pre-built binaries from nodejs include both. So you get compatible versions of node and npm if you use the ones installed by n to `/usr/local/bin`, either by uninstalling the system copies, or by editing your `PATH` so `/usr/local/bin` is earlier than the system location.

**Comment by lostwong** [comment]
Just thought I'd chime and say that I just went through the process of using n on Ubuntu 19.04 and everything works.  The installed npm via apt is still 5.8.0 but after running `n latest`, npm and node are now at the latest versions as expected and being pulled from /usr/local/bin as expected.

```
~$ apt-cache show npm | grep ^Version
Version: 5.8.0+ds6-4
```
```
~$ npm -v
6.9.0
```
```
~$ node -v
v12.6.0
```
```
~$ which npm
/usr/local/bin/npm
~$ which node
/usr/local/bin/node
```

**Comment by deefactorial** [comment]
this is what fixed it for me:
```
sudo ln -fns /usr/local/bin/npm /usr/bin/npm
sudo ln -fns /usr/local/bin/node /usr/bin/node
```
