### ISSUE TITLE
n cannot activating new version

### ISSUE THREAD

**Issue by pecliu** [tj/n#569]
# Issue Template:

### Describe issue including what OS you are using

_centos_

### Describe what version of N you have
_n --version output: 4.1.0_

### Describe how you installed N

_ npm install -g n_

### Steps to reproduce issue _1.2.3_
_i.e._
1. n lts
2. download right version
3. display wrong version
4. cannot switch version using n

### Describe the results you received

```shell
n lts

     install : node-v10.16.0
       mkdir : /usr/local/n/versions/node/10.16.0
       fetch : https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.gz
######################################################################## 100.0%
   installed : v10.15.3
```

### Describe the results you expected

_installed right version.  And can switch to it_

### What version of npm you are using

_npm --version output: 6.9.0_

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n`
* Output of `node -v`

#### (paste your output here)

`/data/mvs/nodejs/node-v10.15.3-linux-x64/bin/n`
`v10.15.3`

### Additional

By following official install guide [Installing](https://github.com/nodejs/help/wiki/Installation)
I'm using `root` user,  and add config code below to `/etc/profile`

```shell
VERSION=v10.15.3
DISTRO=linux-x64
export PATH=/data/mvs/nodejs/node-$VERSION-$DISTRO/bin:$PATH
```

**Comment by pecliu** [comment]
I found in `/etc/profile`,default $PATH include `/usr/local/sbin` except `/usr/local/bin`

**Comment by shadowspawn** [comment]
I think from your information you have `n` installing to `/usr/local`, but have another copy of `node` earlier in your PATH in `/data/mvs/nodejs/node-v10.15.3-linux-x64`. 

I have some extra debugging to help understand this in the upcoming release, which you could try using:
```
npx n@next n lts
```

**Comment by pecliu** [comment]
After installed `n`, the `n` is in `/data/mvs/nodejs/node-v10.15.3-linux-x64/bin/n`. 
And then `n` installs `node` to `/usr/local/n/versions/node`.
I guess the `$PATH` haven't recognize the path of new version `node` which  installed by `n`

**Comment by shadowspawn** [comment]
By default `n` installs the node binary to `/usr/local/bin/node` (and caches a copy of the version in `/usr/local/n/versions/node` for using in future reinstalls). So you need `/usr/local/bin` in your PATH.

If I get the commands right for Centos, what do you see for:

```
which --all node
# and
echo $PATH
```

(On a related note, some shells do not see a new version of node straight away and starting a new shell fixes the problem.)

**Comment by virgilwashere** [comment]
> (On a related note, some shells do not see a new version of node straight away and starting a new shell fixes the problem.)

Or if you've loaded the new path, with `n` first, just remove the old version from the hashtable.

```bash
hash -d n
hash -d node
```

```console
$ hash
hits    command
   0    /home/virgil/.local/n/bin/n
$ npm --version
6.9.0
$ which node
/home/virgil/.local/n/bin/node
$ hash
hits    command
   1    /home/virgil/.local/n/bin/npm
   0    /home/virgil/.local/n/bin/node
   0    /home/virgil/.local/n/bin/n
$ hash -d node
$ hash
hits    command
   1    /home/virgil/.local/n/bin/npm
   0    /home/virgil/.local/n/bin/n
$ hash -d n
$ hash
hits    command
   1    /home/virgil/.local/n/bin/npm
```

`hits` are 1 for `npm` because that's the only command I ran. (`npm --version`)

**Comment by pecliu** [comment]
> By default `n` installs the node binary to `/usr/local/bin/node` (and caches a copy of the version in `/usr/local/n/versions/node` for using in future reinstalls). So you need `/usr/local/bin` in your PATH.
> 
> If I get the commands right for Centos, what do you see for:
> 
> ```
> which --all node
> # and
> echo $PATH
> ```
> 
> (On a related note, some shells do not see a new version of node straight away and starting a new shell fixes the problem.)

`which --all node` shows`/data/mvs/nodejs/node-v10.15.3-linux-x64/bin/node`
 and
`echo $PATH` shows
`/data/mvs/nodejs/node-v10.15.3-linux-x64/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/tsso_openssh/bin:/usr/local/sbin`

It seems that I should add `/usr/local/bin/node` to my root user's $PATH

**Comment by pecliu** [comment]
> By default `n` installs the node binary to `/usr/local/bin/node` (and caches a copy of the version in `/usr/local/n/versions/node` for using in future reinstalls). So you need `/usr/local/bin` in your PATH.
> 
> If I get the commands right for Centos, what do you see for:
> 
> ```
> which --all node
> # and
> echo $PATH
> ```
> 
> (On a related note, some shells do not see a new version of node straight away and starting a new shell fixes the problem.)

`which --all node` shows`/data/mvs/nodejs/node-v10.15.3-linux-x64/bin/node`
 and
`echo $PATH` shows
`/data/mvs/nodejs/node-v10.15.3-linux-x64/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/openssh/bin:/usr/local/sbin`

It seems that I should add `/usr/local/bin/node` to my root user's $PATH

**Comment by shadowspawn** [comment]
I have added additional logging in v5.0.0 which should make PATH issues easier to identify.

Thank you  for your contributions.
