### ISSUE TITLE
change directory hook shell integration auto-checking .nvmrc 

### ISSUE THREAD

**Issue by jjangga0214** [tj/n#573]
**nvm** provides shell integration (change directory hook function), automatically calling `nvm use` if there's `.nvmrc` (and of course, reverting to default version when moving to other directories). And that's pretty convenient. 

What if **n** officially introduces it as well? 

```bash
# pseudo code 
func load_nvmrc() {
  if( there is .nvmrc) {
    n use $(cat .nvmrc)
  } else {
    revert to default version
  }
}
```

**Comment by shadowspawn** [comment]
n does an actual install including npm when switching versions, rather than just change some links, so it is not a great match for switching node automatically when changing directories.

However, there have been discussions and there are some options:
 
- https://github.com/wbyoung/avn
- https://github.com/tj/n/issues/481
- https://github.com/tj/n/issues/204

**Comment by jjangga0214** [comment]
@shadowspawn Thank you for the response. However, as I, unfortunately, don't have enough time to read all discussions, could I ask a direct and simple question that you might be able to answer by (yes  | no)?

Is it not possible for **n** to have the feature (reading .nvmrc automatically and change node version) without causing serious tradeoff? So I shouldn't expect the feature to be implemented?

**Comment by shadowspawn** [comment]
> Is it not possible for n to have the feature (reading .nvmrc automatically and changing node version) without causing serious tradeoff? So I shouldn't expect the feature to be implemented?

Correct, I do not expect this feature to be implemented.

**Comment by mnn** [comment]
I didn't really like the automatic solutions, so I am using simple not-so-automatic script https://gitlab.com/snippets/1899482. When starting working on a different project I just run `switch-node`. Previously I had to read project readme or guess with what version it is compatible, now (after adding `.node-version` or using existing `.nvmrc`) I just run that one command and I am done.
