### ISSUE TITLE
Prerelease of v6 available

### ISSUE THREAD

**Issue by shadowspawn** [tj/n#579]
Prerelease available via `npm i n@next` for v6. Release notes: https://github.com/tj/n/releases/tag/6.0.0-0

**Comment by emilyaviva** [comment]
I've been using this with no problems for a few days now. The breaking changes are good, and I have not yet run into any issues with usage. Thanks for the updates!! 🎉🚀

**Comment by shadowspawn** [comment]
Thanks @emilyaviva! Nice to hear someone tried the prerelease. :-)

**Comment by emilyaviva** [comment]
Yeah, I said, "heck with it, I'm gonna uninstall nvm and just go with this prerelease of n for a while and We'll See What Happens!" and so far everything's been hunky-dory. (For reference, I installed it by hand, not via npm, so I didn't test it via that channel.)

**Comment by DeeDeeG** [comment]
I've done some very basic tests (such as `n lts`, `n stable`, `n 10`, `n 0.8`, `n 0.8.6` etc.) with and without `N_USE_XZ`. Also used a custom `N_PREFIX`. Those aren't very difficult tests to pass, but so far so good!

`n ls` does something totally different than before, which is mentioned in the release notes. Works as described there.

I think it's particularly cool you can get nightly node with `n nightly`.

I also think the explanatory text is helpful when just running `n` without arguments. (For context: running `n` with no arguments lets you select among already-downloaded (cached) versions of node, and "install" one of them as the active version of node.) New text tells you what this screen is about and how to use it, etc.

I didn't try anything with proxies or custom mirrors, which is probably the harder stuff.

**Comment by shadowspawn** [comment]
Thanks @DeeDeeG. 

For your interest, this release is a _big_ back-port of improvements from `nvh`.
https://github.com/tj/n/issues/570#issuecomment-503882088

**Comment by shadowspawn** [comment]
n v6.0.0 has been released
