### ISSUE TITLE
ICU data missing

### ISSUE THREAD

**Issue by caguthrie** [tj/n#580]
## Short Version

Users may want to have a full set of ICU data with their Node build.

## Long Version

ICU data, which is used in internationalization features in Node, is only included for English with most Node builds.  See relevant Node docs here: https://nodejs.org/api/intl.html .  Users may like a CLI option in n to include this data in their Node builds.

**Comment by shadowspawn** [comment]
`n` is installing prebuilt binaries from <https://nodejs.org/dist/> and not building from source. Are you thinking of custom builds of node, or about downloading ICU data separately? I don't currently understand where ICU would fit into what `n` does.

I note the page you linked references [full-icu](https://www.npmjs.com/package/full-icu) for providing ICU data at runtime:
<https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime>
