### ISSUE TITLE
n v6 released

### ISSUE THREAD

**Issue by shadowspawn** [tj/n#583]
Release notes: https://github.com/tj/n/releases/tag/v6.0.0

**Comment by geminiyellow** [comment]
why change the Commands, and 

```
> n lsr
Listing remote... Displaying 20 matches (use --all to see all).

> n lsr --all

  Error: invalid version '--all'
```

??

**Comment by shadowspawn** [comment]
1) 
> why change the Commands

`ls `and `lsr`? I wanted list commands for both the local and remote versions of node available, and I think ls makes more sense as the local one. This is also consistent with similar packages, as `nvm` and `nvs` both have commands called `ls` and `ls-remote`.

2)
> n lsr --all
>
>    Error: invalid version '--all'

Hmm, I had wondered about that. Historically all of the options for n must come first, and I left it that way for this release. So in n 6.0.0:

```sh
n --all lsr
```

(You could open an issue asking for `n lsr --all`, I am interested in making that work.)

**Comment by shadowspawn** [comment]
Support for `n lsr --all` added in v6.0.1.

**Comment by geminiyellow** [comment]
@shadowspawn and when you type `n lsr --all`, the versions will list from latest to oldest,

```
0.8.8
0.8.7
0.8.6
> n latest
```

why dont you sort it from oldest to latest ? for check latest version have to scroll to the top of console, i dont think it is good idea.

**Comment by shadowspawn** [comment]
I did try the sort order for `n lsr` oldest to latest when I first implemented this feature, but preferred newest to oldest for the restricted lists (thinking of it like `head` not `tail`, finding first 20 not last 20). I also found scrolling was now seldom needed for what I wanted to lookup. e.g.

```
n --latest
n lsr latest
n lsr current
n lsr 12
n lsr

n --lts
n lsr lts
n lsr 10
n lsr dubnium
```
