### ISSUE TITLE
currently, `n latest` results in a downgrade of npm to 6.10.2

### ISSUE THREAD

**Issue by luckman212** [tj/n#586]
I have `n` 6.0.1 installed on macOS 10.14.6

If one updates npm to latest using `npm install npm@latest -g`, as of 8/28/2019 it will be 6.11.2. But, if you then run `n latest` it will _downgrade_ npm to 6.10.2.

I see that `n` fetches the data from https://nodejs.org/dist/index.tab, which also has incorrectly listed 6.10.2 as the latest even though 6.11.2 is tagged on github: https://github.com/npm/cli/releases/latest

So not sure, if there should be some logic in n itself not to downgrade a npm version if a newer ver is already present?

**Comment by shadowspawn** [comment]
`n` uses the prebuilt tarballs from nodejs.org, which include a version of node _and_ npm. So when you install node using `n`, you get a particular version of npm as well. This is true of the downloadable Mac and Windows installers too.

There is not currently support in `n` for leaving npm out of the install (or avoiding an npm downgrade).

It does cause some surprise when people first notice: #210 #488 #574. To make it clearer what is happening, `n` 6 added logging about the npm version so at least you know it has happened.

(I have added support for preserving npm in my fork https://github.com/shadowspawn/nvh, but did it in part by switching from `cp` to `rsync` to do the actual install. I have had one try in `n` but discovered problems in testing: #513)

**Comment by luckman212** [comment]
I see. I "worked around" this issue by just calling `npm install npm@latest -g` from my update script after running `n latest`. As long as it's done in that order, you end up with the latest node as well as an up-to-date npm.

**Comment by markuspeloquin** [comment]
@luckman212 Unfortunately, this also results in npm, and all dependencies, being re-upgraded every time you run your update script. Unless your script detects when there's an upgrade.

I think I'll just commit a change in my local repo to skip the NPM 'update'. Somehow...

**Comment by luckman212** [comment]
Yes, my script does check versions and only upgrades when necessary. Here's a gist:
[luckman212/node_update.sh](https://gist.github.com/luckman212/5ffb905ac7d4f23584946002a9ba9764)

**Comment by markuspeloquin** [comment]
Here's my workaround, which I'm committing to my local repo. I'm not sure I believe it'd be accepted as a PR: https://gist.github.com/markuspeloquin/b7828d8d1a9424f7318535797d22a6be

Now, `n latest && npm upgrade -g` doesn't downgrade & upgrade npm :). This is fine when all you care about is running the latest release.

**Comment by shadowspawn** [comment]
Love the code comments about tar features. "Oh, shell scripting."...

I am interested people in this thread are actively taking steps to preserve npm. In the past people have often not taken things further after getting an explanation of the behaviour.

One current work-around/option I'll mention is configuring npm to install to a custom location. `n` installs node and npm side-by-side direct from the tarball, and does not use the custom npm prefix, so this is one way to have separate control over node and npm.

**Comment by shadowspawn** [comment]
I have opened a new issue to allow preserving npm version when installing node: #587

Closing this one as answered.

Thank you  for your contributions.
