### ISSUE TITLE
npm does not update until first reboot

### ISSUE THREAD

**Issue by timothy** [tj/n#588]
# Bug Report
`npm` does not update until the first reboot. There needs to be some type of message to explain this to users. 

## Summary

`n` does not start updating `npm` until after the first reboot. After the initial `n` installation, I switched node version witch triggers `npm` version update. The node version changed but the `npm` version did not. I noticed that there needs to be a reboot in order for it to start working. There needs to be some type of message to explain this to users. I thought it was not working and started debugging only to find that it needs a system reboot to start working properly. 

## Steps to Reproduce

Step 1: `npm i n`
Step 2: `n latest`

## Expected Behaviour

`npm` should update to the version included in the installed version of node.js or inform the user that an OS restart is needed.

## Actual Behaviour

`npm` does not update to the correct version until a system reboot happens.

## Other Information

It would make sense for `n` to give a message after installation explaining to users that they need to reboot in order for `npm` to update correctly.

## Configuration Details

fresh installation of Ubuntu 18.04.3 LTS
installed `n` using `npm` version ~3 (the version that comes with `sudo apt install npm`). Node.js was not installed until after `n` installed it for the first time.

```bash
$ n --version 
? 3.5.2-0ubuntu4


$ command -v node
? Not installed until after n installs it

$ node -p process.platform
? N/A
```

**Comment by shadowspawn** [comment]
What shell are you running?

You should not need to reboot. Depending on your shell and how command paths are cached, you may need to start a new shell or cause your shell to look for commands again. I suspect you may now have two versions of npm installed, and until the cache was clearer you were getting the version in `/usr/bin` instead of `/usr/local/bin`.

People have reported needing to start  new shell in the past, but not pinned down the exact circumstances:

- https://github.com/tj/n/issues/451#issuecomment-325173904
- https://github.com/tj/n/issues/381#issuecomment-271722736
- https://github.com/tj/n/issues/170#issuecomment-41244086

Here is what I see with a fresh boot of a docker container:
```
# cat /etc/issue
Ubuntu 18.04 LTS \n \l

# 
# node --version
bash: node: command not found
# npm --version
bash: npm: command not found
# n latest                      

  installing : node-v12.11.1
       mkdir : /usr/local/n/versions/node/12.11.1
       fetch : https://nodejs.org/dist/v12.11.1/node-v12.11.1-linux-x64.tar.gz
   installed : v12.11.1 (with npm 6.11.3)

# node --version
v12.11.1
# npm --version
6.11.3
```

**Comment by shadowspawn** [comment]
Running Ubuntu container with bash, and reproducing your possible steps:

```
# apt-get update && apt-get install npm -y
...
# npm --version
3.5.2
# which -a npm
/usr/bin/npm
# n latest

  installing : node-v12.11.1
       mkdir : /usr/local/n/versions/node/12.11.1
       fetch : https://nodejs.org/dist/v12.11.1/node-v12.11.1-linux-x64.tar.gz
   installed : v12.11.1 (with npm 6.11.3)

# npm --version
3.5.2
# which -a npm
/usr/local/bin/npm
/usr/bin/npm
# hash -r
# npm --version
6.11.3

**Comment by shadowspawn** [comment]
I came across some other reboot comments today:

> If the version number doesn't show up when typing node -v, you might have to reboot.
https://stackoverflow.com/a/19333717/1082434

> You might need to restart
https://stackoverflow.com/questions/16898001/how-to-install-a-specific-version-of-node-on-ubuntu/45726068#45726068

**Comment by shadowspawn** [comment]
I have added some addition output in `n` v6.1.2 for when the node location changes to hopefully reduce confusion for that initial install. 

```
# node --version
v8.10.0
# command -v node
/usr/bin/node
# n lts

  installing : node-v12.13.0
       mkdir : /usr/local/n/versions/node/12.13.0
       fetch : https://nodejs.org/dist/v12.13.0/node-v12.13.0-linux-x64.tar.gz
   installed : v12.13.0 (with npm 6.12.0)

Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"

# node --version
v8.10.0
# command -v node
/usr/bin/node
# PATH="$PATH"
# node --version
v12.13.0
# command -v node
/usr/local/bin/node
```

**Comment by jespertheend** [comment]
I was also having this issue. `PATH="$PATH"` worked for me in an interactive shell, but it was failing when installing node with my cloud-init script, presumably because that uses a non-interactive shell.
`hash -r` did the trick though!
