### ISSUE TITLE
n doesn't use proxy

### ISSUE THREAD

**Issue by bkelley13** [tj/n#589]
# Bug Report

```
sudo n 11.13.0
Password:

  installing : node-v11.13.0
curl: (7) Failed to connect to nodejs.org port 443: Network is unreachable

  Error: download preflight failed for '11.13.0' (https://nodejs.org/dist/v11.13.0/node-v11.13.0-darwin-x64.tar.gz)

$ env | grep proxy
http_proxy=http://theproxy.mycompany.com:80
https_proxy=http://theproxy.mycompany.com:80
```

## Actual Behaviour

It's not recognizing the proxy for our company, even though I have it set in npm proxy as well as env vars for http.

## Configuration Details

```bash
$ n --version
6.0.1

$ command -v node
/usr/local/bin/node

$ node -p process.platform
darwin
```

**Comment by shadowspawn** [comment]
(Can't see any text in your post apart from the Configuration Details. Did you perhaps put your text inside the markdown comments? You can edit the message to make your original text visible, and can use the Preview tab in the edit window to see what it is going to look like.)

I have written up lots of detail on using proxy server which hopefully helps you:
https://github.com/tj/n/blob/master/docs/proxy-server.md

**Comment by shadowspawn** [comment]
You can also try running `sudo n doctor` which does some basic checks.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by Allon-Guralnek** [comment]
The solution is to use `sudo -E` instead of `sudo` so that the `https_proxy` environment variable is passed on to the elevated shell. This is not mentioned in `proxy-server.md`.
