### ISSUE TITLE
Install Node under $N_PREFIX

### ISSUE THREAD

**Issue by diakitenicolas** [tj/n#595]
# Problem

## Short Version
I would like to have an active node version under `$HOME/usr/local/node` by defining `$N_PREFIX` to `$HOME/usr/local` but in my case `node` is always installed under `$HOME/usr/local/bin/node`.

## Long Version
As explained in the short description, my goal is to have an active node version under `$HOME/usr/local/node` after setting the `$N_PREFIX` to `$HOME/usr/local`  however node is always installed under `$HOME/usr/local/bin/node`.
I would like to do it by executing this bash script 
```
  local NODE_VERSION="latest"

  rm -rf "${HOME}/n-install"
  git clone --depth 1 https://github.com/tj/n.git "${HOME}/n-install"
  (cd "${HOME}/n-install" && PREFIX="${HOME}/usr/local" make install)

  mkdir -p "${HOME}/usr/local/node"
  export PATH="${HOME}/usr/local/node/bin:${PATH}"

  export N_PREFIX=$HOME/usr/local
  export PATH="${N_PREFIX}/bin:${PATH}"
  n "${NODE_VERSION}"
```

I don't know if i misunderstand something but when I read this part of the doc I expect having node under `$HOME/usr/local/node`

```
Once installed, n caches node versions in subdirectory n/versions of the directory specified in environment variable N_PREFIX, which defaults to /usr/local;  and the active node version is installed directly in N_PREFIX.

```

## Configuration Details

```bash
$ n --version
6.1.0

$ command -v node
/Users/XXXXX/usr/local/bin/node

$ node -p process.platform
darwin
```

**Comment by shadowspawn** [comment]
The node installation is made up of files in four folders, including the node executable in the `bin` folder. The folders are:

```
${N_PREFIX}/bin/
${N_PREFIX}/share/
${N_PREFIX}/lib/
${N_PREFIX}/include/
```

To get the node binary at `$HOME/usr/local/node` you could make a symbolic link? (Your script does not seem to quite match your description, as `$HOME/usr/local` is not added to the `PATH`.)

**Comment by diakitenicolas** [comment]
Thanks you for your reply.

`To get the node binary at $HOME/usr/local/node you could make a symbolic link?` 
yes I can.

I try to automate  `node`  managment via `n` in my dotfile using `node.sh`  for installation and  `conffile`  (which is called in `node.sh`  and `bashrc` ) for configuration
```
//node.sh

local NODE_VERSION="latest"
local CONF_FILE="conffilePath"

  rm -rf "${HOME}/n-install"
  git clone --depth 1 https://github.com/tj/n.git "${HOME}/n-install"
  (cd "${HOME}/n-install" && PREFIX="${HOME}/usr/local" make install)

  mkdir -p "${HOME}/usr/local/node"
  source  $CONF_FILE
  n "${NODE_VERSION}"

---------------------------------------------------------------------------------
//conffile
  export N_PREFIX=$HOME/usr/local
  export PATH="${N_PREFIX}/bin:${PATH}"
  ```

I don't understand what i need to add `$HOME/usr/local` to PATH, the above 2 exports aren't sufficient ?

**Comment by shadowspawn** [comment]
That script works fine. The `n` and `node` commands both get installed to `${HOME}/usr/local/bin` and that is in the path. 

You don't need the line `mkdir -p "${HOME}/usr/local/node"`

A couple of ideas:

-----

If you don't want the clone of the n repo and are ok going direct, an alternative to 
```
rm -rf "${HOME}/n-install"
git clone --depth 1 https://github.com/tj/n.git "${HOME}/n-install"
(cd "${HOME}/n-install" && PREFIX="${HOME}/usr/local" make install)
```

could be something like
```
mkdir -p "${HOME}/usr/local/bin"
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o "${HOME}/usr/local/bin/n"
chmod u+x "${HOME}/usr/local/bin/n"
```

-----

If you want to manage the version of n using npm after bootstrapping, you could add a line after installing node (and npm):

```
npm install -g n
```

This will overwrite the `n` file you installed before npm was available with one from the npm package.

**Comment by diakitenicolas** [comment]
Thx a lot for your reply and suggestions.
I will go for this one 
```
mkdir -p "${HOME}/usr/local/bin"
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o "${HOME}/usr/local/bin/n"
chmod u+x "${HOME}/usr/local/bin/n"
```
