### ISSUE TITLE
Switching NPM version fails

### ISSUE THREAD

**Issue by loretoparisi** [tj/n#598]
When switching between two versions of `node` npm is reverted back:

```
  ο node/11.1.0
    node/12.13.0
```

but

```
ip-192-168-23-184:musixmatch-intelligence-node-sdk loretoparisi$ sudo n
   installed : v11.1.0 (with npm 6.4.1)
$ npm --version
6.4.1
$ sudo npm install -g npm@latest
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.13.1
added 64 packages from 19 contributors, removed 21 packages and updated 72 packages in 6.272s
$ sudo n
   installed : v12.13.0 (with npm 6.12.0)
$ npm --version
6.12.0
$ sudo n
   installed : v11.1.0 (with npm 6.4.1)
$ npm --version
6.4.1
```

**Comment by shadowspawn** [comment]
The node distribution includes a version of npm too. When n installs node it also installs the version of npm that shipped with that version of node.

There is an open issue to allow installing node without npm: #587

**Comment by loretoparisi** [comment]
@shadowspawn thanks, I'm not sure if `nvm` can handle this in a better way. Your opinion? Thanks.

**Comment by shadowspawn** [comment]
`nvh` supports "preserving" npm: https://github.com/shadowspawn/nvh#preserving-npm

A key difference in the way that `nvm` works is that is maintains separate packages for each version of node. So I expect by default when you switch node versions you get the last npm version you installed with it (but I have not tried it!). See also: https://github.com/nvm-sh/nvm/blob/master/README.md#migrating-global-packages-while-installing

**Comment by loretoparisi** [comment]
Thanks a lot, closing since it can be addressed via `nvm` then, I will try and update here.
