### ISSUE TITLE
Pre-flight checks failed on url I can hit

### ISSUE THREAD

**Issue by mark1973ryan** [tj/n#600]
Hi,

First thing to mention I'm in highly locked down environment with extensive change control.

The pre-flight check failed for sudo n 10.17.0:

```
  installing : node-v10.17.0
    curl: (7) Failed to connect to nodejs.org port 443: Connection timed out

  Error: download preflight failed for '10.17.0' (https://nodejs.org/dist/v10.17.0/node-v10.17.0-linux-x64.tar.gz)
```

If I curl to the url I can hit it fine. Are there other urls I need to allow for in out proxy to pass the pre-flight check? I also tried to short cut the install by downloading the tar and putting it into the cache. However, I couldn't find the correct location.

I'm still trawling the code to find out the urls I need to bypass or where I need to put the file. A pointer would be great thanks.

**Comment by shadowspawn** [comment]
1) What version of n?
`n --version`

2) Try running `n doctor` for some sanity checks, and it displays lots of configuration info.

3) If you are installing to the default `/usr/local`, then the unpacked tarballs are found:

```
% ls -al /usr/local/n/versions/node
total 0
drwxr-xr-x  12 john  wheel  384 23 Nov 10:30 .
drwxr-xr-x   5 john  wheel  160 26 Aug 09:34 ..
drwxr-xr-x   9 john  wheel  288 23 Oct 23:18 10.17.0
drwxr-xr-x   9 john  wheel  288 29 Oct 19:42 10.5.0
```

4) I wrote up lots of information about proxy usage here: https://github.com/tj/n/blob/master/docs/proxy-server.md

**Comment by shadowspawn** [comment]
5) Does `n --lts` work?

6) The difference in the preflight is it adds `--head`, so for reproducing by hand:
```
curl --location --fail --show-error --head https://nodejs.org/dist/v10.17.0/node-v10.17.0-linux-x64.tar.gz
```

**Comment by shadowspawn** [comment]
Hope something in there helps!

**Comment by mark1973ryan** [comment]
Awesome thanks been dragged into a meeting will go through it all and let you know. Thanks for the prompt response.

Sent from my Samsung Galaxy S8 - powered by Three
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mark1973ryan** [comment]
Hi,

The doctor output came back good. I'm on version n=6.1.3. The n --lts came back with 12.13.1. The curl worked fine. But the install still failed. I used wget to put the tarball in the usr/local/ and ran the install and it worked fine.

There must be something else in the pre-flight that our proxy is blocking but I have a workaround for now.

**Comment by jasonrwang** [comment]
I've been getting the same issue (`n doctor` and all steps you've mentioned above checked out). I was on n 8.15.1 before and so `n --lts` spat out 8.17.0. Updating to that works fine, but I can't seem to hit 10.18.0.

I can't replicate @mark1973ryan's working curl though. Could it be that nodejs changed their release naming scheme? None of the listed files at https://nodejs.org/dist/latest-v10.x/ or https://nodejs.org/dist/v10.18.0/ match what n is telling me it's looking for (https://nodejs.org/dist/v10.18.0/node-v10.18.0-linux-x86.tar.gz; ...-linux-x64... exists, but not x86).

**Comment by shadowspawn** [comment]
@jasonrwang sounds like you are on a 32-bit architecture with different issue. 

- https://github.com/tj/n/issues/517#issuecomment-450586230
- https://github.com/tj/n/issues/492#issuecomment-450585623

`n --lts` now shows the newest compatible lts version for your architecture.

**Comment by jasonrwang** [comment]
@shadowspawn ah, indeed. Switching between machines made me forget I was on 32-bit. Thanks!

**Comment by shadowspawn** [comment]
Some information was provided, and no further activity in a month. Closing this as resolved, or at least not an active issue.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
