### ISSUE TITLE
[NixOS] Library (.so) files do not exist in $N_PREFIX in home folder. `node` command fails with "file not found".

### ISSUE THREAD

**Issue by trusktr** [tj/n#603]
# Problem

I used `n` to install Node with `export N_PREFIX=~/.npm-packages`, but after that, this happens:

```sh
$ file `which node`
/home/trusktr/.npm-packages/bin/node: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=95dee799c59496b84fcdf790c20712e3d0848063, with debug_info, not stripped

$ node -v
bash: /home/trusktr/.npm-packages/bin/node: No such file or directory

$ /home/trusktr/.npm-packages/bin/node
bash: /home/trusktr/.npm-packages/bin/node: No such file or directory
```

I read in various posts online that this can happen if library files are missing.

I have no library files installed in my `$N_PREFIX`. Is that why this happens?

Are we supposed to install required library files inside of `$N_PREFIX`? If so, that makes use of `$N_PREFIX` considerably harder than it seems compared to what the README says.

I thought it would work just as easily as `prefix=~/.npm-packages` does with NPM in `.npmrc`.

## Configuration Details

```bash
$ n --version
6.1.3

$ command -v node
/home/trusktr/.npm-packages/bin/node

$ node -p process.platform
bash: /home/trusktr/.npm-packages/bin/node: No such file or directory
```

**Comment by trusktr** [comment]
This basically explains the issue in a generic Linux sense: https://unix.stackexchange.com/questions/18061/why-does-sh-say-not-found-when-its-definitely-there

**Comment by shadowspawn** [comment]
You are not meant to have to install libraries. I think there is something unusual about the version of node that got installed or about your setup. No quick answer, just questions:

1) What version of node are you installing?

2) What architecture are you on?

```
uname -a
```

3) What operating system are you on?

4) Are you installing other things (like npm packages!) to `~/.npm_packages`? You could try defining `N_PREFIX` to a different folder in case there is a clash. This is a bit of a wild guess, so feel free to ignore for now!

**Comment by trusktr** [comment]
@shadowspawn 

1. `n latest` which currently installs 13.6
2. `name -a`: Linux starnix 4.19.93 #1-NixOS SMP Sat Jan 4 18:13:46 UTC 2020 x86_64 GNU/Linux
3. NixOS.org
4. I tried both different folder and same folder with same result.

Thanks for the hints! Maybe it is because I'm on NixOS, which doesn't have a standard `/lib` folder at the root of the filesystem?

If I can figure out where the `lib`s in NixOS are located, maybe I can run it with `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/lib/ node`?

**Comment by shadowspawn** [comment]
Yes, I expect the breaking detail is NixOS. I have been reading about NixOS but all new to me.

`n` is installing a prebuilt linux binary from nodejs.org. I don't know whether it makes sense to try and run "normal" Linux binaries on NixOS, or what is required to make them run. 

(Given NixOS is all about managing packages, there is also the question whether it would be easier to use NixOS to manage node versions rather than a separate version manager like `n`.)

**Comment by trusktr** [comment]
Looks like NixOS users must make use of [buildFHSUserEnv](https://nixos.org/nixpkgs/manual/#sec-fhs-environments) to create an [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) environment in which binaries expecting an FHS filesystem can be executed. NixOS's filesystem doesn't follow FHS.

**Comment by shadowspawn** [comment]
Thanks for update @trusktr
