### ISSUE TITLE
how can I run multiple nodejs at the same type per nodejs path

### ISSUE THREAD

**Issue by born2net** [tj/n#604]
# Problem

so I have all of my old scripts which need node 6.x
but I want to start developing new scripts on 9.x
so I'd like to have two node paths, one for 6 and one for 9
and point each script new / old to proper node version

is it possible with n to support this?

Thanks

Sean

**Comment by born2net** [comment]
found the solution, just point scripts to:
/usr/local/n/versions/node/9.0.0/bin

**Comment by shadowspawn** [comment]
See also"Using Downloaded Node Versions Without Reinstalling" in the README:

https://github.com/tj/n#using-downloaded-node-versions-without-reinstalling
