### ISSUE TITLE
N_PREFIX is ignored on fish shell.

### ISSUE THREAD

**Issue by gkutiel** [tj/n#608]
# Bug Report

## Summary

`N_PREFIX` environment variable is ignored on fish shell.

## Steps to Reproduce

```
> fish
> set -U N_PREFIX $HOME/n/
> n lts

```
## Expected Behaviour

Should install lts version to `$HOME/n/`

## Actual Behaviour

Trying to install to `/usr/local/n`

## Configuration Details

- Linux Mint 19.1 Tessa
- fish, version 2.7.1
- n version 6.2.0
- npm --version 3.5.2

**Comment by shadowspawn** [comment]
From some reading on fish, I think you need to "export" the environment variable as well as set it, so that is is available to processes like the bash shell used to execute `n`. Try:

```
set -Ux N_PREFIX $HOME/n/
```

**Comment by gkutiel** [comment]
Indeed, it works.
