### ISSUE TITLE
Required to manually set NODE_PATH

### ISSUE THREAD

**Issue by adjenks** [tj/n#609]
# Bug Report

node cannot locate globally installed modules until NODE_PATH is set to /lib/node_modules

## Summary

node cannot locate globally installed modules until NODE_PATH is set to /lib/node_modules

## Steps to Reproduce

```bash
$ curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
```

```bash
$ export N_PREFIX=$HOME/.n
$ export PATH=$N_PREFIX/bin:$PATH
```

```bash
$ n lts
```

>  installing : node-v12.16.1
>       mkdir : /home/\<censored>/.n/n/versions/node/12.16.1
>       fetch : https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz
>   installed : v12.16.1 (with npm 6.13.4)

```bash
$ npm i -g emoji-steam-locomotive
```

>\+ emoji-steam-locomotive@1.3.0
>added 1 package from 1 contributor in 0.209s

```bash
$ node -e "console.log(require('emoji-steam-locomotive'))"
```

>internal/modules/cjs/loader.js:985
>  throw err;
>  ^
>Error: Cannot find module 'emoji-steam-locomotive'

```bash
$ export NODE_PATH=/home/<censored>/.n/lib/node_modules/
$ node -e "console.log(require('emoji-steam-locomotive'))"
```

>�

## Expected Behaviour

```bash
$ npm i -g emoji-steam-locomotive
```

>\+ emoji-steam-locomotive@1.3.0
>added 1 package from 1 contributor in 0.209s

```bash
$ node -e "console.log(require('emoji-steam-locomotive'))"
```

>�

## Actual Behaviour

See reproduction steps.

## Configuration Details

```bash
$ n --version
6.2.0

$ command -v node
/home/<censored>/.n/bin/node

$ node -p process.platform
linux
```

**Comment by shadowspawn** [comment]
This is expected behaviour from npm and node. Global npm installs are mostly for commands and not for packages that you will `require`.

https://docs.npmjs.com/configuring-npm/folders.html

> - Local install (default): puts stuff in ./node_modules of the current package root.
> - Global install (with -g): puts stuff in /usr/local or wherever node is installed.
> - Install it locally if you’re going to require() it.
> - Install it globally if you’re going to run it on the command line.
> - If you need both, then install it in both places, or use npm link.

You can configure node to search the default npm global modules folder, but it is not searched by default and is not the recommended pattern:

- https://nodejs.org/docs/latest-v12.x/api/modules.html#modules_loading_from_the_global_folders

> It is strongly encouraged to place dependencies in the local node_modules folder. These will be loaded faster, and more reliably.

**Comment by adjenks** [comment]
!! My mistake... Thank you for enlightening me. I thought that global modules were supposed to also be available via require(). I'm surprised I didn't notice that behavior until installing this package. I guess because, well, I don't normally do that. Haha.
