### ISSUE TITLE
macOS Catalina usage for multiple users Permission denied

### ISSUE THREAD

**Issue by AndyOGo** [tj/n#610]
# Problem

If I switch node version with `n` on another user I get dozens of **Permission denied** errors.

But I created a group `brew` where both users are added.
And I changed all directories of `/usr/local/bin /usr/local/lib /usr/local/include /usr/local/share` to belong to the brew group and having read/write permission.

I must have made something wrong.

```bash
# ... hundreds of these
cp: /usr/local/include/node/openssl/store.h: Permission denied
cp: /usr/local/include/node/openssl/idea.h: Permission denied
cp: /usr/local/include/node/openssl/lhash.h: Permission denied
cp: /usr/local/include/node/openssl/asn1err.h: Permission denied
cp: /usr/local/include/node/openssl/bn_conf_asm.h: Permission denied
cp: /usr/local/include/node/v8config.h: Permission denied
cp: /usr/local/include/node/v8-version-string.h: Permission denied
cp: /usr/local/include/node/v8-internal.h: Permission denied
cp: /usr/local/include/node/zconf.h: Permission denied
   installed : v12.16.1 (with npm 6.13.4)
```

## Configuration Details

```bash
$ n --version
6.2.0

$ command -v node
/usr/local/bin/node

$ node -p process.platform
darwin
```

**Comment by shadowspawn** [comment]
The old npm folder is deleted as part of the install to get a clean install of the version of npm included with node. The folders that get copied in with the new npm do not have group write.

```
% ls -al /usr/local/n/versions/node/13.7.0/lib
total 0
drwxr-xr-x  4 john  wheel  128 22 Jan 05:40 .
drwxr-xr-x  9 john  wheel  288 29 Jan 22:02 ..
drwxr-xr-x  3 john  wheel   96 22 Jan 05:40 dtrace
drwxr-xr-x  3 john  wheel   96 22 Jan 05:40 node_modules
```

Maintaining group write ability on a shared folder is not easy... 

A robust approach with `n` would be to install to your home folder and have separate installs.

**Comment by AndyOGo** [comment]
Oh, I originally tried to switch from `nvm` to `n`, because I have heard it's a system-wide solution and not a user-only tool.

Guess that is a misconception of mine.
Thank you.

**Comment by shadowspawn** [comment]
> because I have heard it's a system-wide solution and not a user-only tool.

The default install with  `n` is system wide (`/usr/local`), which `nvm` does not support. So you were right there. 

Using `sudo` with the install is another approach, and the more traditional system-wide solution. Given you named your group `brew` I assumed that was not the approach you would be interested in.

**Comment by AndyOGo** [comment]
Thanks for your clarification.

I have a `brew` group for homebrew to have it working for multiple users.
So I just wanted to reuse that group:)

Alright, so I will need to use `sudo n ...` always.
