### ISSUE TITLE
How do implement radio-button

### ISSUE THREAD

**Issue by bsurai** [tj/n#613]
I'm excited about your selector (radio-button) for selecting node versions. Could you advise how to do a similar one?

**Comment by shadowspawn** [comment]
You can take a look at the code.

The selected item in the menu is just being drawn with a character in front:
https://github.com/tj/n/blob/a0cfc8079126c84125bbd53ad4f62e2406bb8e98/bin/n#L417

The routine that manages the display of the menu is:
https://github.com/tj/n/blob/a0cfc8079126c84125bbd53ad4f62e2406bb8e98/bin/n#L445

The "graphics" controls, like clearing the screen, are done using ANSI escape codes:
https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by shadowspawn** [comment]
Closing this as answered, and not an `n` issue.
