### ISSUE TITLE
N not working with Fish Shell

### ISSUE THREAD

**Issue by UpperCenter** [tj/n#621]
# Problem

Running the `n` command in Fish after install shows "command not found" even after a full system reboot. 

Not sure if I've just missed something, I had a look through the issues and nobody else seems to have had this problem. `n` works fine with `bash` only `fish` seems to have issues.

## Configuration Details

```bash
$ fish -v
fish, version 3.1.2

```
Running Arch Linux

Thanks for the help!

**Comment by shadowspawn** [comment]
The `n` command is not found? How did you install `n`?

Does it show up with:
```
command -v n
```

**Comment by UpperCenter** [comment]
`command -v n` executed in Fish returns nothing at all, in bash, it returns:
```bash
$ command -v n
/home/uppercenter/n/bin/n
```
I installed `n` with the Linux installation script, `curl -L https://git.io/n-install | bash`

**Comment by shadowspawn** [comment]
`n-install` is a third-party product which installs `n` into your home directory and modifies the shell initialization file, but not for `fish` which you will need to do yourself. 

https://github.com/mklement0/n-install

> If your shell is bash, ksh, or zsh, the relevant shell initialization file is modified:
> - Environment variable N_PREFIX is defined to point to the installation directory.
> - Directory $N_PREFIX/bin is appended to the $PATH, unless already present.
> - For other shells, these modification must be performed manually; instructions are provided during installation.
> - You can also explicitly suppress modification with the -n option.

**Comment by UpperCenter** [comment]
I must have missed that when first installing, thanks for that.

It seems It wants me to add:
```console
export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"
```
To my Fish initialization file, but as Fish isn't POSIX compliant yet, it doesn't seem to like that very much, and throws the following error when refreshed:
```console
~/.config/fish/config.fish (line 125): No matches for wildcard “[[ :$PATH: == *":$N_PREFIX/bin:"* ]]”. See `help expand`.
export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"
                           ^
from sourcing file ~/.config/fish/config.fish
	called during startup
~/.config/fish/config.fish (line 125): 
export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"
                                                                   ^
from sourcing file ~/.config/fish/config.fish
	called during startup
```
Any ideas?

**Comment by shadowspawn** [comment]
`[[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"`

That piece of fancy scripting is doing:

> Directory $N_PREFIX/bin is appended to the $PATH, unless already present.

When you are doing it manually, you can usually skip the "unless already present" and so you just want to add `$N_PREFIX/bin` onto your PATH. I don't know how `fish` does that, but it will be a common task to find guidance for.

**Comment by shadowspawn** [comment]
And defining `N_PREFIX` probably needed to be different too, I remembered an earlier fish issue: #608

**Comment by UpperCenter** [comment]
Yeah that seemed to be it, thanks for the help!

For anyone else who's having this issue with Fish,
`set -U fish_user_paths /home/uppercenter/n/bin $fish_user_paths` 
Added the `n` bin path to Fish universal variable, following the official documentation [here.](https://fishshell.com/docs/current/tutorial.html#path)
