### ISSUE TITLE
Error whenever running n: Must specify HTTP_USER when supplying HTTP_PASSWORD

### ISSUE THREAD

**Issue by Jay2645** [tj/n#633]
# Bug Report

## Summary

Whenever I run `n`, I just get `Error: Must specify HTTP_USER when supplying HTTP_PASSWORD`. This is true even when not passing in any command line arguments:

```
root@Nile-Nellie:/# n

  Error: Must specify HTTP_USER when supplying HTTP_PASSWORD
```

## Steps to Reproduce

* Run `n`, `n latest`, or any other command

## Expected Behaviour

`n` installs the latest version of Node.

## Actual Behaviour

`n` does nothing; prints out `Error: Must specify HTTP_USER when supplying HTTP_PASSWORD`

## Other Information

This is a fresh install of `n`, on an old server still running Debian 8. I attempted to boostrap using `curl -L https://git.io/n-install | bash`, which ran into this same issue.

## Configuration Details

```bash
$ n --version
root@Nile-Nellie:/# n --version

  Error: Must specify HTTP_USER when supplying HTTP_PASSWORD

$ command -v node
root@Nile-Nellie:/# command -v node
root@Nile-Nellie:/#

$ node -p process.platform
root@Nile-Nellie:/# node -p process.platform
-bash: node: command not found
```

**Comment by shadowspawn** [comment]
`n` supports using `curl` (or `wget`) over a connection that requires authentication. It can use the environment variables `HTTP_USER` and `HTTP_PASSWORD`. If `HTTP_PASSWORD` is defined then `n` requires that `HTTP_USER` is also defined.

I expect you have `HTTP_PASSWORD` defined, but not `HTTP_USER`. You can check with:

```
echo "HTTP_USER is $HTTP_USER"
echo "HTTP_PASSWORD is $HTTP_PASSWORD"
```

**Comment by Jay2645** [comment]
Ah, yep, that did it. Didn't even think to check that environment variable. Thanks!
