### ISSUE TITLE
Poll: move package.json engine support out of auto to a new command?

### ISSUE THREAD

**Issue by shadowspawn** [tj/n#640]
The current behaviour with `n auto` is to stop scanning at the first candidate file which includes `package.json`. This prevents scanning outside a package for a control file, say `.node-version` at the root of a mono repo or in the users home directory.

The purpose of `engine` in `package.json` is rather different than a version control file, and processing `package.json` uses extra dependencies.

One approach would be to use different commands for finding the various node version files like `.node-version`, and for finding node version from `package.json`. The new command could be called `n engine` or `n package`.

Related: #618 #636 #639

Show your preference with a reaction:
👍 move `package.json` support out of `auto` to a new command
😐 single command is nice, but two commands would be fine
👎 don't change, keep package.json support in `auto`

**Comment by mhassan1** [comment]
@shadowspawn when might you expect to close the poll?

**Comment by shadowspawn** [comment]
At this stage, 5 replies or a month, whichever comes first. Eagerly waiting? 😄

**Comment by shadowspawn** [comment]
(Note to self: if `auto` fails to find a version, error could suggest `engine` so clue about change in behaviour.)

**Comment by shadowspawn** [comment]
I am having second thoughts about splitting out engine as a I like `n auto` for getting `n` to do something sensible.

Wondering if first search for the version control files all the way up hierarchy, and only then look for `package.json`.

i.e.
1) search up hierarchy for `node-version`, `npmrc` et al
2) fallback look for `package.json`

This works same as before for simple cases of:
- only version control file
- only package.json

While supporting the mono-repo case of a higher level version control file that is more appropriate for picking a node version than the local package.json file.

**Comment by mhassan1** [comment]
That works for me, and I think it's a sensible compromise.
