### ISSUE TITLE
"no version found" error on Mac with M1 chip

### ISSUE THREAD

**Issue by shadowspawn** [tj/n#641]
Using `n current` or `n 8` etc on a Mac with the M1 chip and an older version of `n` will currently display an error that "no version found", because there are not yet native versions of node available for the new architecture.

You can download and run node built for the Intel x64 architecture. The installed node will run using Rosetta 2. e.g.

```sh
n --arch x64 lts
```

Another approach is to launch Terminal itself using Rosetta, so that the terminal environment assumes x64.

The `n` behaviour on Apple M1 will be reviewed when nodejs decide their plans for support:

- https://github.com/nodejs/build/issues/2474 
- https://github.com/nodejs/TSC/issues/886

**Comment by soffes** [comment]
`n latest` on an M1 shows `Error: no version found for 'latest'`

**Comment by shadowspawn** [comment]
Your situation is what this issue is covering @soffes . For now, you can do installs by specifying the architecture.

**Comment by shadowspawn** [comment]
I have been wondering about releasing a version of `n` which defaults to x64 for now, and fine tune it after nodejs start releasing native versions. 

Readers, let me know if this would be useful with a 👍 or comment.

**Comment by shadowspawn** [comment]
Released `n` v6.8.0 which defaults to x64 on a Mac with the M1 chip.

(The native architecture is `arm64` if you need to specify it to try a new release before `n` catches up. `n` does not separate the downloads by architecture, so if you are changing architectures for a specific version then delete the old download before installing again with the desired architecture.)

**Comment by mattdamon108** [comment]
@shadowspawn Recently, I got a M1 air, then I installed the latest version of n. But, it installed the x64 arch node v14 lts after the normal initial installation.

Can you help me to install the arm64 node version with n?

**Comment by shadowspawn** [comment]
@mattdamon108 There are not yet any prebuilt arm64 binaries available for Mac:

https://nodejs.org/dist/latest/

**Comment by mattdamon108** [comment]
@shadowspawn oh! thank you for clarification!

**Comment by parndt** [comment]
Looks like there are now, at least version 15.7.0 has a prebuilt arm64 for darwin - https://nodejs.org/dist/v15.7.0/node-v15.7.0-darwin-arm64.tar.xz
```
 ✗ n 15
  installing : node-v15.7.0
       mkdir : /Users/parndt/n/n/versions/node/15.7.0
       fetch : https://nodejs.org/dist/v15.7.0/node-v15.7.0-darwin-x64.tar.xz
   installed : v15.7.0 (with npm 7.4.3)
```

🎉

**Comment by parndt** [comment]
Looks like there are now, at least version 15.7.0 has a prebuilt arm64 for darwin - https://nodejs.org/dist/v15.7.0/node-v15.7.0-darwin-arm64.tar.xz - however trying to install this version gives `x64`:

```
 ✗ n 15
  installing : node-v15.7.0
       mkdir : /Users/parndt/n/n/versions/node/15.7.0
       fetch : https://nodejs.org/dist/v15.7.0/node-v15.7.0-darwin-x64.tar.xz
   installed : v15.7.0 (with npm 7.4.3)
```

so I tried again with `--arch`:

```
✗ n --arch arm64 15

  Error: no version found for '15'
```

**Comment by shadowspawn** [comment]
@parndt
That might have been released in error, I think the arm64 has gone again!

**Comment by parndt** [comment]
>  That might have been released in error, I think the arm64 has gone again!

@shadowspawn wow, you're right! 😱 it's gone.

**Comment by shadowspawn** [comment]
Some discussion on https://github.com/nodejs/build/issues/2474 in last day is that nodejs are thinking of shipping a fat binary from node 16.

**Comment by parndt** [comment]
Thanks for the info! 😄 

For now, I'll continue to use my workaround via Homebrew which I'll document here in case it helps anyone else:

```
brew install node # this gets the arm64 version compiled by Homebrew, currently 15.6.0
cp -r /opt/homebrew/Cellar/node/15.6.0 ~/n/n/versions/node/
brew uninstall node

n 15.6
   installed : v15.6.0 (with npm 7.4.3)
```

When it runs, activity monitor happily shows the Architecture as "Apple" as expected:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/10128/105913629-ff9dfb00-6091-11eb-9723-195144ff1c5b.png">

**Comment by dac09** [comment]
Hey! My solution was slightly different to the above, 

1. Move the appropriate version from `/opt/homebrew/Cellar/node` to `~/n/n/versions/node/`
e.g. 
``` mv /opt/homebrew/Cellar/node/15.4.0 ~/n/n/versions/node/```

2. Create a softlink in brew's cellar so your other scripts can still continue using the system one
```
cd /opt/homebrew/Cellar/node
ln -s ~/.n/n/versions/node/15.14.0
```

**Comment by shadowspawn** [comment]
Node.js 16 will have a native Apple silicon build (arm64).

There will be a new version of `n` to default to arm64 native for Node.js v16 and higher. 

If Node.js 16 comes out before `n` is updated, then for `n` v6.8.0 through v7.1.0 you can specify the architecture explicitly to override it defaulting to x64:

    n --arch arm64 16

`n` does not keep track of which architecture is downloaded, so if you installed x64 first then remove it and download again:

    n rm 16
    n --arch arm64 16

**Comment by parndt** [comment]
Thanks @shadowspawn that's great news 🏆

**Comment by shadowspawn** [comment]
Released `n` v7.2.1 in preparation for Node.js 16 release.

**Comment by parndt** [comment]
```
➜  ~ n 16
  installing : node-v16.0.0
       mkdir : /Users/parndt/n/n/versions/node/16.0.0
       fetch : https://nodejs.org/dist/v16.0.0/node-v16.0.0-darwin-arm64.tar.xz
   installed : v16.0.0 (with npm 7.10.0)
```

🎉 ✅  problem solved @shadowspawn

**Comment by shadowspawn** [comment]
Thanks for confirming @parndt 😄 

I don't have an Apple Silicon Mac and the index.tab did not get updated with arm64 until this morning and Node.js 16 wasn't out, so while I was fairly confident from manual tests, good to hear it works with the actual release!
