### ISSUE TITLE
Error: download preflight failed

### ISSUE THREAD

**Issue by al3x-huang** [tj/n#642]
# Bug Report

## Summary

When running `n <version>` I get this error message:
```
$ n 10

/usr/local/bin/n: line 194: [[: v10: syntax error: operand expected (error token is "v10")

  installing : node-vv10.23.0
curl: (3) [globbing] bad range in column 28

  Error: download preflight failed for 'v10.23.0' (https://nodejs.org/dist/vv10.23.0/node-vv10.23.0-darwin-x64.tar.xz)
```

it seems like the URL is incorrect: `vv10.23.0` in the above example instead of `v10.23.0`

## Steps to Reproduce

`n 10` or `n <version>` or `n v10`

## Expected Behaviour

Install node correctly

## Actual Behaviour

Throws error

## Other Information

`n doctor` runs fine
`n -V` is 6.8.0
`n 10.23.0` is the only command that runs/installs

## Configuration Details

```bash
$ n --version
6.8.0

$ command -v node
/usr/local/bin/node

$ node -p process.platform
darwin
```

**Comment by al3x-huang** [comment]
It appears after looking through `/usr/local/bin/n` there is a problem with the version string and how it's generated.
```
install() {
  [[ -z "$1" ]] && abort "version required"
  local version
  #version="$(display_latest_resolved_version "$1")" || return 2
  version="10.23.0"
  ...
```

hardcoding `version` without the `v` prefix produces the expected behavior. Perhaps someone should take a look at `display_latest_resolved_version` and generate the version string without the `v` prefix?

**Comment by shadowspawn** [comment]
I am not seeing the same problem, so something different between our setups. There is a command which is used by the units tests which will let us conveniently compare calling display_latest_resolved_version. What do you see when you run this:

```sh
$ n N_TEST_DISPLAY_LATEST_RESOLVED_VERSION 10
10.23.0
```

**Comment by al3x-huang** [comment]
```
$ n N_TEST_DISPLAY_LATEST_RESOLVED_VERSION 10
v10.23.0
```

**Comment by al3x-huang** [comment]
Curiously, 
```
$ n N_TEST_DISPLAY_LATEST_RESOLVED_VERSION 10.23.0
10.23.0
```

**Comment by shadowspawn** [comment]
There is code which is meant to be dropping the `v` from the string using grep and an extended regular expression. What do you see with this command:

```sh
 $ echo "v10.23.0" | grep -E -o '[^v].*'
10.23.0
```

**Comment by al3x-huang** [comment]
```
$ echo "v10.23.0" | grep -E -o '[^v].*'
10.23.0
```

**Comment by shadowspawn** [comment]
Huh. I'm out of time and ideas for now, will look again later! I am not sure the extra `v` alone explains the error messages you see during install.

**Comment by shadowspawn** [comment]
(For interest, the reason "10.23.0" works is because it is recognised as a fully qualified version and `display_latest_resolved_version` just returns it instead of checking the nodejs downloads to find a matching version.)

**Comment by shadowspawn** [comment]
Bit of a wild guess, but in case you have some different tools or aliases. What do you see for:

```sh
command -v awk
command -v grep
awk --version
grep --version  
```

I see:

```sh
$ command -v awk
/usr/bin/awk
$ command -v grep
/usr/bin/grep
$ awk --version
awk version 20200816
$ grep --version
grep (BSD grep) 2.5.1-FreeBSD
```

**Comment by al3x-huang** [comment]
```
$ command -v awk
/usr/bin/awk
$ command -v grep
/usr/bin/grep
$ awk --version
awk version 20070501
$ grep --version
grep (BSD grep) 2.5.1-FreeBSD
```

**Comment by shadowspawn** [comment]
I don't have any quick answers, so could be a process of elimination! This is a shell file which does what `display_latest_resolved_version` does, but hard coded. For me it displays `10.23.0`. What do you see?

```sh
#!/usr/bin/env bash
curl https://nodejs.org/dist/index.tab \
    | grep -E "osx-x64-tar" \
    | grep -E "^v10[^0-9]" \
    | awk "NR<=1" \
    | cut -f 1 \
    | grep -E -o '[^v].*'
```

**Comment by al3x-huang** [comment]
```
$ ./testn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  114k    0  114k    0     0   354k      0 --:--:-- --:--:-- --:--:--  355k
v10.23.0
```

**Comment by shadowspawn** [comment]
Well found! I did not know about `GREP_OPTIONS`.

**Comment by shadowspawn** [comment]
I checked `nvm` which I knew was more paranoid than `n` about environmental pollution, and sure enough it protects both `GREP_OPTIONS` and aliases. Can follow that example.

```
nvm_grep() {
  GREP_OPTIONS='' command grep "$@"
}
```

**Comment by al3x-huang** [comment]
That works, I just tested it and made a PR!

**Comment by shadowspawn** [comment]
Released in v.7.0.0

**Comment by wescrow-loop** [comment]
I found that without the `v` on the front of the version number I couldn't install the specific version I was looking for. 

```
sudo n i 16.10.0
Password:
  installing : node-v16.10.0
curl: (22) The requested URL returned error: 409 

  Error: download preflight failed for '16.10.0' (https://nodejs.org/dist/v16.10.0/node-v16.10.0-darwin-x64.tar.xz)
```
However, when I added the `v` to the front it worked:

```
sudo n i v16.10.0
Password:
  installing : node-v16.10.0
       mkdir : /usr/local/n/versions/node/16.10.0
       fetch : https://nodejs.org/dist/v16.10.0/node-v16.10.0-darwin-x64.tar.xz
   installed : v16.10.0 (with npm 7.24.0)
```
