### ISSUE TITLE
n is not working under openbsd 6.8

### ISSUE THREAD

**Issue by mbauhardt** [tj/n#645]
`n versions` or `n lts` show for example `Error: no versions found for 'lts'`

output of n doctor 
```
This information is to help you diagnose issues, and useful when reporting an issue.
Note: some output may contain passwords. Redact before sharing.


COMMAND LOCATIONS AND VERSIONS

bash
/usr/local/bin/bash
GNU bash, version 5.0.18(1)-release (x86_64-unknown-openbsd6.8)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

n
/home/mb/usr/local/bin/n
7.0.0

node

tar
/bin/tar
tar: unknown option -- -
usage: tar {crtux}[014578befHhjLmNOoPpqsvwXZz]
           [blocking-factor | archive | replstr] [-C directory] [-I file]
           [file ...]
       tar {-crtux} [-014578eHhjLmNOoPpqvwXZz] [-b blocking-factor]
           [-C directory] [-f archive] [-I file] [-s replstr] [file ...]

curl or wget
/usr/local/bin/curl
curl 7.72.0 (x86_64-unknown-openbsd6.8) libcurl/7.72.0 LibreSSL/3.2.2 zlib/1.2.3 nghttp2/1.41.0
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

rsync:
/usr/local/bin/rsync
rsync  version 3.2.3  protocol version 31
Copyright (C) 1996-2020 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, hardlink-specials, symlinks, IPv6, atimes,
    batchfiles, inplace, append, no ACLs, no xattrs, optional protect-args,
    no iconv, symtimes, no prealloc, stop-at, no crtimes
Optimizations:
    no SIMD, asm, openssl-crypto
Checksum list:
    md5 md4 none
Compress list:
    zlibx zlib none

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

uname
OpenBSD 2147NFS.raspberry.lan 6.8 GENERIC.MP#2 amd64


SETTINGS

n
node mirror: https://nodejs.org/dist
node downloads mirror: https://nodejs.org/download
install destination: /home/mb/usr/local
PATH: /opt/usr/local/bin:/opt/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/home/mb/bin:/home/mb/z/src/go/bin:/home/mb/.cargo/bin:/opt/usr/local/bin:/opt/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/home/mb/bin:/home/mb/z/src/go/bin:/home/mb/.cargo/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/local/jdk-1.8.0/bin:/home/mb/usr/local/bin
ls-remote max matches: 20

Proxy


CHECKS

Checking n install destination is in PATH...
good

Checking permissions for cache folder...
good

Checking permissions for install folders...
good

Checking mirror is reachable...
good

```

I believe it is because `n` uses tar with an unknown option. maybe `gtar` would be a workaround...

**Comment by shadowspawn** [comment]
`n` uses prebuilt node archives from nodejs. I think the `uname` output shows you are running on amd64 which is not one of the available downloads. 

https://nodejs.org/dist/latest-fermium/

The actual command used for architecture lookup by `n` is `uname -m`. Does that return `amd64`?

You can specify the target architecture explicitly. I am not sure whether you can expect x64 to run on your setup? 

```sh
n --arch x64 lts
```

But you might then run into other problems! The error message from `n doctor` is because `--version` is not supported by your `tar`, so may or may not be using other problem flags...

**Comment by shadowspawn** [comment]
Ah, and the operating system is unsupported too! Might perhaps have worked with Linux compatibility previously, but not with OpenBSD 6.

https://www.linux.com/news/openbsd-60-tightens-security-losing-linux-compatibility/

**Comment by mbauhardt** [comment]
yes `uname -m` show `amd64`. `n --arch x64 lts` produce the same output / same behaviour.

So, is this a general nodejs issue or is it an n issue?
Do you see any chance to get `n` working? some workaround there?

**Comment by shadowspawn** [comment]
`nodejs.org` do not offer precompiled binaries for OpenBSD, and `n` does not build from source. No chance of getting `n` working.

You can look for node in a package manager on your platform, or build from source.

https://github.com/nodejs/node/blob/master/BUILDING.md#building-nodejs-on-supported-platforms

**Comment by mbauhardt** [comment]
thx.
`node` is available via the openbsd package manager. in version 12.16.1
so i can use node in this version. but switching between this versions and lower version isn't possible.

ok thx. I would close this issue as clarified or won't fix.
