### ISSUE TITLE
Can't change active version of node

### ISSUE THREAD

**Issue by dbaiser** [tj/n#646]
# Problem

Using `n stable` and thereafter inputting `n` and selecting `node/14.15.4` won't make this version the `active` version of node. Bash outputs:
```
installed : v14.15.4 to /home/snoopy/.n/bin/node
active : v10.19.0 at /usr/bin/node
```

## Short Version

I can't make the new version of node I installed using `n` become the `active` version of node (i.e., `node -v # outputs: v.10.19.0, instead of the version I chose`)

## Long Version

I'm a noob and this is probably a mistake with permissions. But this is what I did:

```
# On a fresh new Ubuntu 20.04 server:
sudo apt install npm

# Change environment variables in .profile:
export PATH="$HOME/.npm/bin:$PATH"
export N_PREFIX=$HOME/.n
export PATH="$PATH:$N_PREFIX/bin"

# Install n:
npm i -g n

# Install the version of node I want:
n stable

# After selecting it using n, I get this output:
installed : v14.15.4 to /home/<my_user_name>/.n/bin/node
active : v10.19.0 at /usr/bin/node
```

## Configuration Details

```bash
$ n --version
7.0.0

$ command -v node
/usr/bin/node

$ node -p process.platform
linux
```

**Comment by shadowspawn** [comment]
The problem is you have `node` and `npm` installed to two locations, and ones being installed by `n` are last in the `PATH` variable.

For interest, you can run `n doctor` and it should pick up this problem.

You could either uninstall the copies of npm and node installed to `/usr/bin/node`, or rearrange your `PATH`. Instead of:

```
export PATH="$PATH:$N_PREFIX/bin"
```

try:
```
export PATH="$N_PREFIX/bin:$PATH"
```

**Comment by dbaiser** [comment]
Thank you very much, @shadowspawn ! And I realized too this is the same issue of https://github.com/tj/n/issues/620 , I'm sorry for duplicating the thread. I'll close it now, thanks again!

**Comment by LoveSponge** [comment]
Just for a potential non-static path-altering fix, my install process for `n` is:
1. Install `nodejs` (via installer, or `yay` or whatever)
2. `npm install -g n`
3. `n lts` (or whatever version you want)
4. Uninstall the original `nodejs` you started with, this will guarantee only 1 installation of any given version of nodejs, which is always the `n` managed one.

Cheers
