### ISSUE TITLE
Solution for n running on Alpine

### ISSUE THREAD

**Issue by immanuelfodor** [tj/n#648]
I think I've found the solution for running `n` on Alpine (see https://github.com/tj/n/issues/431).

I checked the official Docker image of Node at https://hub.docker.com/_/node

The latest LTS latest Alpine was that I followed (`14.15.4-alpine3.12, 14.15-alpine3.12, 14-alpine3.12, fermium-alpine3.12, lts-alpine3.12`), and it took me to this Dockerfile: https://github.com/nodejs/docker-node/blob/ad676318f09f9dee821ac6704340000d75fe31bc/14/alpine3.12/Dockerfile#L21

The highlighted line contains a link to `https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH-musl.tar.xz`

When I opened the link in my browser, I could download the XZ file: https://unofficial-builds.nodejs.org/download/release/v14.15.1/

Extracted it, and it contains the same structure than the non-Alpine NodeJS XZ distribution files: 

![image](https://user-images.githubusercontent.com/21174107/105067278-d375ef00-5a7f-11eb-84c0-9cbe25a9a70c.png)

When I check the build, it's indeed a `musl` build:

```bash
$ readelf -l node | grep "program interpreter"
      [Requesting program interpreter: /lib/ld-musl-x86_64.so.1]
```

In contrast, the version downloaded by `n` on Alpine now resolves to a non-existent dependency:

```bash
$ readelf -l /usr/local/bin/node | grep "program interpreter"
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
```

And it makes my CI pipeline die:

![image](https://user-images.githubusercontent.com/21174107/105067691-41221b00-5a80-11eb-92ee-92712787fab0.png)

The file is definitely there, what is missing it's runtime dependency as it was not built for Alpine: https://unix.stackexchange.com/questions/18061/why-does-sh-say-not-found-when-its-definitely-there

![image](https://user-images.githubusercontent.com/21174107/105067761-58610880-5a80-11eb-91c5-2b68a183d4cd.png)

Could you please adjust `n` to detect if it's running on Alpine, and then use the https://unofficial-builds.nodejs.org/ repo to download the `musl` build what works fine on Alpine? 

Although the repo is named unofficial, the official Docker image by Docker uses it, so we could do, too.

**Comment by shadowspawn** [comment]
Interesting! I probably won't download from an unofficial build by default, but `n` has support for using an alternative mirror with compatible layout and control file `index.tab`. This may work:

```sh
N_NODE_MIRROR=https://unofficial-builds.nodejs.org/download/release n --arch musl lts
```

Note that `n` is a `bash` script, and Alpine comes by default with the `ash` shell.

**Comment by shadowspawn** [comment]
Refreshing my knowledge of musl and Alpine, a complication is that musl in the archive name is extra compared with the usual operating system and architecture parts of the archive name.

Possible sources of context are:

```sh
/ # ldd --version
musl libc (x86_64)
Version 1.2.1
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
/ # more /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.0
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by shadowspawn** [comment]
I got node installed with:

```sh
docker run -it alpine sh

apk add bash curl ca-certificates libstdc++ libgcc
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
chmod u+x n
N_NODE_MIRROR=https://unofficial-builds.nodejs.org/download/release ./n --arch x64-musl lts
```

**Comment by immanuelfodor** [comment]
Wow, I didn't know that env var, thanks! I'll try it in the Alpine CI pipeline, and report it back how it went.

**Comment by immanuelfodor** [comment]
The instructions worked fine, I think the Alpine issue is now solved for good! :)

**Comment by shadowspawn** [comment]
Thanks for the info
