### ISSUE TITLE
n@7.0.1: The platform "win32" is incompatible with this module.

### ISSUE THREAD

**Issue by omasjoseph56** [tj/n#656]
I used the latest version but seems I always got the following errors.

[2/4] Fetching packages...
error n@7.0.1: The platform "win32" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by shadowspawn** [comment]
What platform are you on? If you are on Windows, what shell are you running commands from?

Note, near the top of the README is:

> (Note: n is not supported natively on Windows.)

Some people have had success running in wsl  : #511

**Comment by omasjoseph56** [comment]
> What platform are you on? If you are on Windows, what shell are you running commands from?
> 
> Note, near the top of the README is:
> 
> > (Note: n is not supported natively on Windows.)
> 
> Some people have had success running in wsl : #511

I am using windows

**Comment by shadowspawn** [comment]
`n` is written as a  bash script and does not run natively on Windows. Since it doesn't run, it can't display a nice error message. The best we can so is put an entry in the `package.json` to you get an error on install:

```
  "os": [
    "!win32"
  ],
```

**Comment by shadowspawn** [comment]
Issue #626 has some more explanation, and links to past issues.
