### ISSUE TITLE
Global modules return every time node version is changed

### ISSUE THREAD

**Issue by milos201** [tj/n#662]
# Bug Report

## Steps to Reproduce

1. `n lts`
2. `npm list -g --depth 0`

## Expected Behaviour

Command to install new node version (`n lts`) should not restore every global npm module ever installed. (No matter how many times I uninstall it)

## Actual Behaviour

Whenever I install new node version using `n lts` all my globally installed modules return.
No matter how many times I uninstall global modules they all come back after I update node version with `n lts`.

## Configuration Details

- Mac OS Big Sur 11.2.3
- I never had node installed any other way other than n.

```bash
$ n --version
6.7.0

$ command -v node
/Users/milos/.n/bin/node


$ node -p process.platform
darwin
```

**Comment by shadowspawn** [comment]
`n` installs from a downloaded cache copy of Node.js. It sounds like the cache copy has had some npm global modules installed or copied into it.

You can check whether this is the case by looking in the cache folder or running the list command against the cache copy of npm. I would not expect to see any modules listed except for npm itself. e.g.

```
$ n exec lts npm list -g --depth=0
/usr/local/n/versions/node/14.16.1/lib
└── npm@6.14.12
```

You can remove the cache folder for that version so the next install will download again:

```
$ n rm lts
```

`n` v7.1.0 includes some changes to the install process which improve this scenario and avoid restoring the old npm global modules during an install.

**Comment by shadowspawn** [comment]
Are you still having a problem @milos201 ?

**Comment by shadowspawn** [comment]
Have a good story for the observed behaviour, and latest version likely fixes issue, and no feedback from original poster. Closing.
