### ISSUE TITLE
N_NODE_MIRROR with authentication

### ISSUE THREAD

**Issue by BreakBB** [tj/n#665]
# Problem

We don't know how to add authentication to an `N_NODE_MIRROR` URL and can't find if this is even possible with n.

## Short Version

We want to download node version via a private node mirror. This mirror requires authentication. 

We tried to urlencode the `N_NODE_MIRROR`,

> N_NODE_MIRROR="https://user:password@ourPrivateNodeMirror:443/nodejs-mirror" n --insecure --lts

But this results in:

> curl: (22) The requested URL returned error: 401 Unauthorized

Is there any possibility to hand the user and password to n (e.g. as additional command line parameter)?

We read [the Proxy Server docs](https://github.com/tj/n/blob/master/docs/proxy-server.md) but they don't seem related.

## Configuration Details

```bash
$ n --version
7.2.1

$ command -v node
/usr/local/opt/node@10/bin/node

$ node -p process.platform
darwin
```

**Comment by BreakBB** [comment]
After scrolling through the code we found the usage of `HTTP_USER` and `HTTP_PASSWORD` which are handed as curl options. These perfectly fit our needs since it allows us to do:

> HTTP_USER="myUser" HTTP_PASSWORD="myPassword" N_NODE_MIRROR="https://ourPrivateNodeMiror:443/nodejs-mirror" n --insecure --lts

These parameters are marked as "legacy" though (see [this comment](https://github.com/tj/n/blob/b75a553f251b3afbef48016b1e347756e2188955/bin/n#L101). Are there plans to remove the support of these? Have there been problems with it in the past?

**Comment by shadowspawn** [comment]
No immediate plans to delete them. Legacy because names do not start with `N_` to reduce chance of conflicts.

(I’ll have to do some reading to refresh myself what I thought could be used instead.)

**Comment by BreakBB** [comment]
Thanks for this incredible fast response 🙏🏻 We will keep an eye out for name changes of these parameters then. Feel free to close this issue or keep it open to tackle the name changes.

**Comment by shadowspawn** [comment]
Glad you are unblocked.

For interest, I was expecting it is possible to include the username and password in `N_NODE_MIRROR` as you described. 

> We tried to urlencode the N_NODE_MIRROR

In case of confusion, the "myUser" and "myPassword" values need to be url-encoded in the URL if they contain any special characters, not any of the rest of the URL and not the ':' between the user and password.

**Comment by BreakBB** [comment]
Uff... 🙈 

You are absolutely right! We forgot to urlendcode the special characters. For our defense the curl error message

> curl: (6) Could not resolve host: myUser

is really misleading on this. Correctly urlencoding the `N_NODE_MIRROR` allows us to hand the credentials without the `HTTP_USER` and `HTTP_PASSWORD` parameters.

**Comment by shadowspawn** [comment]
Additions to README in v7.2.2

**Comment by rockyedge** [comment]
Rude what are we doing thos is n
