### ISSUE TITLE
Arrow keys don't work in PowerShell

### ISSUE THREAD

**Issue by tillig** [tj/n#667]
# Bug Report

## Summary

Under
- MacOS Big Sur 11.2.3
- iTerm2
- PowerShell 7.1.3

If you run `n` to get the pick list, while the list is visible, the arrow keys don't actually move the selection at all. It's unclear if this is due to some different handling for arrow keys inside PowerShell or if it's something else about console rendering there.

It _does_ work fine if you use `bash` or `zsh` directly, like if you start `iTerm2` with `bash` as the shell.

It does _not_ work if you start `bash` from _inside_ PowerShell - whatever has taken over the arrow keys has already happened by that time.

## Steps to Reproduce

- Open a terminal with a PowerShell session. Not `bash` and then run PowerShell, but actually start `pwsh` as the shell.
- Run `n`
- Try to change the selection.

## Expected Behaviour

I'd like the selection to change so I can switch Node versions.

## Actual Behaviour

The selection doesn't change.

## Other Information

As noted, I'm not sure if it's something to do with the arrow keys not coming through or if it's something else. I do notice that running `n` starts a `bash` session, and it may be that the nested `bash` inside PowerShell just doesn't work.

It may be nice to have some alternative input keys, things that aren't arrows/meta keys. Maybe angle brackets `<`, `>` or something? Unclear if that'd fix it.

I can work around it by doing

```pwsh
n list
n install [version-from-list]
```

but, again, would be nice to use the pretty menu. :)

## Configuration Details

```bash
$ n --version
? 7.2.1

$ command -v node
? /usr/local/bin/node

$ node -p process.platform
? darwin
```

**Comment by shadowspawn** [comment]
I have not looked into what is failing, but a quick tip. There are alternative keys:

> (You can also use j and k to navigate up or down without using arrows.)

**Comment by tillig** [comment]
YES! j and k do work in PowerShell!

**Comment by shadowspawn** [comment]
Digging... It seems from PowerShell the terminal is in "application mode", but `n` is expecting key sequences from "normal mode", so we are getting a different sequence of characters representing the arrow key.

https://invisible-island.net/ncurses/ncurses.faq.html#cursor_appmode

I will look at coping with both.

**Comment by shadowspawn** [comment]
Fixed in `n` v7.2.2

**Comment by tillig** [comment]
Thanks! So awesome!

**Comment by rockyedge** [comment]
Look im the power shell what do we need
