### ISSUE TITLE
$N_PREFIX ignored during npm -g installs?

### ISSUE THREAD

**Issue by luckman212** [tj/n#670]
_possibly related: #631 and #595_

## Summary

I'm not sure, but seems like `$N_PREFIX` is being ignored during `npm -g install foo`, example:

```bash
$ curl -Ls https://raw.githubusercontent.com/tj/n/master/bin/n -o ~/.n/bin/n
$ chmod u+x ~/.n/bin/n
$ n latest
   installed : v16.1.0 (with npm 7.11.2)
$ npm install -g @bitwarden/cli
```

## Problem

Instead of being placed in `~/.n` the bitwarden package gets installed at `~/n` (without the dot)

Symlink `~/n/bin/bw -> ~/n/lib/node_modules/@bitwarden/cli/build/bw.js`

## Versions and Environment

```bash
$ which npm
/Users/luke/.n/bin/npm

$ npm -v
7.11.2

$ n --version
7.2.2

$ command -v node
/Users/luke/.n/bin/node

$ node -p process.platform
darwin

$ echo $N_PREFIX
/Users/luke/.n

$ echo $NODE_PATH
/Users/luke/.n/lib/node_modules

$ echo $BASH_VERSION
5.1.8(1)-release
```

**Comment by luckman212** [comment]
*edit* not sure if this is really an `n` problem or an `npm` bug. Sorry if it's the latter.

**Comment by shadowspawn** [comment]
I don't think it is `n` as such. Possibly you have a copy of npm installed in that directory from an earlier setup?

Check these as well:
```
command -v npm
npm prefix -g
```

(I am not familiar with how npm 7 decides where to install, but I expect it considers its location, environment variables, and config file settings...)

**Comment by luckman212** [comment]
@shadowspawn Doh! Thanks for the tip. Indeed, I had just changed my `$N_PREFIX` from `n` to `.n` and forgotten to also update `~/.npmrc`.

A quick `npm config set prefix .n` and all's working fine now, sorry for the false alarm!
