### ISSUE TITLE
Specifying NPM version in package.json does not work with auto

### ISSUE THREAD

**Issue by kanadgupta** [tj/n#671]
# Bug Report

## Summary

`n auto` does not use the [`engines.npm` field in `package.json`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) when installing NPM and appears to just use the `npm` version that's associated with a given Node version.

## Steps to Reproduce

Create an empty directory with a package.json like this:
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "engines": {
    "node": "14.15.1",
    "npm": "7"
  }
}
```

From the directory, run:
```sh
n auto
```

## Expected Behaviour

```
       found : /.../test/package.json
        read : 14.15.1
      target : 14.15.1
   installed : v14.15.1 (with npm 7.x)
```

## Actual Behaviour

```
       found : /.../test/package.json
        read : 14.15.1
      target : 14.15.1
   installed : v14.15.1 (with npm 6.14.8)
```

## Configuration Details

```bash
$ n --version
7.2.2

$ command -v node
/usr/local/bin/node

$ node -p process.platform
darwin
```

**Comment by shadowspawn** [comment]
That is expected behaviour currently. `n` installs the target Node.js version which includes a version of node and npm.

(You can leave `npm` out of the install and preserve the installed one with `--preserve`.)

**Comment by kanadgupta** [comment]
I see, thank you for the clarification! Not sure how common of a use case this is, but this would be a great feature to have (either as the default `auto` behavior or as an additional flag), especially as NPM 7 becomes more widely adopted.

Also I just want to say: thanks for your work on this fantastic tool, @shadowspawn!

**Comment by shadowspawn** [comment]
This has not had any activity for over a month. Closing as currently outside the core focus of managing Node.js versions.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by jlarmstrongiv** [comment]
Try running `corepack enable npm` afterwards
