### ISSUE TITLE
Move implementation from Bash to POSIX shell?

### ISSUE THREAD

**Issue by shadowspawn** [tj/n#673]
# Problem

macOS no longer uses Bash as the default shell, and includes Bash v3 when the latest version is v5. Most environments will have a POSIX compatible shell, but not all environments have Bash available by default.

# Solution

`n` could be rewritten as a POSIX shell script?

**Comment by rockyedge** [comment]
Rude but you know its just batch right i can give you 65 percent hit for a
favor

**Comment by shadowspawn** [comment]
No feedback, closing. Something I still have in my backlog as a possible, but likely to be driven by need: an environment that people want to use that has sh and not bash.
