### ISSUE TITLE
how to uninstall n on macos

### ISSUE THREAD

**Issue by johnxiongs** [tj/n#677]
sudo npm uninstall -g n  doesn't work

**Comment by shadowspawn** [comment]
That should work if you used `npm` to install `n` in the first place.

What doesn't work?

What does this show:

```
command -v n
```

**Comment by johnxiongs** [comment]
> That should work if you used `npm` to install `n` in the first place.
> 
> What doesn't work?
> 
> What does this show:
> 
> ```
> command -v n
> ```

It‘s the brew installed another N
