### ISSUE TITLE
Symlink OS node

### ISSUE THREAD

**Issue by GFdevelop** [tj/n#678]
By setting the PATH the os version can't be used, but, as maintainer, I need to use the system installed version to test on the standard environment that all work. Can you provide a feature as `n system` to create a symbolic link to the OS node binary (and npm/npx)?

**Comment by shadowspawn** [comment]
Have a look at `n uninstall`, which has this as one of the use cases.

The idea is by removing the `n` installed version of node and npm, the system installed versions in a different location will be found later in the `PATH`.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
