### ISSUE TITLE
suggested commands for fresh M1 installation

### ISSUE THREAD

**Issue by mesqueeb** [tj/n#679]
# Problem

## Short Version

I'm running the executed commands of the installation:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/3253920/126861614-5d51f1d4-0558-47f6-bd9f-82568d08fba4.png">

This last highlighted line gives an issue on M1 Mac:

```
lucaban@Lucas-iMac ~ % sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
chown: /usr/local/bin: No such file or directory
chown: /usr/local/lib: No such file or directory
chown: /usr/local/include: No such file or directory
chown: /usr/local/share: No such file or directory
```

## Long Version

there is no long version

## Configuration Details

```bash
$ n --version
? 7.3.0
$ command -v node
? # node is not yet installed so shows nothing

$ node -p process.platform
? zsh: command not found: node
```

PS: I had install `n` via `brew install n`

**Comment by mesqueeb** [comment]
After these steps I tried executing `n latest`
and I got about 1000 lines of the same kind of warning:

```
lucaban@Lucas-iMac ~ % n latest
  installing : node-v16.5.0
       mkdir : /usr/local/n/versions/node/16.5.0
       fetch : https://nodejs.org/dist/v16.5.0/node-v16.5.0-darwin-arm64.tar.xz
mkdir: /usr/local/lib: Permission denied
cp: /usr/local/lib: Permission denied
cp: /usr/local/n/versions/node/16.5.0/lib/dtrace: unable to copy extended attributes to /usr/local/lib: Permission denied
cp: /usr/local/lib/node.d: No such file or directory
mkdir: /usr/local/lib/node_modules: Permission denied
cp: /usr/local/lib/node_modules/npm: No such file or directory
cp: /usr/local/n/versions/node/16.5.0/lib/node_modules/npm: unable to copy extended attributes to /usr/local/lib/node_modules/npm: No such file or directory
cp: /usr/local/lib/node_modules/npm/man: No such file or directory
cp: /usr/local/n/versions/node/16.5.0/lib/node_modules/npm/man: unable to copy extended attributes to /usr/local/lib/node_modules/npm/man: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man5: No such file or directory
cp: /usr/local/n/versions/node/16.5.0/lib/node_modules/npm/man/man5: unable to copy extended attributes to /usr/local/lib/node_modules/npm/man/man5: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man5/npmrc.5: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man5/package-lock-json.5: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man5/folders.5: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man5/npm-shrinkwrap-json.5: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man5/package-json.5: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man5/install.5: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1: No such file or directory
cp: /usr/local/n/versions/node/16.5.0/lib/node_modules/npm/man/man1: unable to copy extended attributes to /usr/local/lib/node_modules/npm/man/man1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-init.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-link.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npx.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-star.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-root.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-team.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-ls.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-completion.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-ping.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-docs.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-install-test.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-whoami.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-doctor.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-fund.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-unpublish.1: No such file or directory
cp: /usr/local/lib/node_modules/npm/man/man1/npm-diff.1: No such file or directory
```

**Comment by mesqueeb** [comment]
I've shortened the above

**Comment by mesqueeb** [comment]
Ends in something like this:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/3253920/126861770-2aa75517-2c9c-426e-94dc-8f411e7f8bb6.png">

**Comment by mesqueeb** [comment]
### possible solution:
```
sudo mkdir -p /usr/local/bin
sudo mkdir -p /usr/local/lib
sudo mkdir -p /usr/local/include
sudo mkdir -p /usr/local/share

sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
```

It seems to have worked when I did the above. But is this the recommended approach for M1 macs?
If so, should I make a PR on the readme?

**Comment by shadowspawn** [comment]
I am surprised that `/usr/local/bin` did not exist, but I don't have a fresh Mac to look at to double-check. You didn't trash `/usr/local` for some reason?

I don't think there is a difference in file system layout between M1 and non-M1.

What is in your `/usr/local`? I have:

```
% ls /usr/local
Caskroom	Frameworks	bin		include		n		remotedesktop	share
Cellar		Homebrew	etc		lib		opt		sbin		var
```

**Comment by mesqueeb** [comment]
@shadowspawn now that I've manually added the folders, it looks like this:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/3253920/126862978-ec8b4b9d-65c9-457e-83fa-1ab41b7560c1.png">

Anything else I can help with or share?

**Comment by mesqueeb** [comment]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/3253920/126863006-c0b01936-eec5-48ff-93a0-0f27ae77877d.png">

**Comment by shadowspawn** [comment]
What is in your `PATH`? I would expect `/usr/local/bin` to be there by default.

```
 % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by shadowspawn** [comment]
```
% ls /usr
X11		X11R6		bin		lib		libexec		local		sbin		share		standalone
```

**Comment by mesqueeb** [comment]
@shadowspawn 
```
lucaban@A-Golden-Birdie ~ % echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
```
btw, I'm on Discord: `Luca Ban [Mesqueeb]#4774`

**Comment by shadowspawn** [comment]
My current guess is somehow your `/usr/local` got deleted, meaning the expected folders were missing (and hence the suggested `chown` commands failed).

HomeBrew installs by default to `/usr/local`, but yours has installed to `/opt`. Interesting, but doesn't prove anything!

**Comment by mesqueeb** [comment]
@shadowspawn how can my `/usr/local` be deleted? I literally got this iMac this morning and have been setting it up for the past 3 hours :D

**Comment by shadowspawn** [comment]
I have been looking for references on file system layout, but haven't found details about the very initial folders.

`man hier` does at least mention `/usr/local` but does not say what subfolders exist from the start.

I found one comment from 2015 that initially empty, as you found. (Oh...)

https://apple.stackexchange.com/a/1410

> For what it's worth, /usr/local is not considered a "system" folder by OS X, and on a brand new Snow Leopard install that folder is empty.

And HomeBrew installs differently on ARM vs INTEL.  Intriguing!

```
https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

  if [[ "$UNAME_MACHINE" == "arm64" ]]; then
    # On ARM macOS, this script installs to /opt/homebrew only
    HOMEBREW_PREFIX="/opt/homebrew"
    HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}"
  else
    # On Intel macOS, this script installs to /usr/local only
    HOMEBREW_PREFIX="/usr/local"
    HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}/Homebrew"
  fi
```

 I suspect most people have installed something which creates the usual folder layout by the time they install `n`.

**Comment by mesqueeb** [comment]
@shadowspawn I see. I can pr what I mentioned here:
https://github.com/tj/n/issues/679#issuecomment-886017187

to the readme if you want. with the mention that M1 needs those commands.

For me installing homebrew then installing `n` was like the first two things I did after powering up the new iMac. : D

**Comment by shadowspawn** [comment]
Can go on single line to match the chown, and (with the `-p`) ok to run whether or not folders exist. I don't expect the M1 makes a difference to whether the folders will exist. (But I was wrong about other details!))

```
sudo mkdir -p /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
```

**Comment by shadowspawn** [comment]
Thanks. Hope you enjoy the new computer. 👍
