### ISSUE TITLE
Detect arm64 for M1

### ISSUE THREAD

**Issue by alexpts** [tj/n#683]
**n** use x86_64 arch for M1 macos
```bash
$n 12
$file /Users/alex/.n/bin/node
/Users/alex/.n/bin/node: Mach-O 64-bit executable **x86_64**
```

**Homebrew** use arm64 arch for M1 macos
```bash
$brew install node@12
$file /opt/homebrew/Cellar/node@12/12.22.4/bin/node
/opt/homebrew/Cellar/node@12/12.22.4/bin/node: Mach-O 64-bit executable **arm64**
```

I think **n** must detect arch and install  **arm64** version for M1 CPU

Homebrew formula - https://formulae.brew.sh/api/formula/node@12.json

**Comment by shadowspawn** [comment]
`n` does detect and download arm64 for Node.js v16 on M1 Macs.

`n` uses the pre-built binaries from Node.js downloads. There is not an arm64 build for node v12 (or v14):

- https://nodejs.org/dist/latest-v12.x/
- https://nodejs.org/dist/latest-v14.x/
- https://nodejs.org/dist/latest-v16.x/

Homebrew have their own bottle (binary package) support for Apple Silicon for node@12 and node@14:

- https://formulae.brew.sh/formula/node@12
- https://formulae.brew.sh/formula/node@14

Related: #641 #664

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by L-U-C-K-Y** [comment]
> 

Hi @shadowspawn, it seems that there are now arm64 versions for node 12.

**Comment by shadowspawn** [comment]
@L-U-C-K-Y 
For Mac, it is the darwin versions that are relevant. There are arm64 versions for v16 but not earlier versions of Node.js.

```
node-v16.13.1-darwin-arm64.tar.gz                  01-Dec-2021 11:33            28506601
node-v16.13.1-darwin-arm64.tar.xz                  01-Dec-2021 11:33            18427632
node-v16.13.1-darwin-x64.tar.gz                    01-Dec-2021 12:14            29938975
node-v16.13.1-darwin-x64.tar.xz                    01-Dec-2021 12:15            20056120
```

**Comment by L-U-C-K-Y** [comment]
@shadowspawn thanks! Learned something new 😄

**Comment by jpike88** [comment]
@shadowspawn I think it's worth displaying a warning that this version of node will be run as x64 under rosetta emulation, as there are bugs in some sources that are being compiled and run (e.g. https://github.com/lovell/sharp/issues/3048#)
