### ISSUE TITLE
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n ..... missing n executable

### ISSUE THREAD

**Issue by dman777** [tj/n#684]
on a fresh install of ubuntu focal server.... without node.... I installed n (from zsh) with

```
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
bash n lts
```

It installed everything but the n executable. The actual n executable was missing

So, I deleted the n directory and used `curl -L https://git.io/n-install | bash` (from bash shell instead of zsh this time) and everything worked great.

**Comment by shadowspawn** [comment]
Those two lines install Node.js and not `n`. In particular:
- the `curl` line downloads the `n` script to a local file
- the `bash` line runs `n` to node and npm

Then still up to you how to install `n`, but you now have the option to use `npm` if you wish.

    npm -g n

**Comment by shadowspawn** [comment]
Added extra line to README in `n` v7.4.0

**Comment by k55yhp4bzt-bit** [comment]
** curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
bash n lts
**
