### ISSUE TITLE
Consider automatically symlinking when switching node versions

### ISSUE THREAD

**Issue by JulianKingman** [tj/n#694]
# Bug Report

## Summary

When using certain tools and apps, such as Xcode and Android Studio, they search for node in a particular directory (`/usr/local/bin/node`), and fail to find it. The solution is to run something like `sudo ln -s $(which node) /usr/local/bin/node`, but I believe that would set the location to the currently selected node instance. It would be nice if "n" had an option to automatically link node.

## Steps to Reproduce

Start a new react native project in Xcode with "n" installed and used for node, no global node installed

## Expected Behaviour

Builds successfully

## Actual Behaviour

Complains of non-existing node version

## Configuration Details

```bash
$ n --version
v7.5.0

$ command -v node
/usr/local/bin/node (after symlink)

$ node -p process.platform
darwin
```

Thanks!

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
