### ISSUE TITLE
Failure to extract from xz archive during node installation

### ISSUE THREAD

**Issue by TomRegan** [tj/n#700]
# Bug Report

## Summary

`n` reports a node installation is successful, when in fact it fails to extract the node archive.

## Steps to Reproduce

```bash
$ n install 12.17.0
  installing : node-v12.17.0
       mkdir : /usr/local/n/versions/node/12.17.0
       fetch : https://nodejs.org/dist/v12.17.0/node-v12.17.0-darwin-x64.tar.gz
######################################################################################################################################################### 100.0%
bin/node: Lzma library error:  No progress is possible
   installed : v12.17.0 (with npm 6.14.4)
```

## Expected Behaviour

install command should fail

## Actual Behaviour

install command reports the node version was installed

## Other Information

On my system this results in a state where node is killed by the OS, so it's unusable.

I followed the doc to work around this problem - I configured `n` not to use xz

```bash
export N_USE_XZ=0
```

and the install works as expected.

## Configuration Details

```bash
$ n --version
v8.0.0

$ command -v node
/usr/local/bin/node

$ node -p process.platform
darwin
```

**Comment by shadowspawn** [comment]
I see some clues, but not an answer yet.

1) In your example output the archive being downloaded is the gzip one, but then it tries to use xz to decompress. Not sure how that mismatch can occur.

(The `N_USE_XZ` variable is normalised to "true" or "false" by other code.)

Determining the tar flags:
```
if test "$N_USE_XZ" = "true"; then
  local tarflag="-Jx"
else
  local tarflag="-zx"
fi
```

Determining the file extension:
```
local ext=gz
[ "$N_USE_XZ" = "true" ] && ext="xz"
```

2) The code is checking for a download failure, but may not be detecting a tar failure.

```
do_get "${url}" | tar "$tarflag" --strip-components=1 --no-same-owner -f -
if [[ "${PIPESTATUS[0]}" -ne 0 ]]; then
  abort "failed to download archive for $version"
fi
```

**Comment by shadowspawn** [comment]
What version of tar are you using? 

```
$ tar --version
bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 
```

(The man pages for my tar say it autodetects xz and gzip, and the decompression flags `n` is setting are ignored for extraction!)

**Comment by shadowspawn** [comment]
What version of macOS are you running? e.g.

```
$ sw_vers -productVersion
12.0.1
```

**Comment by shadowspawn** [comment]
I have added detection for tar failing after a successful download in `n` v8.0.1.

One possible explanation if the original problem is no longer reproducible is a transient network problem which was corrupting the downloads.

**Comment by shadowspawn** [comment]
I have made an improvement to the error handling which might help fail more gracefully, and no information supplied to investigate the underlying problem further.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by guillenotfound** [comment]
```
❯ sudo n -d 16.14.1
Alias tip: _ n -d 16.14.1
  installing : node-v16.14.1
       mkdir : /usr/local/n/versions/node/16.14.1
       fetch : https://nodejs.org/dist/v16.14.1/node-v16.14.1-darwin-arm64.tar.xz
############################################################################################################################################################################################################### 100.0%
bin/node: Lzma library error:  No progress is possible
tar: Error exit delayed from previous errors.

  Error: failed to extract archive for 16.14.1
```

```
❯ n --version
v8.0.2
```

What can I do?

**Comment by shadowspawn** [comment]
Hi @guillenotfound 

As a work-around, you can disable xz which will instead download the gz compressed archive. See `--no-use-xz` and the environment variables: https://github.com/tj/n#optional-environment-variables

If you want to debug the problem, please open a new issue and include the tar and macOS versions as per the questions above:
- https://github.com/tj/n/issues/700#issuecomment-983314887
- https://github.com/tj/n/issues/700#issuecomment-983325635
