### ISSUE TITLE
How to set default version and temporary version for current shell ?

### ISSUE THREAD

**Issue by abcfy2** [tj/n#702]
# Problem

Just like `nvm`:

```sh
# Set default version
$ nvm alias default <version>

# Only for current shell
$ nvm use <version>
```

Is there any corresponding operations for `n` ?

Thanks.

**Comment by shadowspawn** [comment]
`n` works differently than `nvm` so there is not direct equivalents. I'll describe the closest match.

`n` changes the installed version of Node.js, while nvm changes your PATH to include the target version of Node.js. 

`n <version>` installs the target version of Node.js. By default this is installed to `/usr/local` and affects all users and shells that have `/usr/local/bin` in their PATH, not just new shells. If you have defined N_PREFIX and added it to your PATH, it affects all processes that have the same environment variables set up. This is the closest equivalent to `nvm alias default <version>`. 

`n` does not modify the current shell so there is no direct equivalent to `nvm use <version>`. `n` does have `n exec <version> <command>` (like nvm). So one way to do something similar is `n exec <version> <shell>` and start a new shell using a particular version of Node.js by having the target version in the PATH, so quite like `nvm`.

**Comment by abcfy2** [comment]
Thanks
