### ISSUE TITLE
mm? can this actually install it somewhere useful?

### ISSUE THREAD

**Issue by PenguinOfTheSky** [tj/n#703]
So it installs node but puts it somewhere where I can't just > node -v
so... it's not very useful to me? if I can't access node, it's basically like it doesn't exist?

**Comment by shadowspawn** [comment]
By default `n` installs the node executable into `/usr/local/bin`. You can change the install location by defining the environment variable `N_PREFIX`.

When you type `node`, the operating system looks for something called `node` in each of the directories in the `PATH` environment variable. `/usr/local/bin` is already in the `PATH` on many operating systems, including macOS, so no extra setup required for the default location. 

You may not have permissions or may not wish to use a system directory, so installing to a folder in your home directory is also common. You can add appropriate lines to your shell startup script to modify `N_PREFIX` and `PATH`, or the the third party product [n-install](https://github.com/mklement0/n-install) does the setup for you.

There is information about all of these in the README, which might make more sense now when you reread it.

**Comment by PenguinOfTheSky** [comment]
Update: functions perfectly following a reboot of linux mint. Has some errors prior to reboot. Dunno if that's somewhere in the readme or not or if it's common in other distros. Might have also been related to installing a version of node prior to installing n

**Comment by PenguinOfTheSky** [comment]
Update: functions perfectly following a reboot of linux mint. Has some errors prior to reboot. Dunno if that's somewhere in the readme or not or if it's common in other distros. Might have also been related to installing a version of node prior to installing n

**Comment by shadowspawn** [comment]
I am glad it is working for you now. Thanks for the update.
