### ISSUE TITLE
NPM 6.14.12 is not present

### ISSUE THREAD

**Issue by brentonstrine** [tj/n#710]
# Bug Report

Version 6.14.12 is not on the server.

## Summary

Use a browser and navigate to https://nodejs.org/dist/. Searching for `6.14.` shows that these are the _only_ versions of 6.14 available:

![image](https://user-images.githubusercontent.com/1900802/150150954-11190b1e-c8f1-4452-a9f4-b71fba157ccd.png)

0-4 are present, but 6.14.5 and beyond are missing. 

## Steps to Reproduce

In a terminal, type the command:

```n 6.14.12```

## Expected Behaviour

Version 6.14.12 is installed.

## Actual Behaviour

```
% n 6.14.12                                       
  installing : node-v6.14.12
curl: (22) The requested URL returned error: 404

  Error: download preflight failed for '6.14.12' (https://nodejs.org/dist/v6.14.12/node-v6.14.12-darwin-x64.tar.xz)
  ```

## Other Information

I am trying to set up this version so my local environment will match the current production version on Netlify. Netlify seems to be using these versions on their production environment:
```
Python  2.7
node v10.24.1 (npm v6.14.12)
ruby 2.6.2
PHP 8.0
```

## Configuration Details

```bash
$ n --version
v8.0.2
$ command -v node
/Users/brentonstrine/.nodenv/shims/node

$ node -p process.platform
darwin
```

**Comment by shadowspawn** [comment]
The Node.js downloads include `node` (and `npm`, and `npx`, and recently `corepack`). But it is node we focus on. The downloads are identified by the node version number. So to match your Netlify setup, your want:

```
n 10.24.1
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
