### ISSUE TITLE
mac OS12.2.1使用n

### ISSUE THREAD

**Issue by ziHan9703** [tj/n#711]
# Problemmac OS12.2.1使用n管理node版本有问题
zsh: bad CPU type in executable: node

## Configuration Details

```bash
$ n --version
?

$ command -v node
?

$ node -p process.platform
?
```

**Comment by shadowspawn** [comment]
Are you on a Mac with Apple Silicon? (Using the Apple M1 chip.)

There is improved support for picking the best architecture from `n` v7.2.1. Update to the latest version of `n` to auto-install a native version of node if it is available for the target version.

If you installed `n` using `npm`, you can update with:
```
npm install -g n@latest
```
