### ISSUE TITLE
Q: What to do for "New patch version of npm available!"

### ISSUE THREAD

**Issue by sskras** [tj/n#716]
# A question

## Short Version

`npm install` prints following: 

```
npm notice New patch version of npm available! 8.5.2 -> 8.5.4
```

1. Does this mean that there is some pending update to implement in the `n` itself?
2. In case I want the latest `npm`, should I wait for it _or_ just follow the advice to update manually?
   (See the full message below)

## Long Version

1. `sudo n latest`
2. `cd our-project`
4. `npm install`
5. The notice is printed at the end of output:

```
npm notice
npm notice New patch version of npm available! 8.5.2 -> 8.5.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.4
npm notice Run npm install -g npm@8.5.4 to update!
npm notice
```

I am Node.js newbie and I am afraid that `npm install -g npm@8.5.4` might break version management for the `n`.

## Configuration Details

```bash
$ n --version
v8.0.2

$ command -v node
/usr/local/bin/node

$ node -p process.platform
linux
```

**Comment by shadowspawn** [comment]
> 1) Does this mean that there is some pending update to implement in the n itself?

Not `n` itself, but yes. By default, `n` installs `node` and `npm` from the target Node.js release. Often there may be a newer version of npm available separately which came out later. New Node.js releases are likely to have new versions of npm but you don't need to wait.

> 2) In case I want the latest npm, should I wait for it or just follow the advice to update manually?

It is fine to update npm manually following the npm instructions. Or stick with the version that came out with the Node.js version. Up to you.

Be warned that by default npm will get over-written and possibly downgraded when you change Node.js versions again using `n`! 

You can use `n --preserve` for this situation, and preserve the existing npm version when you install Node.js. This feature was added specifically so you install the latest npm version and keep it when switching node versions with `n`

> I am Node.js newbie and I am afraid that `npm install -g npm@8.5.4` might break version management for the `n`.

Fair concern, worry not. 😄

**Comment by sskras** [comment]
Thanks a lot, John!

I saw `--preserve` in the help output, but now it's more clear to me about when it's useful. Cheers :)
