### ISSUE TITLE
Unsupported platform: Windows 11

### ISSUE THREAD

**Issue by cekvenich2** [tj/n#719]
Installing from power shell windows 11 via npm returns unsupported

PS C:\Users\vic85> npm install -g n
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@8.1.0: wanted {"os":"!win32"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by shadowspawn** [comment]
Yes, `n` does not work in PowerShell.

See the Support Platforms section in the README: https://github.com/tj/n#supported-platforms
