### ISSUE TITLE
add a command to show all lts versions of node plz

### ISSUE THREAD

**Issue by wangzongqi1001** [tj/n#728]
# Suggestion

Thank you author for creating a perfect tool.

there is a suggestion that n could add a comand like the below.

```bash
$ n ls-remote --lts
```
run the command will show all lts versions of node , it is convenient to user to check which version is lts before installing.

Thank you.

**Comment by shadowspawn** [comment]
What versions would this command display?

Are you wanting:
```console
16.15.0
14.19.3
```

(The above is something I have looked into, but it is hard!)

Or:
```
16.15.0
16.14.2
16.14.1
16.14.0
16.13.2
16.13.1
16.13.0
16.12.0
...
```

**Comment by shadowspawn** [comment]
I think you probably know this since you mentioned `--lts`, but both of these will display (just) the newest LTS version:

```console
% n --lts
16.15.0
% n ls-remote lts
16.15.0
```

**Comment by wangzongqi1001** [comment]
I hope you add a command, which means there isn't such command yet.

Could you add a command which like nvm's command that below.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/29190373/170875413-c6138d55-cef5-4e05-baed-e75ca418e931.png">

run the command will show all node versions of lts.

Thank you

**Comment by shadowspawn** [comment]
The codenames (Argon, Boron, etc) are available to display. Are they very useful for the LTS versions that are past end of life?

**Comment by wangzongqi1001** [comment]
For example, my current version is 16.15.0, if I want to install anyone of lts versions of Fermium, but I don't know the exact version, so I have to search information by Google.

It is convenient that adding  a additional command, if you think there is no need to add a command, just ignore and close the issue.

Thank you

**Comment by shadowspawn** [comment]
In case you didn't know, you can use codenames with `n`. I realise this is different to what you asked for, just letting you know what is current available.

```console
$ n ls-remote --all fermium
14.19.3
14.19.2
14.19.1
  ...
14.15.2
14.15.1
14.15.0
```

**Comment by shadowspawn** [comment]
From a quick look at code, it would be a little tricky but possible to add the codenames. I won't attempt it unless there is some more interest.

Happy to leave this open for a while for feedback from others.

**Comment by shadowspawn** [comment]
Thanks for the suggestion. There have not been any 👍 or other commenters so I'll close this issue.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
