### ISSUE TITLE
Is possible set an specific version by project directory?

### ISSUE THREAD

**Issue by AdsonCicilioti** [tj/n#730]
I don't know if I understood very well, but I would like to know if it is possible to use a specific version dynamically and isolated in a project directory, without having to give a command to switch, for example.

In other words, will the "N" recognize a .nvmrc file in a project directory?

I saw that they support this file. They could include the `.tooling-version` of `asdf`.

**Comment by shadowspawn** [comment]
`n` does not switch node versions in a directory without giving a command of some sort, such as `n install auto` or `n run auto` or `n exec auto`. The `run` and `exec` commands are a one-short command and don't change the installed version.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by vandres** [comment]
@shadowspawn I really would like this feature, too. 

At the moment I am using "n" for switching my local node version. I am working now on projects with multiple developers and multiple node/npm versions. I would like keep using "n", but I don't see a solution yet, to tell other developers how to switch the version. Therefore we might switch to "nvm". They allow to place a `.nvmrc` in the project directory and than call `nvm use`. 

I would love to see the support for a maybe `.n` file and than `n use` :)

**Comment by shadowspawn** [comment]
Have a look in the README at the `auto` target, so you can type `n auto` to switch the version of node based on a configuration file. In particular, this looks for:

- `.node-version`
- `.nvmrc`

**Comment by vandres** [comment]
@shadowspawn Great, thank you!
