### ISSUE TITLE
revert to system version

### ISSUE THREAD

**Issue by arunavabasu-03** [tj/n#733]
# Problem
Basically, I installed n(tj/n)for managing my node versions, and after that, I installed a node version 14.6, it automatically switched my node version to 14.6 and also try to switch my version using the n command but that showed only the one that I installed with n.

- So, is there any way to switch to my main node version (that's installed previously in my system), it overrides my system version ??

**Comment by shadowspawn** [comment]
`n` only tracks the versions of node it has downloaded, and does not show the previous system version.

Whether you still have a system version depends on whether `n` installed to a different location, or overwrote the previous version. By default `n` installs node to `/usr/local/bin/node`. If your operating system has `which` you can see if there are multiple versions of node in your `PATH` with:
```
which -a node
```

If you do have a system version installed to a different location, then you can use `n uninstall` to remove the `n` managed version and go back to the system one.

**Comment by arunavabasu-03** [comment]
thanks, @shadowspawn.
