### ISSUE TITLE
User can't use n on new macOS due to r/w rights changes

### ISSUE THREAD

**Issue by ptrpl4** [tj/n#734]
# Bug Report

## Summary
I installed `n` with Homebrew on macOS 12.4 (21F79) (Apple M1)
It is installed to `/opt/homebrew/bin/n`
I cant see installed Node - `/opt/homebrew/bin/node`
I cant install other Node versions

`mkdir: /usr/local/n: Permission denied`

## Steps to Reproduce
* install node and `n` with homebrew 
* try to use `n`

## Expected Behaviour
`n` shows installed node
`n` can install new node to system 

## Actual Behaviour
`n` doesn't show installed node
`n` can't install new node to system 

## Configuration Details

```bash
$ n --version
v8.2.0

$ command -v node
/opt/homebrew/bin/node (if it was about `node -v` than -  `v18.3.0`)

$ node -p process.platform
darwin
```

**Comment by shadowspawn** [comment]
Have a look at the installation section in the README. You can either use `sudo` (not recommended), or change the permissions on the default install location, or define `N_PREFIX` to install to somewhere you have write permissions like your home folder.

**Comment by shadowspawn** [comment]
> `n` doesn't show installed node

Yes. `n` only tracks the versions of node it has downloaded, and does not show the previous system version or installs by other package managers like homebrew.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by paramaggarwal** [comment]
Home-brew has switched over to using `/opt`, can we consider the same here for `n`?
