### ISSUE TITLE
NPM associated with wrong (missing) version of Node

### ISSUE THREAD

**Issue by bendytree** [tj/n#737]
# Bug Report

## Summary

When I install a specific version of NPM, the associated version of Node is incorrect.

This may be a misunderstanding of how npm works or possibly a nodesource issue.

## Steps to Reproduce

I have a Dockerfile based on Ubuntu 20.04.

```bash
$ curl -sL https://deb.nodesource.com/setup_lts.x | bash -
$ apt-get install -y nodejs
$ npm install -g n
$ n 16.6.1
$ npm install -g npm@7.24.2
```

I've tried the preserve flag and have tried re-ordering the `npm install -g`.

## Expected Behaviour

I check the node version and it looks great:

```bash
$ node -v
v16.6.1

$ which node
/usr/local/bin/node
```

## Actual Behaviour

But from NPM's perspective, it's wrong.

```bash
$ npm install
Unsupported engine, required node 16.6.1, current v16.16.0...

$ npm version
{
  npm: '7.24.2',
  node: '16.16.0',
  ...
```

Why would npm think I'm on node 16.16.0?

## Other Information

```bash
$ n ls
node/16.6.1

$ which npm
/usr/local/bin/npm

$ n which 16.6.1
/usr/local/n/versions/node/16.6.1/bin/node

$ n which 16.16.0
Error: '16.16.0' (16.16.0) not in downloads cache

$ n --version
v9.0.0

$ command -v node
/usr/local/bin/node

$ node -p process.platform
linux
```

**Comment by shadowspawn** [comment]
I'll try reproducing later, this is a quick guess.

After following the setup instructions I think you will have two versions of node and npm installed. And possibly the node is called something different like `nodejs`, but might be found by npm.

I suggest try uninstalling nodejs after getting n installed, and see if that helps. (Or get n available using say curl or wget instead of using nodejs and skip nodejs entirely!)

**Comment by shadowspawn** [comment]
I don't think it sounds like a rehash problem, but I'll add the a link in case proves useful: https://github.com/tj/n/issues/706#issuecomment-1007086519

**Comment by shadowspawn** [comment]
Yup, things are messy after following the steps to reproduce! And the hash is involved too for an interactive session because of the path change for npm. I didn't see your problem as such, but seeing some complications due to the multiple installs.

```
# which -a npm
/usr/local/bin/npm
/usr/bin/npm
/bin/npm
# /usr/local/bin/npm --version
7.24.2
# /usr/bin/npm --version
8.11.0
# /bin/npm --version
8.11.0
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# npm --version
8.11.0
# hash -r
# npm --version
7.24.2
```

**Comment by shadowspawn** [comment]
Here are some alternative steps resulting in a single install of node and npm:

```
# curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
...
# n 16.6.1
...
# npm install -g npm@7.24.2
...
# which -a npm
/usr/local/bin/npm
```

**Comment by bendytree** [comment]
Thanks @shadowspawn for all your help. That got it working for me.

I was using `npm i -g n` because I need `n` available for future commands. I'm pretty awful at bash stuff, but wound up with this:

```bash
$ curl -sL https://raw.githubusercontent.com/tj/n/v9.0.0/bin/n -o n | bash -
$ mv n /usr/local/bin/n
$ chmod +x /usr/local/bin/n
$ n 16.6.1
$ npm install -g npm@7.24.2
```

**Comment by bendytree** [comment]
My issue is resolve, but wanted to share an issue in case it's helpful to others.

I'm installing `n` using the script above and it works great initially. `n`, `node`, and `npm` are all available in `/usr/local/bin`.

Later on, a node script executes a bash script that does some things with `npm install` which gives the error `/usr/bin/env: 'node': No such file or directory`. I cannot for the life of me figure out why it'd be looking for node there. `/usr/bin/env` isn't even a directory.

I've compared `echo $PATH`, `which bash`, `which -a npm`, and `whoami` from when docker is building the image and when the script is run - they all have identical results.

Finally, I tried manually setting the env PATH when I execute the bash script. I literally set it to the exact same path that it already has and it magically works. No idea why this works - maybe a bug in node child_process? In any case, it's setting up the env in a way that somehow finds a mis-configured npm.

**Comment by shadowspawn** [comment]
Some background. `/usr/bin/env` is used to cope with path difference between different setups. Shell scripts start with a "shebang" to specify the interpreter, like:

```
#!/usr/bin/node
```

But what is node is somewhere else, like `/usr/local/bin/node`? Then it will break. `/usr/bin/env` is a utility that is always in that particular folder, and `env` looks up its argument using PATH and invokes it. So it is a portable way of specifying a shell interpreter that vary where it is installed, like `node`.

```
#!/usr/bin/env node
```

**Comment by shadowspawn** [comment]
The issue you hit with `env` failing to find node sounds like the same problem you started with, which was finding the wrong node when there were multiple. I am guessing that particular script is being invoked with a stale idea of where node is located due to the operations that happened before it was called, or how it was called.

In several shells, one way of getting the cache of utility locations to be refreshed is to set the PATH, even to the same value. This can be as explicit as:
```
PATH=$PATH
```

The comment I linked to earlier has what commands work in various shells to reset the cache: https://github.com/tj/n/issues/706#issuecomment-1007086519

**Comment by shadowspawn** [comment]
> Finally, I tried manually setting the env PATH when I execute the bash script.

Oh, setting it in node before spawning the process? That sounds like the child process is not getting the same PATH as your parent process by default. Have you tried echoing PATH from inside the child process?

Anyway, glad you got things working! The mystery of why it broke does not need to be solved. 😄

**Comment by bendytree** [comment]
Yeah, that's the thing - I echoed PATH from inside the process and it looked correct but manually setting it explicitly fixes the issue. It's also strange because there's not a lot of opportunity for the cache to build up. Oh well, it's working now. Thanks again for all your help.
