### ISSUE TITLE
Use node 16, but it doesn't take effect, still use node 12.

### ISSUE THREAD

**Issue by likunyan** [tj/n#738]
OS macOS darwin

n v9.0.0

```shell
➜  ~ n 16
     copying : node/16.16.0
   installed : v16.16.0 to /usr/local/bin/node
      active : v12.22.12 at /Users/example/.nvm/versions/node/v12.22.12/bin/node
```

**Comment by shadowspawn** [comment]
You have (at least) two versions of node installed, and the version that `n` installed is not the first one in the path. The trace statements show the locations of the "installed" node (by `n`) and "active" node.

The version that is active has been installed by `nvm`, which I think modifies the PATH in the current shell. Try disabling `nvm` or running `nvm deactivate` to take it out of the picture.

**Comment by likunyan** [comment]
@shadowspawn Thanks, you completely solved my problem.

**Comment by nilaysahu** [comment]
Yes on the same lines. doing `brew uninstall node@14` solved my problem since 14 was installed via brew and "n" was not able to activate any other version

**Comment by dchicchon** [comment]
I'm having the similar issues on my environment

```
$ sudo n 20.3.0
     copying : node/20.3.0
   installed : v20.3.0 to /usr/local/bin/node
      active : v20.12.0 at /bin/node
```

When I ran `sudo n doctor`
```
...
CHECKS

Checking n install destination is in PATH...
'/usr/local/bin' is not in PATH

Checking n install destination priority in PATH...
good

Checking npm install destination...
There is an active version of npm shadowing the version installed by n. Check order of entries in PATH.
   installed : /usr/local/bin/npm
      active : /bin/npm

Checking prefix folders...
good
```
My assumption is that I should update my PATH so that I am using the correct binary. Would that be the correct step?

**Comment by shadowspawn** [comment]
Yes, either modify your PATH, or delete the "other" version of node.

**Comment by shadowspawn** [comment]
I opened a PR with a detailed walk-through of switching from Homebrew managed Node.js to `n` managed Node.js as the example.

See #802
