### ISSUE TITLE
how to update n to latest version?

### ISSUE THREAD

**Issue by theArianit** [tj/n#741]
How to update `n` when I uninstalled node that I used to install `n`? On Linux

**Comment by shadowspawn** [comment]
`n` does not include a command to update itself. 

Have a look at the installation instructions in the README, skipping over the "if you already have Node.js installed" section since you don't! There are a variety of other ways of installing `n`.

https://github.com/tj/n#installation

For example, you could run:
```
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
chmod 555 n
# sudo not needed if you have write permission to /usr/local/bin
sudo cp n /usr/local/bin/n
```

**Comment by theArianit** [comment]
I tried the curl command but it didn't update. I still have version 8.2.0

**Comment by shadowspawn** [comment]
Perhaps you have `n` installed somewhere different. What does `command -v n` show?

```console
$ command -v n
/usr/local/bin/n
```

**Comment by theArianit** [comment]
it shows the same location as in your comment. `/usr/local/bin/n`

**Comment by shadowspawn** [comment]
The first step in the instructions was to download the new version of `n`, and make sure it is executable. You can check you have the new version before proceeding.
```
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
chmod 555 n
./n --version
```

The second step was to copy it into the default location. Check the version again using the full path, and then using just `n`. If these differ, then you perhaps you have an alias for `n` which points to a different location.
```
# sudo not needed if you have write permission to /usr/local/bin
sudo mv n /usr/local/bin/n
/usr/local/bin/n --version
n --version
```

**Comment by shadowspawn** [comment]
(Alternatively, if you use `npm` to install and manage the version of `n` then you could just leave updating `n` until next time you have Node.js installed!)

**Comment by theArianit** [comment]
I forgot to move n after downloading the new version. now it's on the newest version. thanks for helping me

**Comment by shadowspawn** [comment]
Thank for update
