### ISSUE TITLE
n modules, it doesn't work, cannot download the index.tab or xz file

### ISSUE THREAD

**Issue by lk101** [tj/n#743]
# Bug Report

n works as it.
![image](https://user-images.githubusercontent.com/26990911/196023042-5570bc50-8d1c-4dc5-9733-1d36488be8b7.png)

chrome works as it.
![image](https://user-images.githubusercontent.com/26990911/196023532-b5a15eb1-494f-4d5f-ba87-afa601db0659.png)

## Summary
I configure the N_NODE_MIRROR in ~/.bashrc, but it still doesn't work.
```sh
export N_NODE_MIRROR=https://npmmirror.com/mirrors/node
```
Whatever I configure it or not, it does not work.

## Environment
![image](https://user-images.githubusercontent.com/26990911/196023472-d4181ea6-8f38-406c-8883-26cc3a358bea.png)

## Configuration Details

```bash
$ n --version
v9.0.0

$ command -v node
/usr/local/bin/node

$ node -p process.platform
linux
```

**Comment by shadowspawn** [comment]
From where I am, that custom mirror is slow but working. A command similar to what `n` uses internally to download the index is:

```
$ time curl --silent  --compressed --location --fail --show-error https://nodejs.org/dist/index.tab
... 0.269 total

$ time curl --silent --compressed --location --fail --show-error https://npmmirror.com/mirrors/node/index.tab
... 7.243 total
```

Do those commands fail for you with any additional information?

(That is just for the index, so downloading a version is much larger.)

**Comment by lk101** [comment]
I'm not sure that. Must I install the `curl` ?
![image](https://user-images.githubusercontent.com/26990911/196037941-f2350a59-184a-4c6d-8e04-f050be0daf43.png)

**Comment by lk101** [comment]
It works after I install the `curl`, thanks very much.
