### ISSUE TITLE
Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by Ulrik54** [tj/n#747]
Upon attempting to install `sudo n lts`, and upon executing any `node` or `npm` command, the following message appears:
```bash
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/node
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/node
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```
How can I fix this? Searching the internet for an answer has only returned similar problems for other projects, with solutions being specific to those projects.

n v9.0.1
/usr/local/bin/node
OSX 10.11.15

**Comment by shadowspawn** [comment]
Try installing node 12. I think your macOS version is too old to run Node.js 18.

Node.js 14 raised oldest supported version of macOS from 10.10 to 10.13:
- https://github.com/nodejs/node/pull/32454/files
- https://github.com/nodejs/build/issues/2168

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
