### ISSUE TITLE
Add Support to Windows ARM

### ISSUE THREAD

**Issue by pierophp** [tj/n#755]
# Bug Report

## Summary

When I try to install the package on my Windows ARM, I get this message:

npm -g i n
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@9.0.1: wanted {"os":"!win32"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

## Steps to Reproduce

Using Windows ARM

**Comment by shadowspawn** [comment]
What shell are you using? `n` is implemented as a unix shell script and does not work in a Windows shell.

See the Supported Platforms section in the README for more: https://github.com/tj/n#supported-platforms

**Comment by pierophp** [comment]
It was my bad. I was trying to use it on a Windows inside my Mac M1 using Parallels. But, using that way, I cannot use WSL, because M1 does not support Nested Virtualization.

As Windows is not supported, this issue can be closed unresolved. Thank you.

**Comment by shadowspawn** [comment]
(Thanks for the update)
