### ISSUE TITLE
Is n package supported in windows?

### ISSUE THREAD

**Issue by AhmedAymanBfcai** [tj/n#758]
Hi John, 

I hope you are well.

I am trying to install n package in windows 10. But I think it's not supported in windows.

I have this error:
`npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@7.5.0: wanted {"os":"!win32"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
`

I used and need yamljs not actually n package but It seems that yamljs depends on n package.

Thanks in Advance:)

**Comment by shadowspawn** [comment]
`n` is not supported in Windows, as noted in the README: https://github.com/tj/n#supported-platforms

I had a look at the npm package `yamljs` and it does not depend on `n`. What makes you think you need to install `n`? (Perhaps the problem is about something else and installing `n` is not the solution.)

**Comment by AhmedAymanBfcai** [comment]
Hi John,

Thanks for your reply:)

I also can confirm what you said. But When I am trying to install yamljs. I found this error:
`npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.       
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@7.5.0: wanted {"os":"!win32"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
`
Thanks ~

**Comment by shadowspawn** [comment]
Thanks for the update, glad you worked it out.
