### ISSUE TITLE
Openwrt compatibility

### ISSUE THREAD

**Issue by chuyueye** [tj/n#759]
# Problem
curl: option --compressed: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information

## Short Version

I am using " n lts ",and here is the result.
## Long Version
7.86
[curl -V output]
curl 7.86.0 (aarch64-openwrt-linux-gnu) libcurl/7.86.0 mbedTLS/2.28.2 nghttp2/1.44.0
Release-Date: 2022-10-26
Protocols: file ftp ftps http https mqtt
Features: alt-svc HSTS HTTP2 IPv6 Largefile SSL threadsafe

## Configuration Details
openwrt (kernel 5.10.161,branch 01.10.2023 by Kiddin)

Linux OpenWrt 5.10.161 #0 SMP Sat Jan 7 20:00:16 2023 aarch64 GNU/Linux

```bash
$ n --version
?
v9.0.1
$ command -v node
?
/usr/bin/node
$ node -p process.platform
?
linux

**Comment by shadowspawn** [comment]
I tried deleting `curl` and installing `wget` to see whether `curl` options was the only problem, but then hit missing support in `tar`.

```
# ./n 17
  installing : node-v17.9.1
       mkdir : /usr/local/n/versions/node/17.9.1
       fetch : https://nodejs.org/dist/v17.9.1/node-v17.9.1-linux-x64.tar.gz
tar: unrecognized option: strip-components=1
...
```

I installed `tar` to get a more featured version then from BusyBox, then hit:
```
# ./n lts
  installing : node-v18.14.0
       mkdir : /usr/local/n/versions/node/18.14.0
       fetch : https://nodejs.org/dist/v18.14.0/node-v18.14.0-linux-x64.tar.xz
     copying : node/18.14.0
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
   installed : 
```

Is Openwrt using musl libraries like Alpine? The standard binary builds of node do not support that, but could perhaps download from an unofficial mirror... #648

This might be more problems than you are interested in solving!

(I was running Openwrt using `docker run --rm -it openwrtorg/rootfs`.)

**Comment by shadowspawn** [comment]
A reply was provided, and no further activity in a month. Closing this as stale.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
