### ISSUE TITLE
Node-v12.18.0 unavailable for download

### ISSUE THREAD

**Issue by HannaO25** [tj/n#761]
# Bug Report

## Summary
=> https://github.com/nodejs/node/issues/47121

We have a jenkins job which perform a command to install nodejs:
"+ /var/lib/jenkins/workspace/CCSP_BACK_RELEASE_hotfix_v1.14.9/node_modules/n/bin/n 12.18.0"

But the url to uplaod files (https://nodejs.org/dist/v12.18.0/node-v12.18.0-linux-x64.tar.xz) has change.
We had a look at nodejs.org and the working url is : https://nodejs.org/dist/v12.18.0/v12.18.0-linux-x64.tar.xz.
The command get 404 and we can not modify the url.

## Other Information
plateform : Linux RECBACK 4.19.0-18-amd64 https://github.com/nodejs/node/pull/1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
subsystem : /var/lib/jenkins/workspace/CCSP_BACK_RELEASE_hotfix_v1.14.9/node_modules/n/bin/n 12.18.0
Error: download preflight failed for '12.18.0' (https://nodejs.org/dist/v12.18.0/node-v12.18.0-linux-x64.tar.xz)

## Configuration Details

```bash
$ n --version
?

$ command -v node
?

$ node -p process.platform
?
```

**Comment by shadowspawn** [comment]
There is an ongoing problem with intermittent 404s affecting downloads:

- https://status.nodejs.org
- https://github.com/nodejs/nodejs.org/issues/5149

**Comment by shadowspawn** [comment]
Is this fixed now? (i.e. by the Node.js fix)

**Comment by shadowspawn** [comment]
The linked issue has been closed and the Node.js outage has been resolved. Hopefully solved!
