### ISSUE TITLE
Is there a way to install from .tgz or binary file instead of downloading from remote?

### ISSUE THREAD

**Issue by Lovasz-Akos** [tj/n#769]
# Question

I'd like to install node from a previously downloaded .tgz or binary file instead of downloading from remote every time, is this already supported and I just missed it or any plan on supporting this?

**Comment by shadowspawn** [comment]
There is not support for specifying your own .tgz or binary file. But `n` does not download from remote every time. The downloaded file is cached the first time and used if the same version is installed again in the future.

```
$ n 19
  installing : node-v19.9.0
       mkdir : /usr/local/n/versions/node/19.9.0
       fetch : https://nodejs.org/dist/v19.9.0/node-v19.9.0-darwin-arm64.tar.xz
     copying : node/19.9.0
   installed : v19.9.0 (with npm 9.6.3)
$ n 19
     copying : node/19.9.0
   installed : v19.9.0 (with npm 9.6.3)
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by dguo** [comment]
For what it's worth, the output snippet gave me a hint for a hacky way of doing this. By uncompressing a file and moving the contents to the right place, `n` will go ahead and use them as if it had fetched them.

So this worked for me:
```sh
sudo mkdir -p /usr/local/n/versions/node/16.20.2
sudo tar xvf node-v16.20.2-linux-x64.tar.xz -C /usr/local/n/versions/node/16.20.2 --strip-components=1
```

**Comment by CreateSun** [comment]
> For what it's worth, the output snippet gave me a hint for a hacky way of doing this. By uncompressing a file and moving the contents to the right place, `n` will go ahead and use them as if it had fetched them.
> 
> So this worked for me:
> 
> ```shell
> sudo mkdir -p /usr/local/n/versions/node/16.20.2
> sudo tar xvf node-v16.20.2-linux-x64.tar.xz -C /usr/local/n/versions/node/16.20.2 --strip-components=1
> ```

works for me, thanks!

**Comment by shadowspawn** [comment]
You can download a version of node without activating it using `--download`, so available for installing later.

```console
$ node --version
v22.4.0
$ n --download 16.20.2
  installing : node-v16.20.2
       mkdir : /usr/local/n/versions/node/16.20.2
       fetch : https://nodejs.org/dist/v16.20.2/node-v16.20.2-darwin-arm64.tar.xz
$ node --version
v22.4.0
$ n 16.20.2
     copying : node/16.20.2
   installed : v16.20.2 (with npm 8.19.4)
$ node --version
v16.20.2
```
