### ISSUE TITLE
Add Node.js 14.21.4 ?

### ISSUE THREAD

**Issue by xet7** [tj/n#773]
Hi,
can you add Node.js 14.21.4 ?

https://github.com/wekan/node-v14-esm/releases

**Comment by shadowspawn** [comment]
`n` supports the user using node builds from other sources if there is meta information about available builds in the same layout that Node uses. This is done by the user defining `N_NODE_MIRROR`:

- https://github.com/tj/n#custom-source

There is not support for targeting specific versions specially, which I think is what you are asking.

**Comment by xet7** [comment]
@shadowspawn 

Currently when I type `sudo n 14.21.3` then it installs from original source.

Is it possible to update `n` so that if I type `sudo n 14.21.4` then it would install that version, without defining custom source? 

Otherwise, I would have to define custom source in very many places.

**Comment by xet7** [comment]
@shadowspawn 

I use `n` with Linux at x64, arm64, s390x and risc-v.

**Comment by shadowspawn** [comment]
> Is it possible to update n so that if I type `sudo n 14.21.4` then it would install that version, without defining custom source?

No. The current model is that `n` refers to a single authoritative web source. The user can change that authoritative source. But `n` does not maintain a list of alternative sources.

There is a somewhat similar situation with Alpine builds. The user needs to opt-in to a source which has alpine builds available. See #648
