### ISSUE TITLE
Download version indexes failure, version switch failure!

### ISSUE THREAD

**Issue by walnut-tom** [tj/n#776]
# Bug Report

## Summary
n v8

curl: (22) The requested URL returned error: 502
  Error: failed to download version index (https://npmmirror.com/mirrors/node/index.tab)

script returned exit code 2

## Expected Behaviour

Ignore the error, and use local installed node.

## Actual Behaviour

exit code 2

## Configuration Details

```bash
$ n --version
v9.1.0

$ command -v node
/usr/local/bin/node

$ node -p process.platform
linux

$ node -v
v18.16.1



```

**Comment by shadowspawn** [comment]
`n` uses the `index.tab` file to look up the available versions to expand incomplete versions like `v8` and will fail if it is not available.

To install a local version without consulting `index.tab`, you can either:
- use a full version, like `n v18.16.1`
- select from local versions using the menu, just type `n`

**Comment by shadowspawn** [comment]
Ignoring the error would mean that the same command could install different versions depending on the internet connection. That is not something I want to do.

`n ls` lists the local versions. You could script installing a purely local version. Is that something that suits your use case? 

A related issue including example script: https://github.com/tj/n/issues/727#issuecomment-1163904877

**Comment by walnut-tom** [comment]
ok. thank you!

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
Added --offline option in n v9.2.0
