### ISSUE TITLE
Fresh install of n can't be used

### ISSUE THREAD

**Issue by Lovasz-Akos** [tj/n#782]
# Bug Report

## Summary
Just installed n with `npm install -g n` and using `n latest` breaks
## Steps to Reproduce
`npm install -g n`
`n latest`

## Expected Behaviour
Installs latest nodejs

## Actual Behaviour
$ n latest
/bin/n: line 108: syntax error: unexpected "("

## Configuration Details

```bash
$ n --version
also returns 
/bin/n: line 108: syntax error: unexpected "("

$ command -v node
/bin/node

$ node -p process.platform
linux
```

**Comment by Lovasz-Akos** [comment]
fixed by using the POSIX compliant version on the POSIX branch

**Comment by shadowspawn** [comment]
What version of Bash are you using in the failing environment? 

There is some interesting syntax on that line, so maybe a really old or really new version of Bash is complaining:

https://github.com/tj/n/blob/02a8fe0c540576e0108b4e6f1797f2e71bc3dffc/bin/n#L108

**Comment by Lovasz-Akos** [comment]
I'm using sh, not bash, that might be the issue here

**Comment by shadowspawn** [comment]
The `n` script starts with a shebang interpreter directive to use bash:

https://github.com/tj/n/blob/02a8fe0c540576e0108b4e6f1797f2e71bc3dffc/bin/n#L1

So in theory you can use `sh` (or `zsh` et al) as your shell, but the `n` script is interpreted using `bash`.

> What version of Bash are you using in the failing environment?

Assuming you have a bash available, what I meant was what version is it? For example, I see:

```console
% bash --version 
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by Lovasz-Akos** [comment]
Sadly no bash, it's a super barebones buildroot system i'm testing, I don't even have `apt`  or `curl` which makes changing node versions...difficult. `n` comes to save the day, since I do have `npm`, but that syntax breaks on `sh`.  #751 's changes fix this so I'm looking forward to it's merge or completion :)

**Comment by shadowspawn** [comment]
Thanks for the info. A vote for the posix compatible version. :-)

**Comment by shadowspawn** [comment]
> and it couldn't switch my active install

That sounds like an issue with node installed twice, likely once into `/usr/bin` (by some other process) and into `/usr/local/bin` by `n`. The version which is found depends on the order of directories in the `PATH` environment variable.

If you run `n doctor` it will check for this situation.
