### ISSUE TITLE
OS recogonition mistakes

### ISSUE THREAD

**Issue by zzzgit** [tj/n#786]
I got:

```
npm ERR! notsup Unsupported platform for n@9.2.0: wanted {"os":"!win32"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

My system is:

`13th Gen Intel(R) Core(TM) i5-13400F   2.50 GHz, Win10 64`

**Comment by shadowspawn** [comment]
`n` should work in a unix/Linux shell in WSL, but does not work in Windows native shells like PowerShell or cmd.

**Comment by zzzgit** [comment]
> `n` should work in a unix/Linux shell in WSL, but does not work in Windows native shells like PowerShell or cmd.

I tried gitShell on win10 but failed.

**Comment by shadowspawn** [comment]
Yes, gitShell has enough BASH functionality for git but I don't think is a full unix shell. (I have not looked at it for a long time.) From the README:

> `n` does not work in native shells on Microsoft Windows (like PowerShell), or Git for Windows BASH, or with the Cygwin DLL.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
