### ISSUE TITLE
LTS downloading stable instead of LTS

### ISSUE THREAD

**Issue by necipallef** [tj/n#788]
# Bug Report

LTS downloading stable instead of LTS

## Summary

Running `n lts` downloads node version `20.x.y`, it should instead download `18.x.y`

## Steps to Reproduce

Run `n lts`

## Expected Behaviour

Node 18 is installed, as it is [the LTS version](https://nodejs.org/en/blog/release/v18.12.0).

## Actual Behaviour

Node 20 is installed. Node 20 is the stable version.

## Other Information

It seems like the option LTS is treated the same as stable, but they should not be the same.

**Comment by necipallef** [comment]
never mind, it turns out that LTS is actually Node20. I misread the articles in Node website.

**Comment by shadowspawn** [comment]
Long ago Node.js used `stable` to describe a stable version which at the time was an even numbered release.

The modern terminology is _LTS_ and _current_. Often there are two LTS versions, one in _active_ development and one in _maintenance_. See https://nodejs.org/en/about/previous-releases and https://nodejs.org/en/blog/release/v20.10.0

Were you expecting  `stable` to mean the LTS version that is in maintenance mode? Did you see that usage somewhere? I have not seen that usage defined and `n` does not support a target release name for that.

**Comment by shadowspawn** [comment]
(I commented before seeing you has closed issue. Some bonus background anyway!)
