### ISSUE TITLE
Default install location (N_PREFIX) to home

### ISSUE THREAD

**Issue by SrBrahma** [tj/n#791]
By having the install location by default at home, big part of the README could be removed:

![image](https://github.com/tj/n/assets/28177550/fbc886ae-0544-4f7c-a7ca-6bd912518615)

This would ease the usage for new users.

This would, of course, be in a different major.

**Comment by shadowspawn** [comment]
Interesting suggestion.

A complication is installing to the home directory requires changes to `PATH`, with the appropriate file depending on the shell. I think this is similarly an obstacle for new users. (`n-install` wraps this up nicely.)

**Comment by SrBrahma** [comment]
I understand. I have no workaround ideas so I will close this.

Thanks!

**Comment by SrBrahma** [comment]
@shadowspawn I just realized you mentioned the n-install. I was seeing my starred repos and I found it there, as I already used in the past but forgot about it.

Maybe we could have it linked in the beginning of the installation section in the readme? Giving it a quick read I couldn't find it.

I can do it on a PR if you agree and want ;)

**Comment by shadowspawn** [comment]
`n-install` is included in the third part installers section:

https://github.com/tj/n#third-party-installers
