### ISSUE TITLE
 N_NODE_MIRROR, Error: failed to download version index  + "error": "this version doesn't exist: index.tab"

### ISSUE THREAD

**Issue by gowy222** [tj/n#805]
Description: 
When attempting to use the n package with the N_NODE_MIRROR environment variable set to https://mirrors.cloud.tencent.com/npm/node, the command export N_NODE_MIRROR=https://mirrors.cloud.tencent.com/npm/node && npm i n -g && n lts fails with the following error:

Error: failed to download version index (https://mirrors.cloud.tencent.com/npm/node/index.tab)

However, the URL https://mirrors.cloud.tencent.com/npm/node itself returns a JSON response and no index.tab

Steps to Reproduce:

Set the N_NODE_MIRROR environment variable: export N_NODE_MIRROR=https://mirrors.cloud.tencent.com/npm/node
Install the n package globally: npm i n -g
Attempt to install the LTS version of Node.js: n lts
Expected Behavior: The n package should successfully download and install the LTS version of Node.js using the specified mirror.

Actual Behavior: The command fails with the error:

Error: failed to download version index (https://mirrors.cloud.tencent.com/npm/node/index.tab)

Is it possible to make https://mirrors.cloud.tencent.com/npm/node this JSON response compatible?

**Comment by shadowspawn** [comment]
That URL is to a mirror of the npm package of node. What you want is the mirror of the nodejs releases:

```
N_NODE_MIRROR=http://mirrors.cloud.tencent.com/nodejs-release/
```

```console
% N_NODE_MIRROR=http://mirrors.cloud.tencent.com/nodejs-release/ n --latest
22.4.1
```
