### ISSUE TITLE
Using `auto` or `engine` is inconvenient due to lack of fallback

### ISSUE THREAD

**Issue by elibarzilay** [tj/n#811]
# Problem

## Short Version

As the title says.  Using `auto` is convenient, but making it be strict by throwing an error is inconvenient.

## Long Version

It is often convenient to use `auto`, but use some other version as a fallback -- making it possible to have a sane default.

What I mean by "sane" is that there *is* a known default.  For example, say that I'm writing some shared script that runs `node` as part of many other pipeline definitions.  I *could* use `n` without output and without failing on an error code -- but what would I tell my consumers?  "This will run `node whatever` for you using the version in your config, or if unspecified, using ... the last version that `n` installed by previous random code...?"

Instead, I would like a way to turn that into "..., or if unspecified, using the current `lts` version".

The error-detecting dance in https://github.com/tj/n/issues/726#issuecomment-1135507307 can be used for this, but
* You need to know that you can do that,
* You need to be willing to pay the overhead price -- sometime not negligible (eg, a shell function for interactive use that runs `n` on every directory change).
* And you need to face other complexities (eg, the snippet in that comment is good for running `node`, but what about `npm` or whatever?).

So all in all, this becomes a tedious chore for a common convenience.

## Suggestion

It would be nice if I could specify "`auto`, but <whatever> if that fails" and be done with it.

* One way to get it done is what I suggested in #806, eg, `auto:lts` uses `lts` if `auto` fails.

* Another way is to have some `$N_FALLBACK_VERSION` to use in case `auto` fails.  Makes it a little more verbose, and require a bit more shell knowledge.

* Yet another possible way, more similar to other node managers, is to have some way to set a version as the default for failures.  A cute way to do that is to use a `default` symlink in `$N_PREFIX` that points to whatever the default should be.  This is probably a bigger change though.

## Configuration Details

Current `n`.

See also #806.

**Comment by shadowspawn** [comment]
This issue has not had any upvotes in a couple of months. It isn't likely to get acted on due to this report.

Interesting idea, but I currently don't think the cost/benefit is enough to add code to do this (see https://github.com/tj/n/pull/806#issuecomment-2240933249).

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.

**Comment by ebarzilay-godaddy** [comment]
@shadowspawn, I still have the same interest (promoting more use of `n` in cicd pipelines), and I still am not sure what the cost would be.  IIRC, you were concerned about the additional complexity, which I think is (a) minimal-ish, (b) could be even smaller with limiting things more (eg, using an env var as a fallback), (c) I'm not going anywhere so it's not like future problem will get a "not my problem" reply...

**Comment by shadowspawn** [comment]
> Yet another possible way, more similar to other node managers, is to have some way to set a version as the default for failures.

I am interested in prior art and other implementations. What ways that other node managers are setting a default for failures did you have in mind?

**Comment by elibarzilay** [comment]
I don't remember the exact details, but I remember something like just `nvm install` using the version in `.nvmrc` but not failing if it's missing.  But now that I try it, it *does* fail, so that's not it.  I'll try to figure out what I saw at some point...
