### ISSUE TITLE
should not network curl `index.tab` when using numeric `.node-version`

### ISSUE THREAD

**Issue by loynoir** [tj/n#812]
# Bug Report

should not network curl `index.tab` when using numeric `.node-version`

## Summary

should not network curl `index.tab` when using numeric `.node-version`

## Steps to Reproduce

```sh
$ echo 22.6.0 > .node-version
```

## Expected Behaviour

Everytime command install or exec using numeric `.node-version`, should not network curl `index.tab`.

## Actual Behaviour

Everytime command install using numeric `.node-version`, network curl `index.tab`.

```sh
$ bash -x `which n` install auto |& grep index.tab 
++ local index_url=https://nodejs.org/dist/index.tab
++ do_get_index https://nodejs.org/dist/index.tab
++ curl --silent --location --fail --show-error --silent https://nodejs.org/dist/index.tab
```

Everytime command exec using numeric `.node-version`, network curl `index.tab`.

```sh
$ bash -x `which n` exec auto node --version |& grep index.tab
++ local index_url=https://nodejs.org/dist/index.tab
++ do_get_index https://nodejs.org/dist/index.tab
++ curl --silent --location --fail --show-error --silent https://nodejs.org/dist/index.tab
```

## Configuration Details

```bash
$ n --version
v9.2.3

$ command -v node
/usr/local/bin/node

$ node -p process.platform
linux
```

**Comment by shadowspawn** [comment]
Nice reproduction steps, thanks.

The way `auto` and `engine` are implemented does not currently benefit from the fast-path for fully specified numeric version specified on command-line.

Performance has become of more interest since we added `exec` and `run`, since they are lightweight compared with an install.

**Comment by shadowspawn** [comment]
(You can avoid the network call manually by adding `--offline`, but this issue identifies an improvement for the default behaviour.)

**Comment by shadowspawn** [comment]
Improved in v10.0.0
