### ISSUE TITLE
Quick installation alternative?

### ISSUE THREAD

**Issue by ebarzilay-godaddy** [tj/n#819]
# Question / Installation docs

This more of a question that can lead to a documentation change:

The installation instructions talk about bootstrapping using `curl | bash` and then doing an actual `npm install n`.

AFAICT, and after doing it for a while, there's no reason for using `npm` at all, and instead I just `curl` the file straight to `/usr/local/bin/n` and declare victory.  The fact that this should be fine is further supported by `make install` doing exactly that.

I do see some reason that some people might want:
* Using a standard command instead of knowing where to put the file or how to `chmod` it
* Same for uninstalling it
* Using a blessed version instead of `master`

But if I know what I'm doing, is there any reason not to just drop the file in?

And if so, maybe mention that in the installation instructions?

**Comment by shadowspawn** [comment]
> Using a standard command instead of knowing where to put the file or how to `chmod` it

Yes, the `chmod` step puts me off a little when I consider describing manually-installing. 

> But if I know what I'm doing, is there any reason not to just drop the file in?

The main factor I have been taking into account is checking for updates and installing updates for `n` itself. You get this with `npm install --global`, `n-install`, Homebrew, and MacPorts.

**Comment by shadowspawn** [comment]
For historical interest, I did have saving the download in the instructions (albeit not explicitly in a permanent location), but removed the extra step: #754

There is a clue in the instructions for expert users that it is `n` itself and not some special install script:

> If `npm` is not yet available, one way to bootstrap an install is to download and run `n` directly.

**Comment by ebarzilay-godaddy** [comment]
Yeah, but the thing that I was worried about is that it sounded sufficiently indirect that I wasn't sure that it might break.

FWIW, if there was some quick comment about the `githubusercontent` url just fetching the current version, and that there's nothing else needed, and that you can use it ("if you know how", ie, chmodding, sudoing), then that would be sufficient.

(The point of keeping an updated version makes sense, but I'm doing this from a CICD runner, so updates are a moot point anyway, and a simpler installation is much preferred...)

**Comment by shadowspawn** [comment]
I noticed `nave` has manual install instructions as the suggested way: https://github.com/isaacs/nave#installation

**Comment by shadowspawn** [comment]
FYI @ebarzilay-godaddy 

Opened PR for README: #822
