### ISSUE TITLE
Running "n stable" removed bin, lib, share and include directories from /usr/local

### ISSUE THREAD

**Issue by davidcornu** [tj/n#86]
I believe this has something to do with the following lines (https://github.com/visionmedia/n/blob/master/bin/n#L138-156). Am still investigating as to why exactly this happened.

Running the latest version from master on Mac OS X 10.8.2. 

**Notes**
- Adding `echo $N_PREFIX` on line 143 returns `/usr/local`, which seems normal as line 6 is `N_PREFIX=${N_PREFIX-/usr/local}`.
- Tested on a fresh ubuntu 12.04 install, got the same result

**Comment by jasonkarns** [comment]
Permalink for code reference post by @davidcornu in original post (for posterity): https://github.com/tj/n/blob/77946bb9c69c8ac365fb4d2ea9e666e417dfdc3c/bin/n#L138-156
